### ISSUE TITLE
Route transition animation

### ISSUE THREAD

**Issue by emildimitrov** [router5/router5#100]
Hi, guys,

I'm using router5 for few months already and everything is very sweet :) 
Recently our team decided to enrich the user experience by animating the page transitions. We'r looking for integration between react-motion and router5, so i will be very happy if you give your two cents about this. how you approach it? any best practices? Is it good idea at all?

Regards,
Emil Dimitrov

**Comment by troch** [comment]
Yes, it is a good idea to use an animation library like react-motion (or any library you are familiar with). It doesn't need to be integrated with router5, it only needs to be integrated with React ;). If you are familiar with animating components based on state / props changes, then there is nothing different with route level components.

The problems you'll encounter are the same one you'll encounter with animation in general: loading data while animating can cause the content of the animated components to change and some frames will be dropped.

For react-motion, it would look something like that (not tested, just to give you an idea):

```js
import React, { Component } from 'react';
import { TransitionMotion, spring } from 'react-motion';
import { withRoute } from 'react-router5';

export class ViewContainer extends Component {
    getStyles = () => this.props.route
        ? [{ route: this.props.route, style: { opacity: spring(1) }}]
        : [];
    willEnter = (key) => ({ opacity: 0 });
    willLeave = (key) => ({ opacity: spring(0) });

    renderRouteComponent({ route, style }) {
        switch(route.name) {
            case 'home':
                return <Home { ...route.params } style={ style } />;
            default:
                return <div>No route found</div>;
        }
    }

    render() {
        return (
            <TransitionMotion styles={ this.getStyles() } willEnter={ this.willEnter } willLeave={ this.willLeave }>
                { data => <div>{ data.map(this.renderRouteComponent) }</div> }
            </TransitionMotion>
        );
    }
}

export default withRoute(ViewContainer);
```

**Comment by emildimitrov** [comment]
@troch thank you for the valuable insights. Will give it a try and will share the result

**Comment by LeonardoGentile** [comment]
@emildimitrov did you experiment on this?
Have you found something nice to share?

**Comment by emildimitrov** [comment]
@LeonardoGentile  we'v put this as prod enhancement in our backlog. As soon is comes into priority for implementation i'll share it.

**Comment by faizrr** [comment]
Here's how I achieved the result using `react-transition-group`

```js
class ContentWithPage extends PureComponent {
  render() {
    const { route } = this.props

    return (
      <Content>
        <TransitionGroup>
          <CSSTransition
            classNames="fade"
            timeout={{ enter: 300, exit: 300 }}
            key={route.name}
            appear
            exit={false}
          >
            {React.createElement(
              componentByRoutename[route.name]
            )}
          </CSSTransition>
        </TransitionGroup>
      </Content>
    )
  }
}
```
