### ISSUE TITLE
Using allowNotFound to serve 404 pages redirects to /null

### ISSUE THREAD

**Issue by razor-x** [router5/router5#101]
I am trying to get navigating to an unknown route `/does/not/exist` with `allowNotFound` to serve a 404 page at that path.

The `@@router5/UNKNOWN_ROUTE` state is transitioned to correctly, but then the page is redirected to `/null`.

I've poked around, and it looks like the browser plugin is calling `buildPath` from [route-node](https://www.npmjs.com/package/route-node) (at [this line](https://github.com/router5/router5/blob/07dd1ec590f83b09d2dab2d0d96c45dc8b9b8448/dist/es/core/utils.js#L89)), but since the route is not found in the routes list, it returns `null` and the URL gets updated to `null`.

**Comment by troch** [comment]
Is it something which happens on start, on a normal transition (link), or on a transition triggered by a `popstate` event?

**Comment by troch** [comment]
Fixed in version 4.3.4
