### ISSUE TITLE
Match route on both trailing slash and not

### ISSUE THREAD

**Issue by vivekbhagwat** [router5/router5#102]
Hi, we have a router5 setup with `trailingSlash: false` as a configuration – however we'd like to match a path in both cases if trailing slash is provided and if it isn't, e.g. (`example.com/faq` and `example.com/faq/` should both match the same route – either by forced redirect or multiple matching. I see you reference the concept in this issue from a while ago here: https://github.com/router5/router5/issues/16 and I was wondering since there's been quite a bit of development since then, if you've made any progress on this front. Thanks!

**Comment by troch** [comment]
The naming of the option is not very explicit, but `trailingSlash` should be set to a truthy value if you want them to be optional.

[http://router5.github.io/docs/router-options.html#optional-trailing-slashes](http://router5.github.io/docs/router-options.html#optional-trailing-slashes)
