### ISSUE TITLE
Do not omit hash on initial page load when using History API

### ISSUE THREAD

**Issue by iotch** [router5/router5#104]
Hello! With the browser plugin enabled, and when it's `useHash` option is set to `false` IMO router should not omit the hash part of the url on initial page load. Now it is impossible to reload a page with the hash in the url - hash gets removed on reload.

It happens here, I believe - https://github.com/router5/router5/blob/master/modules/plugins/browser/browser.js#L31
Thanks!

**Comment by troch** [comment]
Yep, it is a request I've had before, will look at it.

**Comment by iotch** [comment]
Hello. Is there any progress on it? Thanks!

**Comment by troch** [comment]
Unfortunately, I haven't had the time to look at it. Will do at some point though, unless someone beats me to it with a PR :)

**Comment by iotch** [comment]
I think I found the causing code, will try to send a PR today.

**Comment by iotch** [comment]
Should the hash be appended on replacing state as well? Now the hash being preserved only with start state, I think it makes sense to keep it on transitions from 'popstate' event too. What do you think?

**Comment by troch** [comment]
That would make sense.
