### ISSUE TITLE
A simple example is missing ... and is more than required

### ISSUE THREAD

**Issue by peshoicov** [router5/router5#106]
Although the website has a lot of stuff - a simple example is still missing and it is **a must have** thing.
Nothing fancy, just two pages with link to the other one, and it'll be enough to give idea how to use the router at all.

**I'm not using react or deku.** So - I spent almost half a day at your site and github page, and I still can't figure out how to do a simple routing, even between two simple pages.

Me personally - will search for another solution. So, please add a very simple example, so at least next people who get here understand how to use it.

**Comment by troch** [comment]
There are examples: https://github.com/router5/examples. I'm sorry it doesn't cover more UI libraries for you. Please, go and search for another solution.
