### ISSUE TITLE
How to navigate with query params?

### ISSUE THREAD

**Issue by tesujimath** [router5/router5#107]
Since router.navigate takes a route name and optional route params rather than an actual path, I can't see how to navigate to a path containing query params, e.g. '/my/path?query1=value1'.

Any suggestions?

**Comment by troch** [comment]
Route name / params define a state, your route definition defines where those params go in the URL. So whether those params are search params or not, when you navigate to a new state it will update the URL (see [browser plugin](http://router5.github.io/docs/history.html)). When the URL is changed (popstate event, manually entered), your router state is updated.

**Comment by tesujimath** [comment]
I thought you were saying, just use history pushState() to navigate, but that doesn't work.  Sorry, I'm still not getting it.  When I navigate to a new URL within the application by calling history.pushState(), the URL does change (obviously), but the router doesn't notice that, so the components for the new route don't get rendered.

(It worked when I called router.navigate(), but I couldn't include query parameters in my URLs by doing that.)

Here's how I create the router:

```
import createRouter from 'router5';
import browserPlugin from 'router5/plugins/browser';
import listenersPlugin from 'router5/plugins/listeners';
import loggerPlugin from 'router5/plugins/logger';

const routes = [
  { name: 'root', path: '/' },
  { name: 'login', path: '/login' },
];

const defaultRoute = 'root';

const router = createRouter(routes, { defaultRoute });
router.usePlugin(loggerPlugin);
router.usePlugin(browserPlugin());
router.usePlugin(listenersPlugin());

export default router;

```

What am I not understanding?

**Comment by troch** [comment]
Don't use the history API directly, use `router.navigate` (called with name and parameters). Can you show me how you call `router.navigate`?

**Comment by tesujimath** [comment]
Well, when I use `router.navigate`, all works fine, except I can't put query parameters into the URL:
```
export function openLoginDialog(email) {
  // TODO email, using mjackson's history library:
  //history.push(email ? `/login?email=${email}` : '/login');
  router.navigate('login');
}
```
And when I use the history library directly to navigate to a URL with the query parameter, router5 doesn't notice the URL change, so components don't re-render.

Are we simply missing a version of `router.navigate` which could take query parameters as well as route parameters?

**Comment by troch** [comment]
Query parameters are route parameters: they are part of your routing state. You just need to define your route as follow:

```js
const routes = [
  { name: 'root', path: '/' },
  { name: 'login', path: '/login?email' },
];
```

And then navigate

```js
router.navigate('login', { email })l
```

**Comment by tesujimath** [comment]
Ah! Thanks for the clarification and the prompt responses, and sorry for being a bit slow.

**Comment by andreigabreanu** [comment]
Actually I think this solution is not 100% bullet proof.

Imagine the following situation:

You have the following routes:

/dashboard --> shows latest posts
/posts ---> shows all posts
/posts/5 --> shows a single post

on either of these pages you want to be able to show a modal to DELETE a post (like a confirmation).

This means that we want to do router.navigate([current route name], {}, {modal: "delete-post"}); 
We would then listen globally for the state change and if the query param "modal" is present and it is set to "delete-post" we render the page that was requested + on top of it the Delete Post modal . You define everything only once and you do not have to treat all the possible routes combos to show the delete modal. Seems pretty DRY to me but cannot be achieved with router5 right now AFAIK.

**Comment by troch** [comment]
It depends on how you implement modals but nothing is stopping you to:
- Listen to route changes and dislpay a modal if `modal` is in route params
- Kill existing modal on route change
