### ISSUE TITLE
canDeactivate not working with back button

### ISSUE THREAD

**Issue by tesujimath** [router5/router5#108]
I have a canDeactivate installed on the router, and it works nicely to provide confirmation of leaving the route when navigating using router.navigate(), e.g. when the user clicks on my navigation bar.

However, it does not get called when the user clicks on the browser back button.

Is this an omission?

**Comment by troch** [comment]
It won't get called, unless you set `forceDeactivate: false` in browserPlugin. I've updated the docs as I realised it wasn't documented (http://router5.github.io/docs/history.html).

I don't recommend not forcing deactivation on popstate events: you can't prevent those events, and the history will change anyway, causing synchronisation issues between browser and your application. The browser plugin tries its best to make it work, but it's far far from ideal, and you'll expose yourself to a class of issues.

**Comment by tesujimath** [comment]
I tried it, and saw some of the problems you refer to.  So I decided not to use it after all.  ;-)

Thanks for your help.
