### ISSUE TITLE
Question about transition actions

### ISSUE THREAD

**Issue by tesujimath** [router5/router5#109]
I use [redux-saga](https://redux-saga.github.io/redux-saga/), and find it useful to have a saga which listens for the action `@@router5/TRANSITION_SUCCESS`.

However, I didn't find actions like these documented in the public API of router5.  So my question is, do you regard these actions as part of the API, to support uses such as this?  (And if not, could I request that you do so, because it is useful!)

**Comment by troch** [comment]
Yes, that is true action types are not documented (action creators are). I will add them to the docs.

You can access action types as follow:

```js
import { actionTypes } from 'redux-router5'

const { TRANSITION_SUCCESS } = actionTypes
```

See file: https://github.com/router5/redux-router5/blob/master/modules/lib/actionTypes.js

**Comment by tesujimath** [comment]
Great, thanks!
