### ISSUE TITLE
history issue. Forward button doesn't work

### ISSUE THREAD

**Issue by Crazy-Ivan** [router5/router5#11]
When I navigating from example.com/#/ to example.com/#/mailbox and then click browser back button everything works as expected. Url has changed to example.com/#/ and router noticed it. However from this point I should be able to click forward button and go to example.com/#/mailbox again. Unfortunately i'm not able to do that. Forward button is disabled.

**Comment by troch** [comment]
Thanks for raising this and helping during the grinding teeth phase! :+1:

**Comment by troch** [comment]
v0.2.6 released

**Comment by Crazy-Ivan** [comment]
At your service :+1: . Thanks for such fast answer.
