### ISSUE TITLE
Locking the route until (some) action is taken.

### ISSUE THREAD

**Issue by Sotorin** [router5/router5#110]
How can I stop user from navigating away before filling out a form?

In the examples there is a sample of how not to navigate away before all form fields are cleared, but the problem is that I can explicitly type in another route (like 'inbox') and app navigates away.

What I would like to do is to literally lock the app. Even if I type another route (like 'inbox') router recognizes that user is not supposed to do it and returns back to 'compose' (or does not move). 

I tried stopping the router via router.stop(), but I can still navigate away by typing route in the address bar.

**Comment by troch** [comment]
You can use `canDeactivate` handlers. When using the browser plugin, there is a `forceDeactivate` option which is set to `true` by default. I don't recommend turning it to `false`: history change events are not cancellable, and it will cause synchronisation issues between your application and your history.

**Comment by Sotorin** [comment]
Yes, I saw example of that in the router5 samples that have been provided. Compose component uses `canDeactivate` and things are working as expected, but I can still navigate away by typing the route explicitly. Is there a way to avoid this altogether? 

Just like in this video clip.

[Router5.mp4.zip](https://github.com/router5/router5/files/683748/Router5.mp4.zip)

**Comment by troch** [comment]
Clicking the back button can cause either one of the two:
- A history change without page unload if there is a current history
- A page unload

Page unloads can be prevented synchronously by asking users if they want to leave indeed.
History changes (popstate events) cannot be prevented at all. The browser plugin tries its best to ignore them but ultimately you can face a page unload or a messed history. From my own experience, it is best to persist data rather than preventing a user to navigate away.

**Comment by Sotorin** [comment]
I had another idea. Perhaps instead of tap-dancing around preventing users from navigating away (using the router or other means) it would be better to somehow disable or freeze the app. Users would be able to click on back/forward buttons, type URL explicitly in the address bar, basically navigate the app thru available means but all the functionality would be disabled. For example, they won't be able to click on a link taking them to some other user's profile. Even if they navigate there thru history or some other way, that profile would not have any functionality enabled. The only option would be to complete required action and, thus, re-enabling the application.

**Comment by troch** [comment]
When you enter a new URL in your browser you are causing a full page reload, unless you modify something after the hash.

I'm not sure how you can freeze an app, but not entirely so you can still use the parts which are meant to be used (i.e a form to complete).

**Comment by Sotorin** [comment]
The app has only one entry point on the server (http://host.com/index.html) and everything is rendered by the browser. The app will be eventually connected to either AJAX endpoints or single web socket connection (we are experimenting).

We could try to save the state on the client side (local or session storage) and when user refreshes the page state is reloaded from these sources. However, this can be easily bypassed and is not an ideal solution. We have to save and then read the state from the server (if user tries to refresh the page).

The app is also protected by a login screen and this poses another set of challenges. The app is already started, redux store created but we don't know know how to render it because user is not logged in and we don't know what data to send. So, after successful login, store is hydrated with data coming from the server and app is rendered. Refresh destroys the state and we are back where we started. 

We will have an opportunity to save the state to the server after user enters route which we want frozen. However, if we stop the router and user decides to refresh the page then we will lose state and he/she would be redirected back to the login screen. That would not be optimal user's experience. 

This discussion is now far beyond router5. I'm just sharing some thoughts and try to learn from smarter people :)
