### ISSUE TITLE
Code splitting exmplae

### ISSUE THREAD

**Issue by saniko** [router5/router5#111]
Hi,
Any "code splitting" example with webpack 2 system.import I can learn from?

Best.

**Comment by troch** [comment]
Hi @saniko. Mentioned at the bottom here: http://router5.github.io/docs/async-data.html (not a full-blown example, but it will help giving you the overall idea of how to do it).

I personally still use `require.ensure`.

Note: `System.import` is deprecated in webpack 2 (use `import()` instead). From the `2.1.0-beta.28` release notes:

> add import() as Code Splitting construct. It should be used instead of System.import when possible. System.import will be deprecated in webpack 2 release (removed in webpack 3) as it's behavior is incorrect according to the spec.
