### ISSUE TITLE
Docs: Examples don't work properly

### ISSUE THREAD

**Issue by hinok** [router5/router5#112]
Hey,
I noticed something weird while playing with examples.

**Url**
http://router5.github.io/docs/with-react.html#/inbox

![r2](https://cloud.githubusercontent.com/assets/1313605/22129356/b3f3555a-dea5-11e6-9e7d-c3e20d0e8993.gif)

**Current**
Clicking on a message don't change visible message but url is changed. It works only once for the first click.

**Expected**
Clicking on a message change visible message and url. Url and the state are in sync.

This bug exists in all examples (React, React + Redux, Deku).
If this is a desired behaviour, sorry for the confusion.

**Comment by troch** [comment]
@hinok thanks for reporting, will look into it.

**Comment by troch** [comment]
Fixed (finally took the time)
