### ISSUE TITLE
When Importing I get not a function 

### ISSUE THREAD

**Issue by DavidStrada** [router5/router5#113]
Hi there, I'm having a hard time after upgrading from v.3 to v.4.4.1 I keep getting this error when importing Route5 dependencies.

``` javascript
// Imports
import createRouter from 'router5';
import loggerPlugin from 'router5/plugins/logger';
import listenersPlugin from 'router5/plugins/listeners';
import browserPlugin from 'router5/plugins/browser';

```

``` javascript
// implementation
const routes = [
    { name: 'home',      path: '/'},
    { name: 'section', path: '/:section'},
];

const router = createRouter(routes, {
  defaultRoute: 'home'
})
  .usePlugin(loggerPlugin)
  .usePlugin(browserPlugin({
      useHash: true
  }))
  .usePlugin(listenersPlugin());
```

ERROR: 
`Uncaught (in promise) Error: createRouter is not a function`

**Comment by DavidStrada** [comment]
`createRouter is an obj` so i did `import { createRouter } from 'router5';`  and now i get :

`Uncaught (in promise) Error: factoryFunction.apply is not a function`

**Comment by troch** [comment]
@DavidStrada `createRouter` is available as default and named exports. That's weird it would work as a named export and not as default. Can you make sure what you have in `node_modules` is indeed v4.4.1, and manual delete / re-install if not?

I have not experienced those issues (I always upgrade to the latest patch) and it has not been reported yet.

**Comment by DavidStrada** [comment]
I forgot to mention I'm using `jspm` package manager so it appears `systemjs` is somehow having a problem or not sure ( really ), I'm trying to integrate now using webpack,  given I need to deploy this thing :), Did check you `export.default = ... ` so it's really weird.

Also I notice on your docs there are some places where ( mainly in plugins part ) they are being imported wrongly ( e.g. ) https://github.com/router5/router5#plugins

``` javascript
import browserPlugin from 'router/plugins/browser';
import listenersPlugin from 'router/plugins/listeners';
import persistentParamsPlugin from 'router/plugins/persistentParams';
```

missing `router5`
``` javascript 
import browserPlugin from 'router5/plugins/browser';
import listenersPlugin from 'router5/plugins/listeners';
import persistentParamsPlugin from 'router5/plugins/persistentParams';
```

**Comment by DavidStrada** [comment]
Your package is by far one of the most advanced / best out there in my opinion so thanks for your hard work.

**Comment by troch** [comment]
Thanks for your kind words, and thanks for pointing out issues in the docs (will fix). Do you use babel for transpiling from es2015 to es5? I'm going to look at jspm docs to see if there is anything I need to add in my `package.json` config.

**Comment by DavidStrada** [comment]
`jspm` uses babel transpiler to do es2015 -> es5, 

http://jspm.io/0.17-beta-guide/creating-a-project.html

I created ( 9 months ago ) a package you did include it ( at the time on your docs ) using jspm + jquery to have a "client-site" example https://github.com/DavidStrada/router5-example

**Comment by troch** [comment]
I don't see anything special I would need to configure for an npm package to work with jspm.

In your `jspm.config`, dependencies are locked to older versions https://github.com/DavidStrada/router5-example/blob/master/jspm.config.js#L2-L8 (just making sure you don't re-use that config with router5 >= 4).

If you do the following, what do you get?

```js
import * as router5 from 'router5';
import * as browserPlugin from 'router5/plugins/browser';
import * as listenersPlugin from 'router5/plugins/listeners';
import * as persistentParamsPlugin from 'router5/plugins/persistentParams';

console.log(router5);
console.log(browserPlugin);
console.log(listenersPlugin)
console.log(persistentParamsPlugin);
```
