### ISSUE TITLE
strictQueryParams doesn't seem to be working

### ISSUE THREAD

**Issue by coulson84** [router5/router5#114]
Hopefully this is just caused by my doing something incorrectly but essentially I have code like this to set up the router

`
    const router = createRouter(routes, {
        defaultRoute: 'page404',
        trailingSlash: true,
        strictQueryParams: false
    })
`

so as according to the documentation this means that I should be able to add any query parameters to a url and it should still match as long as the path is correct. However if I run this on the server it will return a route not found error and if I load up the root of the app and then in the console run

`router.matchPath('/?s=3')`

it will return null.

If this isn't a bug then any guidance on what I am doing wrong would be great.

Thanks
Joe

**Comment by troch** [comment]
Hi Joe,

Can you show me your routes?
Also are you on the latest version (4.4.1)?

**Comment by coulson84** [comment]
Sure, these are my routes

`[{
    name: 'root',
    path: '/',
    title: 'Home Page'
}, {
    name: 'home',
    path: '/home',
    title: 'Home Page'
}, {
    name: 'gallery',
    path: '/gallery',
    title: 'Gallery'
}, {
    name: 'gallery.galleryName',
    path: '/:galleryName/?:display',
    titlePrefix: 'Gallery - ',
    titlePath: ['params', 'gallery']
}, {
    name: 'packages',
    path: '/packages',
    title: 'Available Packages'
}, {
    name: 'packages.info',
    path: '/:package',
    titlePrefix: 'Package - ',
    titlePath: ['params', 'package']
}, {
    name: 'about',
    path: '/about',
    title: 'About Me'
}, {
    name: 'blog',
    path: '/blog?:date&:offset&:limit',
    title: 'Blog Index'
},  {
    name: 'blog.year',
    path: '/:year?:date',
    titlePrefix: 'Blogs From ',
    titlePath: ['params', 'year']
}, {
    name: 'blog.year.month',
    path: '/:month?:date',
    titlePrefix: 'Blogs From ',
    titlePath: ['params', 'month']
}, {
    name: 'blog.year.month.title',
    path: '/:title',
    titlePath: ['params', 'title']
}, {
    name: 'contact',
    path: '/contact',
    title: 'Get in Touch'
}]`

You can probably ignore the title stuff. That is just related to some middleware I am using to create titles for pages. Also I have put a workaround in for this for now by adding the query parameters that may be present (just google adwords query string parameters - not present in the above routes) to the root route but would be good to know that if anything changes or people click through to the site from somewhere else which appends their own query string parameters that they won't get a 404 response.

**Comment by troch** [comment]
Thanks. Will look into and come back to you.

**Comment by troch** [comment]
Sorry for the delay checking over your issue. It works all fine for me with your routes. `matchPath('/?s=3')` returns:

```js
{ name: 'root',
  params: { s: '3' },
  path: '/?s=3',
  meta: { params: { root: {} }, id: 1 } }
}
```

Are you sure to be on the latest version?

**Comment by acolby** [comment]
@troch Love the project! 

However I'm running into this problem too.  Any help would be hugely appreciated

```
var router5 = require('router5');

var routes = [
  { name: 'root', path: '/', title: 'Home Page' },
  { name: 'home', path: '/home', title: 'Home Page' }
]

var router = router5.createRouter(routes, { defaultRoute: 'page404', trailingSlash: true, strictQueryParams: false });

console.log(router.matchPath('/'));
console.log(router.matchPath('/?s=3'));

```

**Comment by ibc** [comment]
Routes:

```js
{
  name : 'company',
  path   : '/:company'
}
```

Settings:

```
trailingSlash     : true,
useTrailingSlash  : true,
strictQueryParams : false
```

```js
router.matchPath('/google')
// => matches company

router.matchPath('/google?foo=bar')
// => matches company

router.matchPath('/google/')
// => matches company

router.matchPath('/google/?foo=bar')
// => null
```

100% related to #248. There is a bug in the URL parsing.

But, this is much worse since when the initial URL opened in the browser already contains a `?foo=bar` query parameter, the router does not match the "company" route at all, no matter it's `/google?foo=bar` or `/google/?foo=bar`. This is with `useHash: false`. When `true` it behaves differently (not 100% ok anyway): https://github.com/router5/router5/issues/248#issuecomment-364599357

**Comment by ibc** [comment]
Sorry for mixing info in two issues at the same time. I confirm this bug exists, but just when the URL is the original one used to open the browser: https://github.com/router5/router5/issues/248#issuecomment-364604045
