### ISSUE TITLE
onRouteEnter for single route

### ISSUE THREAD

**Issue by kresli** [router5/router5#116]
I'm struggling to find out how can I call method on routeEnter/routeLeave. So far I found I need to write middleware for whole router, but this doesn't feel right. Maybe I'm missing something?

**Comment by troch** [comment]
What is your use case for `onRouteEnter` / `onRouteLeave`?

**Comment by kresli** [comment]
Thanks for quick respond.
onEnter should set a value in global object maybe dynamically load a component. I'm using mobx as store manager for react which will be used by rourter5 in `onEnter` callback.

**Comment by troch** [comment]
You can use the `onTransitionSuccess` handler available on plugins. Here is a plugin example with redux: https://github.com/router5/redux-router5/blob/master/modules/lib/reduxPlugin.js. If you are trying to share router5 state with mobx, I imagine it will be pretty similar.

**Comment by kresli** [comment]
nice! thank you very much!
