### ISSUE TITLE
Mobx Plugin

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#117]
Hello,
wonderful router and ecosystem! 👍 
I'm wondering if a mobx plugin was in plan.

If not I'm sure it would be quite similar to the redux one. 
I can try to develop it, however I have no previous experience with redux so the example plugin will help me just a bit. Could you give me a some tip on what should be done to port the redux plugin for mobx?  Thanks

**Comment by troch** [comment]
Hi,

I don't use Mobx, and to avoid having to maintain too many packages I don't plan in adding a mobx integration myself. However I would love to see integrations with it (and also bindings for Vue.js), and I'd be happy to help.

Redux and mobx are similar in the way they are both state containers, and they both take actions in and emit state changes. So from the redux integration what is to take away is:
- You need a plugin to share your routing state with your mobx state container. You can start very basic by only sharing the current route (using `onTransitionSuccess`). And then later you can add the transitioning route, transition errors, etc...
- You need a class / mobx data structure to persist state and have observables available

**Comment by LeonardoGentile** [comment]
FIY: I've released mobx and react (with mobx) integrations, feedbacks would be appreciated:
 - https://github.com/LeonardoGentile/mobx-router5
 - https://github.com/LeonardoGentile/react-mobx-router5

They are available also on npm: 
- https://www.npmjs.com/package/mobx-router5
- https://www.npmjs.com/package/react-mobx-router5

**Comment by troch** [comment]
@LeonardoGentile will look at it at some point (currently moving house, I don't have much time and no internet :cry:)

**Comment by troch** [comment]
@LeonardoGentile it looks good, always a cleaner implementation with push APIs (observables) rather than pull APIs. Have you add much feedback from MobX users?
