### ISSUE TITLE
Manually changing the url reloads the entire html page

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#118]
If I am on a route, for example `/home` and I manually go to the url box and hit enter then the entire html page will reloaded. I don't think this is the intended behaviour, how can I avoid it?

I'm using hash `useHash: true` on `Chrome 56.0.2924.87 (64-bit)`  and : 
```
"react-router5": "^4.0.1",
"router5": "^4.5.1"
```

**Comment by troch** [comment]
Seems to be a chrome / opera only behaviour (not in Firefox), and only if the URL is modified. I wonder if it is intended.

**Comment by LeonardoGentile** [comment]
@troch yes it's true it doesn't happen in Firefox.
However I could verify this behaviour also happen on Safari 10.0.2 (OSX).
For both Chrome and Safari this happens ONLY if the original url is not modified, meaning I am for example on `/#/home` and if I just press enter in the url bar (without modifying the url) the whole page is reloaded.   
This does NOT happen when I modify the url to point to another route and hit enter.

**Comment by troch** [comment]
It looks to me like a browser feature more than anything else: if you press enter without modifying the URL, it considers your intention is to reload.

**Comment by LeonardoGentile** [comment]
Alright, as long as it doesn't happen when manually changing the url to another route I think this shouldn't be a big issue. 

Thanks 👍
