### ISSUE TITLE
canActivateDeactivate

### ISSUE THREAD

**Issue by jamalsoueidan** [router5/router5#119]
Hello,

I'm using router5 in my webapplication, and I need to use couple of data before the application renders, but im not sure if im using this correct, because I need to dispatch actions to load data.

´
router.canActivate('application',... {
  let unsc = store.subscribe(... {
     if(dataloaded) {...
       unsc();
       done();
     }
  }
   window.store.dispatch(...action
}

It doesn't feel like a good solution for me, because i always need to subscribe and unsub in my canActivate functions?

Do you have example on how to be able to do this more cleaner?

Thank you

**Comment by troch** [comment]
http://router5.github.io/docs/async-data.html

Use a middleware, not `canActivate` and `canDeactivate`.

**Comment by jamalsoueidan** [comment]
troch, I tried.. 

fetch('/users').then(data => dispatch(loadUsers(data.users)))

where does fetch method come from?

**Comment by troch** [comment]
fetch is a promise-based xhr client: https://developer.mozilla.org/en/docs/Web/API/Fetch_API, I used it in  my examples to have an example without external dependencies. I personally use https://github.com/mzabriskie/axios, and have an `api` object in my router dependencies which is a collection of functions (`api.Users.get()`, etc...).

**Comment by jamalsoueidan** [comment]
I'm using https://www.npmjs.com/package/redux-api-middleware in my actions to handle async api call.

const load = (user_id) => ({
  [CALL_API]: {
    endpoint: '...',
    method: 'GET',
    types: ['REQUEST', 'SUCCESS', 'FAILURE']
  }
})

so in my case I will only dispatch a action?

{
  name: 'application',
  path: '/application',
  onActivate: (params) => {
    let user = store.getState().user
    store.dispatch(load(user.id))
  }
},

but I'm trying to figure get my head around this, but cant be able to know where to put things.

my solution is like this at the moment, but I dont like to use native store methods.

const canActivate = (router) => (toState, fromState, done) => {
    let user = store.getState().user
    let unsub = store.subscribe(() => {
      if(store.getState().navigation) { // initial data is false
        unsub();
        done();
      }
    }
    store.dispatch(load(user.id))
}

router.canActivate('application', canActivate);

**Comment by troch** [comment]
Use `js` for proper syntax highlighting
```
```js
```

**Comment by troch** [comment]
`canActivate` is not meant for loading data, just for checking you can activate a route. For instance, if you have a nested route called `admin.users`, and you start loading data in `canActivate` method of `admin` route,  but are not allowed to access `admin.users`, then your data loading was wasted.

`canActivate` and middleware functions work the same way and middleware are intended for stuff like data loading.

Note: `onActivate` is not handled by default, you need to create a middleware reading your routes config and then executing `onActivate` handlers.

**Comment by jamalsoueidan** [comment]
but onActivate on the routes config, is not the same as 

router.onActivate('application'...

**Comment by troch** [comment]
There isn't an `onActivate` method on the router itself.

**Comment by jamalsoueidan** [comment]
Okay sorry I meant to write canActivate,

Anyway my friend.

1. I add store as dependency to router.
router.setDependency('store', store);

2. Add onActivate 
{
  name: 'application',
  path: '/application',
  onActivate: (params) => {
    // I need store to dispatch an action
    let user = store.getState().user
    store.dispatch(load(user.id))
  }
},

3. I add middleware to my router.

```js
const activate = (routes) => (router, dependencies) => (toState, fromState, done) => {
    let store = dependencies.store
    // check if ('application') is going to be activated next? somehow
    if ( 'application' is onActive ) {
         if (!store.getState().navigation) { // what if the api request is not done yet?
             done()
         }
    }
};

router.useMiddleware(activate);
```

I could remove (2) and just go with middleware, but then every time route change I need to check if 'application' is activated after 'login'.

**Comment by troch** [comment]
```js
router.useMiddleware(activate);
```

should be 

```js
router.useMiddleware(activate(routes));
```

You can use both `canActivate` and `middleware`: check if you can access the route, then load the data for the route, once you know it can be activated.

**Comment by jamalsoueidan** [comment]
once I know it can be activated? the data can only be loaded if the user is loggedin! 

If this the way middleware will run?

- deActivate('login')
- middleware //  LOAD DATA
- canActivate('application') // check user is logged in?

I'm confused :)

**Comment by troch** [comment]
middleware functions run after a transition can be done (after canDeactivate and canActivate handlers have validated the transition, if you have such handlers configured).

**Comment by jamalsoueidan** [comment]
This did the job 👍 

Thank you :) 

```js
const dispatch = (state, action) => {
  return new Promise((resolve, reject) => {
    if(store.getState()[state]) {
      resolve();
      return;
    }

    const unsubscribe = store.subscribe(() => {
      if(store.getState()[state]) {
        unsubscribe();
        resolve();
      }
    })

    store.dispatch(action)
  })
}

const routes = [
  { name: 'application', path: '/', onEnter: (router, store) => dispatch('user', {type: 'add', text: 'jamal'})},
  { name: 'application.id', path: '12' }
];

const router = createRouter(routes, {
  defaultRoute: 'application.id'
})
.usePlugin(browserPlugin({useHash: true}))
.usePlugin(listenersPlugin())
.setDependencies({ store });

const findRouteByName = (routes, routeName) => {
  return routes.find(route => route.name === routeName)
}

const customMiddleware = (routes) => (router, dependencies) => (toState, fromState, next) => {
  const { toActivate } = transitionPath(toState, fromState)
  const onEnterPromises = toActivate.map(routeName => findRouteByName(routes, routeName))
                         .filter(route => typeof route.onEnter === "function")
                         .map(route => route.onEnter(router, dependencies.store))

  return Promise.all(onEnterPromises)
};

router.useMiddleware(customMiddleware(routes));
```
