### ISSUE TITLE
Using router5 isomorphically / universally

### ISSUE THREAD

**Issue by ArnoBuschmann** [router5/router5#12]
Is it possible to use router5 isomorphically/universally? When using it server side I run into problems as there is no window object defined, error:

```code
/project-path/node_modules/router5/dist/commonjs/router5.js:70
            this.base = this.options.base || window.location.pathname.replace(
                                             ^
ReferenceError: window is not defined
```

**Comment by troch** [comment]
It is not yet possible but it is something I want to enable. For removing the error you see this won't be difficult, and I need to grab the server URL in the start function. I am inexperienced with universal JavaScript, so I need to do a bit of research.

**Comment by ArnoBuschmann** [comment]
Using Express.js server side, the request object is good for getting the URL: http://expressjs.com/4x/api.html#req.originalUrl

That is how it is handled right now without router5.

**Comment by troch** [comment]
Would you expect to use the exact same code client and server side? My initial thought was to allow to pass an URL to `.start()` so the router can match what is being passed rather than accessing the global location object, but that is a difference of code between client and server. Or would you try to access a global or context variable?

**Comment by ArnoBuschmann** [comment]
ATM I'm using @staltz solution for isomorphism in Cyclejs, where he grabs the URL server side via req.url and attaches it for the client as context: https://github.com/cyclejs/cycle-dom/blob/master/examples/isomorphic/server.js#L18

Then there is ongoing context client side: https://github.com/cyclejs/cycle-dom/blob/master/examples/isomorphic/app.js#L38-46

Thereafter the ongoing context, combined with a switch statement is used to select functions to render the page: https://github.com/cyclejs/cycle-dom/blob/master/examples/isomorphic/app.js#L48-58

**Comment by troch** [comment]
I think I now have a fairly good idea of what I need to do to allow universal javascript apps to use router5, and it is less than initially thought. It should be done in a few days time.

**Comment by ArnoBuschmann** [comment]
Sounds good :+1:

**Comment by troch** [comment]
How to use:

__Create your router (client & server)__

```javascript
let router = new Router5()
    .addNode('home', '/home')
    .addNode('about', '/about')
    .addNode('contact', '/contact');
```

__On the server__
```javascript
// With express, you would pass req.originalUrl
router.start(serverUrl, function (err, state) {
    // Serialise state and send it in a "<script></script>" tag
    // so it can be retrieved on the client side
    // ex: <script>window.initialState = JSON.stringify(state)</script>
});
```

__On the client side__
```javascript
// Read starting state
let startState = window.initialState;
// Tell the router the application is already initialised with startState so
// it won't try to transition to the current URL or default route.
router.start(startState, function (err, state) {
    // ...
});
```

**Comment by troch** [comment]
v0.3.1 released

**Comment by ArnoBuschmann** [comment]
Works well :) But one question, when having
```javascript
req.originalUrl -> /home
```
server side and the route name is simply "home" while there's a listener
```javascript
router.addRouteListener('home', function (toState, fromState) {
      // render view
  });
```
wouldn't it make sense, a listener could also listen to the URL fragment /home to make it compatible with req.originalURL?
