### ISSUE TITLE
get routes through router?

### ISSUE THREAD

**Issue by jamalsoueidan** [router5/router5#120]
Hi Troch,

I'm trying to get my custom defined attributes *component* in routes object, through router.rootNode, but can't figure it out.

```js
const routes = [
  { name: 'application', path: '/'},
  { name: 'application.barchart', path: '/barchart', component: BarchartExample }
];

console.log(router.rootNode.children[0].children[0])
RouteNode {name: "application.barchart", absolute: false, path: "/barchart", parser: Path, children: Array[1]…}
```

Can you help? :)

**Comment by troch** [comment]
The router (and its route nodes) don't keep custom data. Route node only consume `name` and `path`, the router consumes `canActivate` and `canDeactivate`.

**Comment by jamalsoueidan** [comment]
Okay thank you! :)
