### ISSUE TITLE
OnStart is called before the state is set

### ISSUE THREAD

**Issue by pristas-peter** [router5/router5#121]
When passing state object to router.start the state isnt set in onStart callback in plugin when calling getState. We want to use it for obtaining data from ssr.

**Comment by troch** [comment]
`onStart` doesn't have arguments, like specified here: http://router5.github.io/docs/plugins.html (please let me know if you've seen a wrong documentation about `onStart`). It is called when `router.start()` is called, before any transition starts.

`router.start()` takes a callback where you can trigger data loading from. Or you can use middlewares which are better suited than plugins for loading data, especially for SSR.

**Comment by pristas-peter** [comment]
I agree, but middleware is not triggered when passing state into start(). 

So only one solution comes to my mind: to monkey patch start method of router from middleware to get state from that callback, but I wanted to avoid this. I don't want to refresh state from client side code when starting router, I think this should be handled in plugin or middleware.

**Comment by troch** [comment]
>  I agree, but middleware is not triggered when passing state into start().

for SSR? If you already know your start state, then you might not need a plugin or middleware at all?

Another option is to use a plugin like this:

```js
const myPlugin = () => {
    const isFirstTransition = true;

    return {
        onTransitionStart() {
            if (isFirstTransition) {
                isFirstTransition = false;
                /* ... */
            }
        }
    };
};
```

**Comment by pristas-peter** [comment]
We are using classes based on mobx which need to be deserialized from state object before first render according to current route. The methods which implement this are stored in routes segment object like method onActivate in your data async guide example. So therefore we need to do this either on transition (which is not called when state is provided on start) or some other manner, but somehow we need to get to the current state to know which deserialize methods to call. 

I managed to get this working by not using state object on the start of client, so the first transition will happen. 

Thanks for your time, you can close this issue. Finally I can delete react-router from my codebase, which caused me many headaches :)

**Comment by troch** [comment]
> I managed to get this working by not using state object on the start of client, so the first transition will happen.

Sounds sensible. :+1:
