### ISSUE TITLE
Dynamic persistent parameters

### ISSUE THREAD

**Issue by sotojuan** [router5/router5#122]
I have a query parameter of the form `${user.id}_open_tab` that tells you the tab open in `user`'s workspace. I'd like to keep this namespace since I have multiple users open at once. However, I can't add this to `persistentParamsPlugin` because it's dynamic. I need to be persistent.

For example, a route would be `mysite.com/hello?123_open_tab=activity&124_open_tab=orders`.

What's a good solution? I don't mind locally patching the plugin since it's short.

**Comment by troch** [comment]
> What's a good solution? I don't mind locally patching the plugin since it's short.

I would do a plugin similar to the persistent param plugin, with your custom logic in it, saving any parameter matching xxx_open_tab. You might have to call `router.setRootPath` all the time you add a new param, and  have strict query parameters turned off.
