### ISSUE TITLE
Middleware fires twice while redirecting from defaultRoute

### ISSUE THREAD

**Issue by wasd171** [router5/router5#125]
Hi!

Let's consider this situation: there are 2 routes: `A` and `B`. `B` is stated as default route. `B` has a `canActivate` condition with redirect to `A`. And there is a middleware, firing on every route change, let's say it's logging `toState` to console.

So what happens when router starts, but `B` cannot be activated? It redirects to `A`. I would expect middleware to fire only once, with `toState` equal the state of `A` route. But that's not the case. First, it is fired with `A` state. But right after that it is fired with `B` state, although transition to `B` was not succesful. Both times it fires with `fromState` = `null`.

First it fires with `toState.meta.id` = 2, then with `toState.meta.id` = 1, so I keep the previous value and compare new id with it, as a workaround, but it looks like a bug for me. Documentation [states](http://router5.github.io/docs/middleware.html) that 

> Multiple middleware functions can be registered with a router instance. **They are invoked in series after the router has made sure active route segments can be deactivated and future active route segments can be activated**. Middleware functions are for example a great way to load data for your routes.

**Comment by troch** [comment]
Hi @wasd171,

Being called twice doesn't sound right for a middleware if the first transition is blocked by `canActivate`. Firing with `fromState = null` is normal. I'll try to re-create and come back to you.

**Comment by troch** [comment]
Closing (a year old)
