### ISSUE TITLE
Changing hash by hand in IE11 does not work

### ISSUE THREAD

**Issue by pbenes** [router5/router5#126]
Hi,
running the example in IE11 http://router5.github.io/docs/with-react.html#/contacts does not work when changing hash by hand (e.g.  http://router5.github.io/docs/with-react.html#/contacts -> http://router5.github.io/docs/with-react.html#/compose)

This is due to IE11 not triggering popstate event on hash change https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/ (fixed in edge)

**Comment by troch** [comment]
Not entirely sure what the workaround would be. Any idea?

**Comment by pbenes** [comment]
I think it's necessary to have something similar to what for example react-router has in their history library (their IE11 fix: https://github.com/ReactTraining/history/pull/336/files, see https://github.com/ReactTraining/react-router/blob/d601722f8515eea3910bb3a69313f3f2fc37df16/packages/react-router-redux/modules/ConnectedRouter.js#L29, https://reacttraining.com/react-router/web/api/Router/history-object for reference)

**Comment by troch** [comment]
@pbenes I've not been able to fully finish it, hopefully soon!

**Comment by shivani137** [comment]
any updates on this?

**Comment by troch** [comment]
@shivani137 not yet. I had started the work and changed laptop which meant I didn't have any VM with IE11 set-up and I never went back to it. Poor excuse, but if anyone wants to do the work, they will be more than welcome.

**Comment by troch** [comment]
Fixed in v6
