### ISSUE TITLE
API to retrieve the routes config object

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#127]
Hello,
I'm not sure if this available or not, I couldn't find many infos.

This is my idea: in the routes config object we usually stores some extra data, like functions to be called by middleware, ectr.

When creating the router and passing the routes config object to it, it would be useful if the original routes config would be stored somewhere into the router instance. Doing so we could retrieve it and all the related _extra_ field we added. 

Or another idea would be, when handling the route states to embed automatically those extra field into the states.

The tricky part maybe would be to handle the 2 different config structure (with and without `children`).

Basically it should be possible to do something like this:

```
const  routes= [
  { name: 'home', path: '/', component: Home, info:'super'},
  { name: 'login', path: '/login', component: Login, info: 'nah!!'},
  { name: 'section', path: '/section', component: Sections, children: [
    // Sections
    { name: 'subsection', path: '/subsection', component: Subsections, children: [
      // Subsections
      { name: 'down', path: '/down', component: Down, info: 'red' },
    ]}
  ]}
];

const router = createRouter(routes, routerOptions)

const myRouteConfig = routerInstance.getRouteConfig('section.subsection.down')`
console.log(myRouteConfig.info) // ---> 'red'

```
Or while using middleware or other functions handling the state transitions:

```
// When toState is `section.subsection.down`
(toState, fromState) => {
 console.log(toState.info); // ---> `red`
}
```
Is it feasible?  
Would it make sense?

**Comment by troch** [comment]
Hi Leonardo,

Currently, the router doesn't store any route information at all. The only thing stored is `rootNode` which is the tree of routes created with `route-node` package. This package only cares about `name` and `path`. I'm not sure about how I feel about router5 keeping hold of that information, it feels to me like it is not the responsibility of the router. Holding onto component references can also make hot reloading harder depending on how you perform it.

What you can achieve though: with a middleware, you can alter the state.

```js
const myStateEnhancer = (router) =>
    (toState, fromState, done) =>
        done(null, { ...toState, myProp: 'hello' });
```

**Comment by LeonardoGentile** [comment]
Hello Thomas,
thanks for your answer, so in theory with a middleware I could inject stuff into the state coming from the route configuration array? 

I know you don't like storing component reference into the routes config but it's been working for me, to be honest I haven't tried with hot reloading, but that has never worked for me anyway so I gave it up a while ago 😄 

When terminating my plugin I'll show you how I'm using this configuration, then maybe we could find a solution to make it work with hot reloading if you know it better?

**Comment by troch** [comment]
> thanks for your answer, so in theory with a middleware I could inject stuff into the state coming from the route configuration array?

Yes you can.

```js
const myStateEnhancer = (router) =>
    (toState, fromState, done) =>
        done(null, { ...toState, myProp: 'hello' });
```

If you have your routes array available, you can import it to use in a middleware. You can use dependency injection to make it more testable.

```js
router.setDependency('routes', routes);
```

```js
// If you use destructuring, make sure you register
// your dependency before your middleware
const myStateEnhancer = (router, { routes }) =>
    (toState, fromState, done) =>
        done(null, { ...toState, myProp: findSomethingFromRoutes(routes) });
```
