### ISSUE TITLE
[question] Translated Routes

### ISSUE THREAD

**Issue by tomzmtl** [router5/router5#128]
Is there a preferred way to handle translated routes?

For instance:
```
/en/about-us
/fr/a-propos
```

Both routes would of course connect to the same component.

I managed to handle the root language param like so:
```
export default [
  {
    name: 'root',
    path: '/:lang',
  },
  {
    name: 'root.about',
    path: '/about-us',
  },
];
```

This is working fine. Now I'd like to be able to define specific paths for the languages I'd like to support.

The way I see it, I'll probably do something to that effect:

1. Add individual routes for each route I want to handle:
```
{
  name: 'root.about-en',
  path: '/about-us',
},
{
  name: 'root.about-fr',
  path: '/a-propos',
},
```

2. I'm using a simple `switch` statement to decide which main component I should render based on the current route, so I'd add my new route names in there:

```js
const renderElements = (route) => {
  switch (route.name) {
    case 'root.about-en':
    case 'root.about-fr':
      return <About />;
    default:
      return <NotFound />;
  }
};

const App = ({ route }) => (
  <div className="main">
    {renderElements(route)}
  </div>
  );

export default connect(() => routeNodeSelector('root'))(App);
```

This should work, but I'm not convinced this is really viable as the application scales.
I'd rather have a way to map multiple paths to the same route and have a function decide which path is the right one based on current language.

I'm really new to this library so maybe middlewares could play a role here but I haven't seen anything in the documentation/issues addressing this particular use-case.

Thank you.

**Comment by troch** [comment]
Hi,

The way I do it myself: depending on the current language, I create the router with different routes. They are downsides to this approach, and it depends how it lives in production and on your general use case.

The other approach you can take, is to not have the language as a parameter.

```js
const routes = [
  {
    name: 'en',
    path: '/en'
  },
  {
    name: 'fr',
    path: '/fr'
  },
  {
    name: 'en.about',
    path: '/about-us',
  },
  {
    name: 'fr.about',
    path: '/a-propos',
  }
];
```

You can easily create an util to build your routes and make it less verbose.
For mapping a route name to a component, you then need to check a route name contains `'about'`. I have an utility package which can help you: https://github.com/router5/helpers.

I have another idea: allowing paths to be defined as functions of parent params. Something looking like:

```js
const allowedLanguages = [ 'fr', 'en' ];

const paths = {
  about: {
    en: '/about-us',
    fr: '/a-propos'
  }
};

const routes = [
  {
    name: 'root',
    path: '/:lang',
    canActivate: (toState) => allowedLanguages.includes(toState.params.lang)
  },
  {
    name: 'root.about',
    path: ({ lang }) => paths.about[lang]
  }
];
```

**Comment by tomzmtl** [comment]
Thanks for replying!

Your second example is interesting, is this syntax currently supported? It would make the more sense in my situation, and have some other interesting applications.

Another thing I thought about was a way to dynamically update the router with a new set of routes at runtime.
Because your first example is kinda limited if you need to be able to change the language without a reload.

**Comment by troch** [comment]
That syntax is not supported, and I'll have to look at how feasible it is.

> Another thing I thought about was a way to dynamically update the router with a new set of routes at runtime. Because your first example is kinda limited if you need to be able to change the language without a reload

It's another approach, but I think you'll face similar issues.

**Comment by tomzmtl** [comment]
Ok thanks. Based on this discussion I'll go with creating the router with different routes then.
Express already handles unsupported languages, and it is acceptable in my case to do a simple reload when changing languages.

I'd be interested to see what comes up on this front in the future though.
I'm pretty sure I'll eventually end up with requirement for more dynamic route handling.

Thanks for your thoughts 👍
