### ISSUE TITLE
Inconsistency between documentation and example

### ISSUE THREAD

**Issue by satazor** [router5/router5#134]
http://router5.github.io/docs/async-data.html

> You shouldn't mutate toState if you don't explicitly ask the router to wait by either calling a done callback or by returning a promise.

but in the example you are returning a promise and NOT mutating the toState:

```js
const dataMiddlewareFactory = (routes) => (router) => (toState, fromState) => {
    const { toActivate } = transitionPath(toState, fromState);
    const onActivateHandlers =
        toActivate
            .map(segment => routes.find(r => r.name === segment).onActivate)
            .filter(Boolean)

    return Promise
        .all(onActivateHandlers)
        .then(data => {
            const routeData = data.reduce((accData, rData) => Object.assign(accData, rData), {});
            return { ...toState, data: routeData };
        });
};
```

Shouldn't the example actually mutate toState because it's returning a promise?

**Comment by troch** [comment]
I think the phrasing is confusing. It should be:
- if you want to add information to the state object, then you need to use the done callback or return a promise with the augmented state
- you should not attempt to change `meta`, `name` and `path` properties
- whether you use an immutable style doesn't matter (I think)

I'll update the docs to make it more clear. Thanks for pointing it out.
