### ISSUE TITLE
Change strictQueryParams default to false?

### ISSUE THREAD

**Issue by Keats** [router5/router5#137]
The vast majority of the time, you want to match routes on their path, whether they have query params or not. I would think the number of people wanting strict matching on query params to be very small.

This non-intuitive default means that by default `/` and `/?ga_id=some-analytics-stuff` (for example) will not match, leading to hard to diagnose issues.

Now I could be completly off-base and the majority of people actually wants strict query parameters but I can't even think of a case where I would want that.

If changing it is not possible, I suggest moving the "Strict query parameters" paragraph from http://router5.github.io/docs/router-options.html to the top of the page, doubling its font-size and putting a 10px red border to make sure it is visible.

**Comment by troch** [comment]
Good suggestion for the docs. That's also fair to say `strictQueryParans` could be false by defaul`, but that will be a breaking change and need a major version bump.

I also need to document a trick you can use: the router has a `setRootNodePath` function you can use for "global" query params.

```js
// List query params you expect to be used
router.setRootNodePath('?ga_id');
```

**Comment by Keats** [comment]
I agree that it would be a breaking change. I personally think it would be worth the new version but otherwise it can be scheduled in the next version when there are more breaking changes

**Comment by troch** [comment]
I'm going to start working on a couple of new features which will create breaking changes on `route-node` (dependency) so it will be a good opportunity to introduce that change.

**Comment by troch** [comment]
Default changed with v5
