### ISSUE TITLE
Allow middleware to alter navigation url param based off api response

### ISSUE THREAD

**Issue by morenoh149** [router5/router5#138]
I'm trying to write a middleware that figures out a url param if it's not provided.

If url param `foo=1` is in the url, then navigate to `/route?foo=1`.
Else, extract foo after an api call and navigate to `/route?foo=apiValue`.

Is this possible? I have specified an empty value in navigate
`router.navigate('some.route', { foo: ''})`
then in my middleware
```
// middleware
fetch('api.com', (res) => {
  const params = {}
  if (toRoute.params.foo) {
    params.foo = foo
  } else {
    params.foo = res.foo
  }
  done(params)
}
```
the UI seems to respect the new param but if I transition twice the value reverts to the empty string (`''`).
The transition message in my reducer is claiming that foo is `''` even though I'm setting that param value in the middleware.

**Comment by troch** [comment]
I wouldn't expect a middleware to work properly. I plan to support default params in a near future, but the best way to go about it currently is to monkey-patch `navigate`. Something like that:

```js
const routes = [
    { name: 'foo'', path: /foo/:id', defaultParams: { id: '1' } }
];
const navigate = router.navigate;

router.navigate = (name, params, ...args) => {
    const route = routes.find(_ => _.name === name);
    if (route) {
        return navigate(name, { ...route.defaultParams, ...params }, ...args);
    }

    return navigate(name, params,, ...args);
};

**Comment by morenoh149** [comment]
After thinking on it I thought you would suggest that determining the route to transition to should be the callee's responsibility. It's just that it would be nice to have middleware be able to change the destination.
