### ISSUE TITLE
Question: route intercept gotchas?

### ISSUE THREAD

**Issue by axefrog** [router5/router5#14]
I'm having a heck of a time trying to get my routes intercepted by router5. The arguments I'm using initially can be seen in this snippet of my app's configuration code:

```js
router: {
  routes: [
    { name: 'home', path: '/', 'children': [
      { name: 'search', path: '/search' },
      { name: 'new-resource', path: '/new-resource' },
      { name: 'my-data', path: '/my-data' },
      { name: 'browse', path: '/browse' }
    ]}
  ],
  options: {
    defaultRoute: 'home',
    base: 'http://localhost:50431'
  }
}
```

I have a link on my page that is `href="/new-resource"`, and when I click it, it tries to natively navigate to that page, as though router5 isn't active. No listener fires at all. I've tried both `addListener(callback)` and `addNodeListener('home', callback)`, and they only fire for the default route that fires on startup.

* I've called router.start().
* I've tried it with and without a `base` option.
* I've confirmed that it navigates to my default route on startup.
* I've checked "preserve log" in Chrome's dev tools, to ensure my various log messages and errors are preserved if I leave the page (to avoid last-millisecond errors and messages getting wiped away) - I can see no evidence that the router is doing anything when I click the link.

Nothing. No matter what I do, it won't intercept my link clicks. It's entirely possible I'm making a huge incorrect assumption about what this router is supposed to do. If that is the case, how does one prevent native navigation from occurring?

**Edit:** for the record, the link in question is dynamically generated via Cycle.js, though I'm assuming navigation interception would be a window-level event handler.

**Comment by troch** [comment]
Hi @axefrog,

For your links, you need to prevent their default behaviour and interact with the router directly.

Ideally, you would have a component which takes a few properties: route name, route params, route options and label and it would render a link:
- It builds href for you (that's the whole point of having named routes, it increases maintainability)
- on click, it prevents default behaviour (`event.preventDefault()`) and invokes `router.navigate(routeName, routeParams, options)` so it can push to window.history with new state and new URL.

That is how router works: it replaces links default behaviour. Setting the href property has no impact on routing, but it enables middle click, link sharing, etc...

**Comment by axefrog** [comment]
Ah. I was using visionmedia's page.js previously and it automatically handles intercepting of links clicked, so I was in that mindset. I guess it's a tradeoff, and that router5 is a slightly more manual approach.

**Comment by troch** [comment]
Yes, page.js intercepts click on links. I prefer not to do that so links can be application-specific and include custom logic.

here is an example of a link component with React:
https://github.com/router5/router5-react/blob/master/modules/link-factory.js

**Comment by axefrog** [comment]
No worries, thanks for the help.
