### ISSUE TITLE
Do not owerwrite history state

### ISSUE THREAD

**Issue by iotch** [router5/router5#141]
Hello. Currently the browser plugin is overwriting the entire history state with the router state. Is it a better idea to have a namespaced entry in the global history state to not overwrite any third-party history state data? Thanks!

**Comment by troch** [comment]
Hi!

> a namespaced entry in the global history state to not overwrite any third-party history state data

Do you mean if any 3rd party mutates the current state, you would router5 to somehow keep that state? Can you give me an example on why you would need it?

**Comment by iotch** [comment]
For example, if some component that renders modal windows needs to react on popstate event and close the modal on browser back button.

**Comment by troch** [comment]
So when you open a modal, you add a push state, if you then click the back button, you want the router to ignore the popstate event?

**Comment by iotch** [comment]
I think the plugin should keep the data stored by others in the history state. 

Something like: 

````js
function updateBrowserState(state, url, replace) {
    state = Object.assign({}, browser.getState(), state);
    if (replace) browser.replaceState(state, '', url);
    else browser.pushState(state, '', url);
}
````
https://github.com/router5/router5/blob/master/modules/plugins/browser/index.js#L42
