### ISSUE TITLE
404 Handling

### ISSUE THREAD

**Issue by faergeek** [router5/router5#144]
Hello. First of all, great routing solution 👍 

I have one issue, but I'm not sure if I'm doing the right thing. I ended up with route config like this:

```javascript
export default [
  {name: 'home', path: '/'},
  // also some routes here
  {name: '404', path: '*splat'},
]
```

With this config the problem is that splat route which I use for 404 page takes precedence over home route and only on `router.start`. If I navigate to `home` after `router.start` by clicking a link, it works ok. I don't understand the entire codebase, but I noticed that here `route-node` is pushing home route after splat route https://github.com/troch/route-node/blob/2a49f9f8668c740a22e1e90bde1b03fb324b00c0/modules/RouteNode.js#L110
May be that's causing an issue, not sure.

That's one part of the problem. The other part is why I ended up defining such route for 404. The reason is that middlewares are not called if I get to 404 route with `allowNotFound: true` or `defaultRoute: 404`. I've got an auth middleware which redirects to login page if user is not logged in.

So the behavior with `allowNotFound: true` or `defaultRoute: 404` was that if unauthenticated person navigates to route that exist, middleware redirects him to login page. But when he navigates to route that doesn't exist, middleware is not called and he sees 404. I would like to redirect to login page in both cases.

Can you please suggest a solution to this?

**Comment by troch** [comment]
Hey,

Spats won't work well in that context. For 404s, use `allowNotFound` option on the router: http://router5.github.io/docs/router-options.html. If the router can't match the current path, it will generate a "not found" state.

**Comment by faergeek** [comment]
Yeah, I understand that, but with `allowNotFound: true` I've got the problem with middleware which isn't called on 404.

**Comment by troch** [comment]
Hmm, I've just looked at the code. I don't remember it being intentional to skip transition for not found states.

**Comment by troch** [comment]
I will fix that issue, but I need to bump the version to v5 (it might cause an issue with existing apps). I'm currently in the process of moving all repos into one, will release v5 after that.

**Comment by faergeek** [comment]
Cool, thanks 👍

**Comment by troch** [comment]
Fixed with v5
