### ISSUE TITLE
Trailing slashes should be ignored

### ISSUE THREAD

**Issue by axefrog** [router5/router5#16]
If I set up a route "/foo", it is ignored when the path is "/foo/". Bug or intended behaviour?

**Comment by troch** [comment]
Hi @axefrog. It is not a bug, route matching is strict. However, I will support a few options in the near future:
- Strict path matching (as for now)
- Trailing slashes ignored
- Trailing slashes ignored and path rewritten to the matached route path

**Comment by vojtech-dobes** [comment]
Looking forward to this :). :+1:

**Comment by vvanscherpenseel** [comment]
+1

**Comment by troch** [comment]
0.5.0 released, with support for optional trailing slash. `trailingSlash` option can be set to a truthy or falsy value:
- truthy for optional trailing slash and URL will be rewritten to its intended format
- falsy for strict URL matching (default)
