### ISSUE TITLE
Distinguish browser back navigation from normal navigation

### ISSUE THREAD

**Issue by tomsdev** [router5/router5#165]
Hi, first of all thanks for your great work on router5!

I'm implementing scroll restoration in my application (and some other state than just the scroll state).

I've tried to implement it using my Redux store and without relying on Router5 at all like you suggested in a [related issue](https://github.com/router5/router5/issues/130). However I reached a point where I actually need to distinguish whether a navigation/transition was started because of a normal link navigation or because of the user clicking the browser back button.

The reason is that in my app, if the user navigates to page A, scroll a bit, then navigate to page B and press back button, then I want to restore the scroll on page A. However, if the user navigates to page A using the application menu (and not using the back button) then I don't want to restore the scroll. Thus I need to know what triggered the navigation/transition.

Ideally I'd also like to be able to store and restore some state from History but that's less blocking for now (but if you have some ideas please share).

Thanks for your time!

**Comment by tomsdev** [comment]
Note that ideally this "going back" information should be given in onTransitionStart/onTransitionSuccess/onTransitionError events as they are the only way to connect router5 to a Redux store.

**Comment by troch** [comment]
@tomsdev the initial plan was to include a `source` property in meta. I think it is either broken or was never fully implemented. Will look at it soon.

**Comment by tomsdev** [comment]
I see. I've seen "source" in meta but it was either "popstate" or empty and was not different when clicking on a link VS pressing the browser back button.
Thanks for looking into it!

**Comment by troch** [comment]
@tomsdev I've put a fix in 5.1.3 which has source set to 'popstate' when back / forward buttons are used.
