### ISSUE TITLE
buildUrl for a path '/' with useTrailingSlash=false will break links

### ISSUE THREAD

**Issue by davazp** [router5/router5#168]
Hi,

I found this problem with `react-router5`, but I assume this is the case in other of the helper libraries as well.

Briefly, my use case is:  we have `useTrailingSlash = false`, and our main route has path "/". Then, when I try to navigate to it (e.g: with the `Link` component), it will navigate instead to the current URL.

The reason is that a route with path "/" is formatted as an empty path by `buildUrl`.  Query parameters are appended, but that results in the browser navigating to the URL "?a=b", which counts as a URL relative to the current document.

I think I have narrowed down the problem to the `route-node` library. I created an issue and pull request for it in here:

- https://github.com/troch/route-node/issues/11
- https://github.com/troch/route-node/pull/12

However, I want to track the issue here as well, as my main interest is in router5. So if that is not the right place, I still think router5 should handle this case better.

Hopefully that change is enough and it doesn't break anything in router5 and the library version can just be updated.

**Comment by troch** [comment]
Fixed in route-node, will release tonight a patch.

**Comment by troch** [comment]
v5.1.5 released, thanks again for raising this and fixing it 👍
