### ISSUE TITLE
Will router5 team will be more than 1 soon ?

### ISSUE THREAD

**Issue by Aarbel** [router5/router5#170]
Hi Thomas, thank you for your amazing work ! We use router5 for our react app, we would just like to know if you plan to integrate new people in router5 team to maintain it over the long term ?
It could be very great to make this library more viable and used by more people ;)

Thanks ! - Clovis team

**Comment by troch** [comment]
Hi Clovis team,

The opportunity to offer someone to join me hasn't presented itself up yet, but I will always be open to integrate people to maintain router5. It was one of the drivers behind moving to a monorepo using lerna: make it easier to contribute / maintain / release.

This library is key in my daily work, I use it in production on a large code base with server-side pre-rendering, and functional and reactive techniques (including implementing routing as a side-effect by observing state changes / actions). I also use it on a side project. So I'm currently 100% committed to maintain it, improve it and evolve it. Having more ppl would be great, so this project is not solely relying on me.

Cheers

**Comment by Aarbel** [comment]
Thanks a lot for you answer troch ! We saw too much libraries administrated by one strong man be forgotten or stopped for many reasons. We can't know what will happen tomorrow, could be great to see other administrators ;) (unfortunately it can't be me, my js skills aren't enough :) )
