### ISSUE TITLE
Wrong query serialialization of defaultParams

### ISSUE THREAD

**Issue by Reaverart** [router5/router5#171]
Hey, thanks for a great lib, I found that query serialization is broken at least with defaultParams if empty arrays are presented.
here is the object I use:
```
defaultParams: {
        a: 'string',
        b: [],
        c: [],
        d: [1, 2],
      }
```
and I'm getting following query `?a=string&&&d=1&d=2` as you might see there is additional `&` symbols for removed empty params.
It getting worse after reload, because in this case route cant parse this query string correctly.

**Comment by troch** [comment]
That's an issue. In your case, would you be happy with empty arrays not being serialised?

**Comment by Reaverart** [comment]
Thank you for quick reply! Yep, think empty arrays shouldn't be presented, so in my case it should look like `?a=string&d=1&d=2`

**Comment by troch** [comment]
I've just released a patch (v5.1.6) which fixes it. Thanks for raising this!

**Comment by Reaverart** [comment]
Thanks for fixing it 👍 !
The only thing now it cant parse array params after window reload, i.e. `?a=string&d=1&d=2` becomes to following route params
```
{
        a: 'string',
        d: 2,
}
```
First `d` is lost now.

**Comment by troch** [comment]
Yeah, that's why I asked you the question if you wanted them to be removed or not 😄 
There is a bit of refactoring to do around query parameters to find suitable serialising / deserialising solutions which work for primitive values as well as arrays and objects.

**Comment by Reaverart** [comment]
Yes, query params is hard.. Hmm, In my case `d` wasn't an empty array, so not sure is it related
Do you mind if I open new issue with wrong query parse or thats connected to latest fix?

**Comment by Reaverart** [comment]
Just a thought about tricky moment here, without brackets we cant be sure when `foo=bar` is a `{ foo: bar }` or if it a `{ foo: ['bar'] }`, so maybe we need a configuration option? to serialize arrays in more explicit way, `foo[]=bar` or `foo[0]=bar`?
hmm, a link to consider https://github.com/sindresorhus/query-string#arrayformat-1

**Comment by troch** [comment]
You can add define paths like this `/path?param[]`

**Comment by Reaverart** [comment]
Hi, @troch I was thinking about this issue, the way you mention in last comment isnt really suitable for me because params might change. But what if route config will accept custom `parse` / `serialize` (`encode` / `decode`) function? Then we will have flexible way to control query params on our own, anyone will be able to take any lib he like for parsing/serialization queries or wrtite something specific when needed. Or maybe there is middleware for that?
