### ISSUE TITLE
Navigating to not found state

### ISSUE THREAD

**Issue by davazp** [router5/router5#173]
Hi,

I am struggling to implement a not found handling the way I would like.  I want to keep the same URL, so I do not want to have a specific route for not found. I am using `allowNotFound: true`, such that router5 will create the not found state when no route matches.

The thing here is, for some routes, there is a more semantic meaning of *not found*. Let's say, `/product/{id}`.  When the product doesn't exist, I would like to know (at router level) that the state is not `product`.

However, I can't find a way to `navigate` to it.  It makes sense, as it's not a route. My next attempt was to do

```javascript
router.setState(router.makeNotFoundState(path))
```

however this doesn't quite work, as it does not trigger all the route lifecycle events and plugins can't process the state change.  So redux and react integrations don't update properly.

Any idea how I should do this?  In my opinion,  `setState` should trigger plugin updates somehow,  otherwise I do not see the point in exposing it in first place.

Thanks!

**Comment by troch** [comment]
That is quite a vast question, which can have different answers depending on your set-up (server-side rendering, data loading).

How do you load route-related data?

(`setState` should not be called directly)

**Comment by davazp** [comment]
Sorry I meant to narrow down the question to the scope of router5 only :-) :

Is it possible to `navigate` to a not found state programatically?

If it isn't and it is not sensible adding it, then I have alternative implementations in mind, but I was exploring what options router5 provides and what are its limitations.

> (setState should not be called directly)

Should it be removed from the documentation and be kept internal? or is there other uses for it?

Thanks

**Comment by troch** [comment]
> Is it possible to navigate to a not found state programatically?


You could call navigate with the correct name and params. But it depends the context, you can also fail a transition with a redirect error.

> I have alternative implementations in mind

Please share :)

**Comment by davazp** [comment]
> You could call navigate with the correct name and params. But it depends the context, you can also fail a transition with a redirect error.

But there is no really a name, is there?   I tried `navigate(constants.UNKNOWN_ROUTE, path: ...)` and didn't work. The code didn't suggest it would either.

Failing the transition with a redirect error sounds interesting. I'll give it a try to see the details.

>> I have alternative implementations in mind

> Please share :)

Well, something that would work for us is to keep the route-level not found from the semantic one separated.  I can let `/products/3` to go to the `Product` route, but set a `notFound` flag into the application state (in redux in our case).  And then just this application flag to render the 404 page.

I think I would prefer the router to be aware about it however.

**Comment by troch** [comment]
> But there is no really a name, is there? I tried navigate(constants.UNKNOWN_ROUTE, path: ...) and didn't work. The code didn't suggest it would either.

I can look into it

> Well, something that would work for us is to keep the route-level not found from the semantic one separated. I can let /products/3 to go to the Product route, but set a notFound flag into the application state (in redux in our case). And then just this application flag to render the 404 page.

Nothing wrong with that approach. IMO redirection can only be a good option in case of server-side rendering, as I prefer to not block client-side transitions (waiting for data to load).

> I think I would prefer the router to be aware about it however.

I don't think it is a viable option. The router would need to understand the way you load data (fetch won't return a rejected promise for a 404, you might have multiple requests to make for a single route, you might not want to block client-side transitions, etc...).

It sounds like programmatically being able to navigate to not found will solve it for you?

**Comment by omcg33** [comment]
What is the best way to show 404 page on different routes? SSR is enabled
