### ISSUE TITLE
Route translation / i18n

### ISSUE THREAD

**Issue by mikkelwf** [router5/router5#174]
Hi..

I'm looking to replace react-router, and router5 looks promising.

Also watched your talk, which is interesting btw., and you mentioned something about the choice of named routes. That its a good pattern to keep urls out of the app (which i totally follow).

I've been trying to implement named routes with react-router, and make an abstraction for the router configuration which implements translatable routes.

And since you mentioned that the route configuration for router5 would support route translation, it could be nice to see an example to how this could be implemented..

Is it possible to switch out the routes entirely when you change language, or should the all the translated paths be in the config from the beginning..?

**Comment by troch** [comment]
Hi,

Thanks for watching the talk :) I use translation, but not dynamically: the language is a configuration variable which is used to bootstrapped my app, and the route configuration is generated based on that parameter.

There was a discussion about route translation here: #128.

> And since you mentioned that the route configuration for router5 would support route translation, it could be nice to see an example to how this could be implemented..

There isn't an official way, I've tried it but the main issue is the browsing history. You could replace all the route definitions (paths) at a given time, replace the current history state to display the new path, but then pressing the back button can cause issues. There is also the issue of landing on your application, if the language of the path is not matching the router configuration.

There are a few edge cases to consider and a proper solution would need the router to be aware of your application language to properly match paths from all supported languages, and build paths using the current language. Something I've chosen not to implement yet.
