### ISSUE TITLE
Question: Combine Prevent Navigation + Async Data

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#175]
Hello,
I've been trying to wrap my mind around this problem, probably you have faced this issue before.

Sometimes I need to fetch async data to calculate if a user `canActivate` a particular route.
In your examples you used middlewares to load async data, and I find them very useful. As in your example I store `onActivate` functions in the routes configuration, the middleware will select and execute them on route activation.

Now I need to fetch this async data a step before, that is when executing `canActivate` on a particular route. 

In this case we can't use middleware because: 
> they are invoked in series after the router has made sure active route segments can be deactivated and future active route segments can be activated.

We need to register `canActivate` functions on specific routes: `router.canActivate('admin', canActivate);`. 

**1)** I think this is less flexible compared to middleware, because we explicitly have to register `canActivate` and `canDeactivate` functions one by one, instead of storing functions on routes configuration (as in the case of `onActivate`). Wouldn't it be a good idea to have `canActivate` and `canDeactivate` middlewares? These would be invoked a step before the standard middlewares just to have a bit more flexibility.

**2)** Going back to the initial problem I can fetch async data inside an `canActivate` function but then I would need the same data in the `onActivate` function called by the (standard) middlewares. How could I pass this data without fetching them again?

I could probably use a store, but would it be possible (and how) to do this using only router5 logic?

Thanks

**Comment by troch** [comment]
> I think this is less flexible compared to middleware, because we explicitly have to register canActivate and canDeactivate functions one by one, instead of storing functions on routes configuration (as in the case of onActivate). Wouldn't it be a good idea to have canActivate and canDeactivate middlewares? These would be invoked a step before the standard middlewares just to have a bit more flexibility.

`canActivate` functions on route config objects are registered. `canDeactivate` are not, but look at this issue: #163 

> Going back to the initial problem I can fetch async data inside an canActivate function but then I would need the same data in the onActivate function called by the (standard) middlewares. How could I pass this data without fetching them again?

You can use your own container (store, simple object). One thing which could be added is the ability to augment the state object passed to those functions, the same way you can do it with middlelwares, so the state object can be your container.

**Comment by LeonardoGentile** [comment]
> canActivate functions on route config objects are registered.
 
I've understood the general difference but what do you mean exactly by 'registered'?

> One thing which could be added is the ability to augment the state object passed to those functions, the same way you can do it with middlelwares, so the state object can be your container.

Meaning this is not available in `canActivate` and `canDeactivate` or meaning that you are suggesting me I could use this this approach if I want to?

**Comment by troch** [comment]
> I've understood the general difference but what do you mean exactly by 'registered'?

They are added to the router.

> Meaning this is not available in canActivate and canDeactivate or meaning that you are suggesting me I could use this this approach if I want to?

This is not available, but it is a two line change I should make anyway to keep things consistent.

**Comment by LeonardoGentile** [comment]
Thank you very much
