### ISSUE TITLE
How to catch Navigation Error And Redirects when using BrowserPlugin

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#176]
Related to #175.
In case one of my canActivate function returns a rejected promise (or false) how to catch and redirect when using the browserPlugin?

In your example you do this:

```
router.canActivate('profile', (router) => (toState, fromState, done) => {
    return isUserLoggedIn()
        .catch(() => Promise.reject({ redirect: { name: 'login' }}));
});

router.navigate('profile', (err, state) => {
    // err is null
    state.name === 'login';
});
```
But when I manually change the urls in the browser I am not manually calling `router.navigate` so how can I catch the potential rejected promises returned by canActivate (or from a middleware)?

**Comment by LeonardoGentile** [comment]
It seems that when returning a rejected promise from a middleware the browser plugin ignores it, in fact [this line](https://github.com/router5/router5/blob/master/packages/router5/modules/plugins/browser/index.js#L100) is executed synchronously before the promise could be resolved or rejected.

In fact the cutom redirect error won't work/

Here's my configuration:
```

const onRouteActivateMiddlewareFactory = (routes) => (router, dependencies) => (toState, fromState, done) => {
    const { toActivate } = transitionPath(toState, fromState);
    toActivate.forEach(segment => {
        const routeSegment = routes.find(r => r.name === segment);

        if (routeSegment && routeSegment.onActivate) {
          routeSegment.onActivate(toState);
        }
    });
};

export default function configureRouter(useLogger) {
  const router = createRouter(routes, routerOptions)
    .usePlugin(browserPlugin({useHash: true}));

  if (useLogger) {
    router.usePlugin(loggerPlugin);
  }
  router.useMiddleware(onRouteActivateMiddlewareFactory(routes));
  return router;
```

```
// routes
export default [
  {name: 'home', path: '/'},
  {
    name: 'index',
    path: '/index/:id',
    onActivate: (route) => {
    // getIndex returns a promise  
    return getIndex(route.params.id)
        .then(data => {
          if (data.data.canActivate) {
            return data;
          }
          else return Promise.reject({
            code: 'UNAUTHORIZED',
            segment: route.name,
            redirect: { name: 'basket', params: {id: "hello"} }
          });
        })
        .then(data => {
          return tabStore.activateTab(route, data.data.tabTitle);
        })
        .catch(err => {
          return Promise.reject(err);
        })
    }
  },
  {name: 'basket', path: '/basket/:id'}
]
```
Everything is executed and the last catch returns a rejected promise but this won't be caught by anybody 🤔  in fact I get: `Uncaught (in promise) {code: "UNAUTHORIZED", segment: "index", redirect: {…}}`

If I do a similar logic using on a `onActivate('index', callback)` I get redirection:

```
const canActivateIndex = (router, dependencies) => (toState, fromState) => {

  return getIndex(toState.params.id)
    .then(data => {
      return data.data.canActivate || Promise.reject({ redirect: { name: 'basket', params: {id: "hello"} } });
   });
};

router.canActivate('index', canActivateIndex);
```
In this case I get a redirection.

In both cases I don't know from where to catch the rejected promise when using the browser plugin..

**Comment by troch** [comment]
Your `onRouteActivateMiddlewareFactory` creates a middleware which never returns a promise (it calls the `onActivate` method of each segment to activate, but doesn't return anything)

**Comment by troch** [comment]
That means the router doesn't wait for your data to be loaded before redirecting, and it is also unaware of any error and redirection required.

**Comment by LeonardoGentile** [comment]
Thanks @troch 
You are right, but adding `return routeSegment.onActivate(toState);` doesn't change much. I get the same error and also can't navigate anymore.

The only way to make this work is:

```
const onRouteActivateMiddlewareFactory = (routes) => (router, dependencies) => (toState, fromState, done) => {
    const { toActivate } = transitionPath(toState, fromState);
    toActivate.forEach(segment => {
        const routeSegment = routes.find(r => r.name === segment);
        if (routeSegment && routeSegment.onActivate) {
          return routeSegment.onActivate(toState)
            .then(data => {
              done(null);
            })
            .catch(err => {
              done(err);
            });
        }
        done(null);
    });
};
```
So I have to explicitly use the done() callback to signal my function is done. 
This work but I'm not sure what was wrong just by returning a promise.

Please notice that return the promise as in my first example (with the return of course) works for `canActivate`

**Comment by troch** [comment]
`return routeSegment.onActivate(toState)` is inside a `forEach`, it doesn't return a promise within the `(toState, fromState) => {}` function.

**Comment by LeonardoGentile** [comment]
Totally right, I got confused inside promises!

I think your promise example at http://router5.github.io/docs/async-data.html is missing a step (please correct me if mistaken).

```
const routes = [
    {
        name: 'home',
        path: '/home'
    },
    {
        name: 'users',
        path: '/users',
        onActivate: (params) => fetch('/users').then(data => ({ users: data.users }))
    },
    {
        name: 'users.user',
        path: '/:id',
        onActivate: (params) => fetch(`/users/${params.id}`).then(data => ({ user: data.user }))
    }
];

import transitionPath from 'router5.transition-path';

const dataMiddlewareFactory = (routes) => (router) => (toState, fromState) => {
    const { toActivate } = transitionPath(toState, fromState);
    const onActivateHandlers =
        toActivate
            .map(segment => routes.find(r => r.name === segment).onActivate)
            .filter(Boolean)

    return Promise
        .all(onActivateHandlers) // <== HERE: We are not passing `params` to the onActivateHandlers
        .then(data => {
            const routeData = data.reduce((accData, rData) => Object.assign(accData, rData), {});
            return { ...toState, data: routeData };
        });
};

```

So I tough the middlewareFactory should be changed to take into account passing `params` to the functions that actually return the promises:

```
const dataMiddlewareFactory = (routes) => (router) => (toState, fromState) => {
    const { toActivate } = transitionPath(toState, fromState);
    const onActivateHandlers =
        toActivate
            .map(segment => routes.find(r => r.name === segment).onActivate)
            .filter(Boolean)

    return Promise
        .all(onActivateHandlers.map(callback => callback(toState.params)) // <== HERE
        // .all(onActivateHandlers.map(callback => callback.bind(null, toState.params)) // <== OR this approach
        .then(data => {
            const routeData = data.reduce((accData, rData) => Object.assign(accData, rData), {});
            return { ...toState, data: routeData };
        });
};
```

**Comment by LeonardoGentile** [comment]
And just one more question to be sure I've understood: anything returned from the second arguments of `done(null, data)` or from a resolved promise is the new toState object, right?

I guess it's not mandatory to return this new toState if we managed to pass the needed data around to some external store, right?

**Comment by troch** [comment]
> I think your promise example at http://router5.github.io/docs/async-data.html is missing a step (please correct me if mistaken).

I show blocking and non-blocking examples. They are probably not perfectly working, their goal is to be illustrative.

> I guess it's not mandatory to return this new toState if we managed to pass the needed data around to some external store, right?

Correct.

> I guess it's not mandatory to return this new toState if we managed to pass the needed data around to some external store, right?

If you don't need to enhance your state object with any data, then you don't need to pass it to done.

**Comment by LeonardoGentile** [comment]
Thanks very much, just one more thing, as for my initial question:

In case one of my canActivate function returns a rejected promise (or false) I now know how to redirect, but how, more generally, can I catch when using the browserPlugin? I don't use router.navigate directly

**Comment by troch** [comment]
The browser plugin only changes the URL and responds to `popstate` events. The only way to navigate is to use `start()` and `navigate()`.
