### ISSUE TITLE
Browser url do not change after redirect error

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#177]
I'm using a middleware for fetching async data and  check user has permission for the current route. All navigation is happening by changing the browser's url, so by the browser plugin.

Let's say I am in A and I want to go to B, if the middleware raise an error then I add a custom 
```
{redirect: { name: 'C', params: {id: "hello"} } }
```
If the middleware calls a done(error) then I will be correctly redirected to **C**.

The problem comes when we are already in **C**, so I manually change the browser url to go to B. But again our middleware don't let us, in this case it will redirect again to C. But we are already in C, so a new **SAME_STATE** error will be raised, we will remain where we are but what seems to be the problem is that the url won't change, it will point to **B** even we are correctly in **C** (we never moved from here)

**Comment by troch** [comment]
I see. It is only an issue because of `useHash`. I will look at it.

**Comment by troch** [comment]
Fixed in #188, will be merged soon
