### ISSUE TITLE
Router5 doesn't respect the base path when matching route paths

### ISSUE THREAD

**Issue by axefrog** [router5/router5#18]
If I specify a base, I can't seem to match routes properly.

If I don't specify a base, everything works fine. If I want to specify a base, then I can't get routes to match at all.

For example, here are some routes:
```
routes: [
  { name: 'home', path: '/' },
  { name: 'foo', path: '/foo' }
],
```
If I want to use a `base` of `'/admin'` (i've also tried `location.origin + '/admin'`) then the home route doesn't match at all when `location.pathname` is `'/admin'`, and if i try to set the home path to `'/admin'` then router5 ends up redirecting me to `'/admin/admin'`.

What am I doing wrong? Is this a bug?

```js
console.log(location.href); // http://localhost:3000/admin
console.log(location.origin + location.pathname); // http://localhost:3000/admin
console.log(router.matchPath(location.href)); // null
console.log(router.matchPath(location.origin)); // null
console.log(router.matchPath(location.pathname)); // null
console.log(router.matchPath(location.origin + location.pathname)); // null
console.log(router.matchPath(location.origin + '/')); // null
console.log(router.matchPath(location.origin + '/admin')); // null
console.log(router.matchPath(location.origin + '/admin/')); // null
console.log(router.matchPath(location.origin + '/admin/foo')); // null
console.log(router.matchPath(location.origin + '/foo')); // null
console.log(router.matchPath('/')); // Object {name: "home", params: Object, path: "/"}
console.log(router.matchPath('/admin')); // null
console.log(router.matchPath('/admin/')); // null
console.log(router.matchPath('/admin/foo')); // null
console.log(router.matchPath('/foo')); // Object {name: "foo", params: Object, path: "/foo"}
```

**Comment by troch** [comment]
Hi @axefrog,

`base` is not for adding a prefix to all your URLs, but to tell the router what is the base path of your page. It is only needed if `useHash` is set to false, and is designed to prevent the router overwriting your initial pathname (so instead it preserves it).

Don't pass `location.origin` to the router, it won't know what to do with it. The part to match is location.pathname (minus your base).

From your console.log examples, it seems the router is ignoring your base. Could you share more of your router configuration?

On an unrelated note, optional trailing slashes won't work if url is "/". I had a few issues with it that I am still trying to fix.

**Comment by troch** [comment]
I have edited my answer

**Comment by axefrog** [comment]
There's nothing special about my setup other than I'm using the optional trailing slashes option. I included all of those `console.log` examples just to demonstrate all of the things I tried in the process of trying to work out what I might be doing wrong. I'm not using hashes at all.

As far as "correct" usage goes, I'm not sure. All I know is that the current `location.href` changes and I have to somehow match that to a route. If I use a base that has a subpath, nothing works as expected.

The behaviour I'd intuitively assumed was that the base path would always be respected, no matter what, which makes logical sense, because if you declare a base path, of course all of your routes are going to hang off of it, and so passing a URL to `matchPath` would be able to look at the declared `base`, the pathname and be able to extrapolate from there.

In any case, I'll just avoid using `base` and make sure "/admin" is prepended to all of my route paths.

**Comment by troch** [comment]
I think you are missing a method. `matchPath()` is designed to match the extracted path from an URL. I'll implement a `matchUrl()`.

**Comment by axefrog** [comment]
Ah ok so it's assumed that `matchPath()` is called *after* you've manually removed your own base path?

**Comment by troch** [comment]
`matchPath` is just exposing the `matchPath` function from the root node (see [route-node](https://github.com/troch/route-node). `matchPath` is used internally, but I can see you need more than `matchPath` with the way you implemented cycle-router5.

Also, optional trailing slashes won't work if path === "/". I had a few issues with it that I am still trying to fix. I'll let you know when it works.

**Comment by axefrog** [comment]
No worries. I'm still getting a feel for router5 myself if I'm completely honest, so I'm hoping that after a few people have started to use it with cycle that we'll start to get a better idea of what is needed and what (if any) shortcomings need to be addressed.

**Comment by troch** [comment]
No problem. There is also `.getLocation()` which can extract the path from the current URL (but I guess it is useless to you!)

**Comment by axefrog** [comment]
Cool. I think I'm going to be overhauling cycle-router5 now that I've got a sense of how router5 works versus the idioms of a Cycle.js application. The node-based architecture of router5 will come into play in a big way I think.

**Comment by troch** [comment]
Just released v0.5.1 with two new methods:
- `.urlToPath(url)` (useful for debugging)
- `.matchUrl(url)`

**Comment by axefrog** [comment]
Fantastic, thanks! I'll get it into cycle-router5.

**Comment by troch** [comment]
v0.5.3 released: removed a `console.log`, and now it supports optional trailing slash for '/'
