### ISSUE TITLE
Returning promises instead of using callbacks

### ISSUE THREAD

**Issue by lostpebble** [router5/router5#180]
I'm not sure if Router5 already allows it, but from reading through the docs and API reference I can't seem to find a mention of it anywhere.

After making use of Promises in just about everything for the past year I've come to loath callbacks. My code has become a lot cleaner and more readable using the new async/await syntax which makes use of promises.

I'd like to know if the following would be possible (creating and using a router instance on my server):

```
const router = createRouter(/* options */);

const routerState = await router.start(req.originalUrl);

/* continue request operations */

/* Use router state, send some HTML! */
```
(In this example I can catch errors in a higher `try { } catch (err) { }` statement)

As opposed to:

```
const router = createRouter(/* options */);

router.start( req.originalUrl, function done( error, state ) {
    if ( error ) {
        res.status( 500 ).send( error );
    } else {
        /* continue request operations */

        /* Use your router state, send some HTML! */
    }
});
```

**Comment by troch** [comment]
Both `start` and `navigate` take a callback and don't return a promise. Callbacks are used because they work in any context. If you need to use promises, you can create your own start function returning a promise.

**Comment by lostpebble** [comment]
Yep, that's what I've done now. It just seems the norm now for libraries to add promises optionally where callbacks were traditionally used before. Modern JavaScript programming tends to be moving towards the Promise pattern (especially with `async/await` making code so much easier to reason about), so something to think about adding perhaps?

Not that big of a deal cause I've wrapped it myself now - but I think a lot of new users might come expecting Promises out the box.

**Comment by troch** [comment]
Start and navigate can be both asynchronous or synchronous, depending on what is added by library users. Promises are not a replacement for callbacks, there are another tool to deal with asynchronous code, and it's not the only one. 

No plans to change that behaviour yet.
