### ISSUE TITLE
Prevent Browser Plugin to Navigate to Default Route in case of CANNOT_ACTIVATE Error

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#182]
Hello,
In my custom `canActivate` function I check if a user has the rights to access a specific route.
If not then I manage to show a modal window to tell the user why he can't do so.

The problem is that when manually changing the url in the browser then the browser plugin creates a different behaviour.

That is: on a `CANNOT_ACTIVATE` error my modal is correctly open but soon after [this code](https://github.com/router5/router5/blob/master/dist/router5BrowserPlugin.js#L264) will run and will redirect the user to the default page (home for example).

Is there a way to disable this behaviour? Whenever a user cannot activate a route (whether or not using the browser plugin) I want the user to remain where he was originally, my custom logic will take care of showing modal and/or redirect.

**Comment by LeonardoGentile** [comment]
It seems that this doesn't happen if we don't pass a `defaultRoute` to the router options.
But I would like to keep this option, while disabling the `CANNOT_ACTIVATE` redirection by the browser plugin

**Comment by troch** [comment]
It is the point of a default route and as you mentioned, not defining a default route stops that behaviour.

I'm not sure removing that behaviour would be beneficial.

**Comment by LeonardoGentile** [comment]
@troch as I can read from the docs
>  if such route is defined and if it cannot match the URL against a known route defaultRoute: the default route.

My exposed case is not when we cannot find a route. The route exists, it just is not accessible. IMO they are two different cases. I want to keep redirection to the default route when the user navigate to an unknown route and but I don't want the redirection when I manually raise a `CANNOT_ACTIVATE` error. I would prefer to handle that manually

**Comment by troch** [comment]
@LeonardoGentile I'll add an option to the browser plugin

**Comment by LeonardoGentile** [comment]
thank you @troch 👍 
1) If we don't specify `defaultRoute` then we will not get any redirection even for not found routes, right?

2) Instead of handling the multiple use cases (redirection on _not found route_, redirection on _route that could not be activated_, etcr) I guess that if you better document the errors listed [here](https://github.com/router5/router5/blob/master/packages/router5/modules/constants.js)  (ROUTE_NOT_FOUND, SAME_STATES, CANNOT_DEACTIVATE and so on) you could leave to the users (us) the logic for redirection 

The second point is related to #176. It's still not clear to me how to catch navigation error when manually changing the url when using the browser plugin. The browser plugin calls the router `navigate` method, but since we are not calling it manually we can't pass error handlers to it.
