### ISSUE TITLE
How to implement "redirect after login"

### ISSUE THREAD

**Issue by ezzatron** [router5/router5#184]
I'm trying to implement a typical login system with router5. So far I've used `canActivate` handlers, which are working well to redirect the user to the login form when they try to access a route that requires authentication.

One convenience that users will expect is that once authentication has succeeded, they will be redirected to the route that they originally requested, as in this example flow:

1. User navigates to `profile`
2. User is redirected to `login` to authenticate
3. User authenticates successfully
4. User is redirected back to `profile`

But, when redirecting to `login`, I cannot figure out an elegant way to store the user's intended route name and params for later retrieval. I could add them as params of `login`, but then they're exposed in the address, and I think it would be neater to keep them hidden - especially the params.

This is relatively easy in `react-router` because is supports arbitrary data in the router state:

```js
replace({
  pathname: '/login',
  state: {nextPathname: nextState.location.pathname}
})

// then later...

if (location.state && location.state.nextPathname) {
  router.replace(location.state.nextPathname)
} else {
  router.replace('/')
}
```

But when I try something similar in router5, using `meta`, it seems like the information is ignored:

```js
export function createRequireAuth (store) {
  return router => {
    return function requireAuth (toState, fromState, done) {
      if (isAuthenticated(store.getState())) return done()

      done({
        redirect: {
          name: 'login',
          meta: {
            nextName: toState.name,
            nextParams: toState.params
          }
        }
      })
    }
  }
}
```

Any advice to point me in the right direction would be appreciated. Thanks!

**Comment by troch** [comment]
Just change `meta` to `params`:

```js
params: {
    nextName: toState.name,
    nextParams: toState.params
}
```

As long as `nextName` and `nextParams` are not defined in the path of your login route, they won't appear in the URL but will be in your router state object (easily accessible in your login form, to navigate after your users have successfully logged in)

**Comment by LeonardoGentile** [comment]
> As long as nextName and nextParams are not defined in the path of your login route, they won't appear in the URL but will be in your router state object

This a very valuable information, it should be documented.

Also, given that during normal navigation we can inject any field into the state object (see middleware for example) passing extra field into the params object seems incoherent. 
Would't it be more clear if the redirect object would also accepts any arbitrary fields (besides the name and params)?

**Comment by ezzatron** [comment]
> As long as nextName and nextParams are not defined in the path of your login route, they won't appear in the URL but will be in your router state object

@troch This really confused me, because I tried that and the extra params ***did*** appear in the URL. A bit of digging, and I realised that it only works with the router option `strictQueryParams: true`. If you have `strictQueryParams: false` ([which is the default since v5](http://router5.github.io/docs/migration-5.html)), then this statement is incorrect.

That's unfortunate, because I'm using `strictQueryParams: false` for another reason.

**Comment by LeonardoGentile** [comment]
@ezzatron as the current implementation of redirect after error seems a bit limited to me I can suggest you another way I'm following: catch the navigation errors in a higher scope and then depending on what type of error you have you can redirect accordingly
