### ISSUE TITLE
Consistent state.meta.id

### ISSUE THREAD

**Issue by eugenkiss** [router5/router5#185]
To implement a scroll (and other view state) restoration plugin I used a `state`'s `meta.id` field as kind of cursor into the history stack. For example, a `state` with `meta.id = 3` would represent the third entry in the history stack and I would save a component `c`'s scroll position `s` in a map `m` as `m[3][id(c)] = s`. When the user goes back in the history such that `meta.id = 3` I could restore `s` from `m`.

However, it seems that [this change](https://github.com/router5/router5/commit/5d5d9fc2f08e5c7421ebeaf112a6c8c8e5016ef6) broke the relied-on consistency of the `meta.id` field. Before I try to recreate the cursor-like behavior in my application code I'd like to ask if you there is still a way to get a kind of cursor directly from router5 even after the mentioned commit.

**Comment by troch** [comment]
Hi @eugenkiss, you are right the change you pointed out now creates a new meta ID for popped states. I've re-instated the previous behaviour in #187.

**Comment by eugenkiss** [comment]
Awesome, thanks @troch!
