### ISSUE TITLE
isActive with null parameter

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#189]
If config is `{name: 'components', path: '/components/?:section?:tab'`, current url is `/components` and I'm calling isActive like
```javascript
isActive('components', {tab: null}, false, false);
```
it returns `false`, but seems like it should be true

**Comment by troch** [comment]
I would be tempted to say "won't fix", because I think it is more a query params serialisation issue (which will be reworked) than a `isActive` issue. Route name 'components' with params `{tab: null}` should serialise to `'/components/?tab=null'`

**Comment by klimashkin** [comment]
But result url is `/components` since setting param to null removes it from url? This is very convenient behavior currently

**Comment by troch** [comment]
I won't fix this one, due to future changes to query parameters (and null values will appear in the URL).
