### ISSUE TITLE
Query parameters: Specify on intermediate nodes/Make optional

### ISSUE THREAD

**Issue by Nickman87** [router5/router5#19]
Hi,

I'm making a React router based on Router5 and all seems to be working fine for now except for query parameters.
I like the way the query parameters and the url parameters are just one big collection, but I need to be able to make my query parameters optional AND provide them in intermediary nodes, i.e.:

```javascript
var myRouter = new Router5([
    {name: 'app', path: '/', children: [
        {name: 'calendar', path: 'calendar/:id/', children: [
            {name: 'period', path: 'week/?date', children: [
                 {name: 'details', path:'details/?mode'}
            ]},
        ]},
    ]}
]);
```

As you can see, the node `period` specifies an optional query parameter `date` and the following child node `details` also specified an optional query parameter `mode`.

Is there I was I can make this work with the current router? Or would it be possible to get this supported?

A Solution I was considering was to pre-parse all routes, extract the query parameters and create routes with all possible combinations of query parameters, but this seems like a lot of hassle for something that is quite commonly used?

**Comment by troch** [comment]
Hi @Nickman87,

I didn't account for this case when designing the router, so you won't be able to make it work for now. [path-parser](/troch/path-parser) makes query parameters optional (so no need to create all possible combinations), I just need [route-node](/troch/route-node) to be a bit more clever on how it consumes route segments when matching.

**Comment by Nickman87** [comment]
I just tried my suggested solution to get a workaround, but this isn't working as route names are no longer unique now.
Would it be usefull for me to try and fix route-node to support this feature and provide a pull-request?

**Comment by troch** [comment]
I'll be on it tomorrow

**Comment by Nickman87** [comment]
Awesome! I'll be looking out for it :+1:

**Comment by troch** [comment]
Making good progress on this. I have it working on route-node, I'll integrate it to router5 tonight.

**Comment by troch** [comment]
0.6.0 released, it now handles nested query parameters. Query parameters are optional, so you can specify all of them or none of them and a route will still match. However, if your path containing extra query parameters (not defined in your routes), it won't match.

**Comment by Nickman87** [comment]
Awesome, thanks for the quick response!

**Comment by troch** [comment]
No problem. Let me know if you experience any issues!

**Comment by Nickman87** [comment]
It seems to be working fine for now, If problems arise with a more complicated setup I'll let you know :)
:+1:
