### ISSUE TITLE
Update getting started doc?

### ISSUE THREAD

**Issue by acchou** [router5/router5#194]
The getting started page has the following suggested imports:
```
import Router5, { RouteNode, errorCodes, transitionPath, loggerPlugin } from 'router5';

import browserPlugin from 'router5/plugins/browser';
import listenersPlugin from 'router5/plugins/listeners';
import persistentParamsPlugin from 'router5/plugins/persistentParams';
```

But I noticed that

(1) `RouteNode` isn't in the `router5` module
(2) `persistentParamsPlugin` isn't declared in `index.d.ts` (I'm using Typescript).

It looks like (2) can be fixed with an additional module declaration. Not sure how to fix (1). Happy to create a pull request if I can get some direction on which way to go.

**Comment by troch** [comment]
Actually there is a typo here: it should be `createRouter` and not `Router5`, it has been fixed.

`RouteNode` should be exported: https://github.com/router5/router5/blob/master/packages/router5/modules/index.js#L11, but type definitions are missing. I would not recommend using it (less options available), and use plain objects instead (see https://github.com/router5/router5/blob/master/packages/router5/index.d.ts#L363-L378)

`persistentParamsPlugin` isn't defined, that's right. PR welcome! Add it at the end of the definition file, after other plugins (browser plugin, listeners plugin). Source is here: https://github.com/router5/router5/blob/master/packages/router5/modules/plugins/persistentParams/index.js, it takes a single argument which can be:
- A list of string (parameter names to persist)
- A map of key value pairs (keys being the params to persist, values their initial value)

**Comment by acchou** [comment]
Thanks, I will take a crack at type definitions for `persistentParamsPlugin`. I also noticed that `rxjs-router5` doesn't have type definitions. Would it make sense to attempt that as well? I can put the `index.d.ts` in `packages/rxjs-router5`.

**Comment by troch** [comment]
> I can put the index.d.ts in packages/rxjs-router5

Please :)
