### ISSUE TITLE
Cancel transition in middleware on browser back/forward

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#195]
I have async middleware for router that check something or fetch some data.
If user press Esc while middleware is working I throw `throw {code: errorCodes.TRANSITION_CANCELLED};` to stop url change and abort all fetching.

And it works perfectly, until user click Esc on running middleware that was invoked by browser history change (back/forward buttons). In that case router, instead of just cancelling transition, navigates to root (`/#`) which invokes next middleware like throwing error with `redirect` prop.

My config:
```javascript
forceDeactivate: true,
useHash: true,
hashPrefix: '',
base: '',
mergeState: false,
preserveHash: false,
```

**Comment by klimashkin** [comment]
Checked, the same happens if I replace `TRANSITION_CANCELLED` with `TRANSITION_ERR` or even dispatch `actions.cancelTransition()` right from that middleware

**Comment by klimashkin** [comment]
Hm.. and if I add `redirect` prop to error like this
```javascript
const toThrow = {};

if (this.router.buildUrl(toState.name, toState.params) === window.location.hash) {
  toThrow.redirect = {name: fromState.name, params: fromState.params};
}

throw toThrow;
```

Then router just keep target url (that in toState)

**Comment by troch** [comment]
Would you be able to create a repo or host some code somewhere which reproduces the error?
