### ISSUE TITLE
rxjs-router5 tests not running

### ISSUE THREAD

**Issue by acchou** [router5/router5#197]
I noticed that `rxjs-router5` tests are not running because the test directory is named `_test` instead of `test`.

The test command appears to be:
```
$ mocha --compilers js:babel-core/register --require test-helper.js --recursive 'packages/*/test/**/*.js'
```

Should we rename `_test` to `test`?

**Comment by troch** [comment]
It should be renamed yes. But I'm not sure they work.

**Comment by troch** [comment]
To clarify, I don't know how well `rxjs-router5` works. I copied the implementation from `xstream-router5` (which itself fully works), using RxJS observables. So any help would be appreciated 👍
