### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by dgieselaar** [router5/router5#200]
Hi,

I currently have a route structure that looks like this:
- Main (all routes)
-- Home (/:continent?)
-- Entity (/:country/:region/:city)

The continent path is optional. How can I achieve this with Router5? The only requirement that I have is that both `/` and `/africa` (for instance) have the same parent (`Home`) route. I've tried fiddling with absolute paths, and regexes with empty strings, but all approaches break down at some point.

**Comment by troch** [comment]
Optional parameters are not supported in router5 (a design decision), and the way to achieve it is to define two routes (one with param, one without) with a parent forwarding to the non-param one by default (using `forwardTo` route option).

Don't forget to set router5 option `useTrailingSlash: false` for it to strip trailing slashes when building (or set it to `true` if you want trailing slashes to always be added).

```js
[
	{
		name: 'section',
		path: '/',
		forwardTo: 'section.home'
	},
	{
		name: 'section.home',
		path: '/'
	},
	{
		name: 'section.subsection',
		path: '/:subsectionParam'
	}
]
```

In your case, something like:

```js
[
	{
		name: 'continent',
		path: '/',
		forwardTo: 'continent.default'
	},
	{
		name: 'continent.default',
		path: '/'
	},
	{
		name: 'continent.view',
		path: '/:continent'
	}
]
```

**Comment by dgieselaar** [comment]
I tried that, but then I get the following error:

```
DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://localhost:3000/
```

For me, the route structure is:
```
const routes = [
    { name: 'root', path: '/' },
    { name: 'root.home', path: '/' },
    { name: 'root.home.index', path: '/' },
    { name: 'root.home.continent', path: 'midden-amerika' },
  ];
```

So it might be the fact that I have an additional root route that causes the double slash to show up. Perhaps the fix is just to remove the repeated slashes? I can do the work if you point me in the right direction.

**Comment by troch** [comment]
The issue can be fixed here, by replacing successive slashes by one: https://github.com/troch/route-node/blob/master/modules/RouteNode.js#L331

**Comment by dgieselaar** [comment]
Ah, that fixes buildPath, but breaks matchPath, i.e.:
```javascript
buildPath('root.home.continent', { continent: 'midden-amerika' }); // '/midden-amerika'
matchPath('/midden-amerika'); // null
```
Presumably that is because the slashes get stripped when they encounter the parent routes. That might be fixable but I'm starting to doubt if it's the right way to go about it. Any alternatives or suggestions?

**Comment by troch** [comment]
OK, I guess it needs a tweak somewhere to not consume a slash from the path. Maybe that line could change: https://github.com/troch/route-node/blob/master/modules/RouteNode.js#L214 (not consuming anything from the path if consumed path is `'/'`)

> are pathless routes problematic?

Yes they are: I would need to either add exploring multiple subtrees which would add complexity (and a slight performance impact), or limit pathless routes to one per node. I much prefer `'/'` being the equivalent of path-less.

**Comment by dgieselaar** [comment]
Alright, thanks for the tips. I've written some tests and it seems to work now. Will submit a PR in a bit.

**Comment by klimashkin** [comment]
Faced with the same issue. Would it be possible to add `forwardParams` property?
Like `forwardTo: 'continent.view' forwardParams: {continent: 'africa'}`

**Comment by troch** [comment]
There is `defaultParams` available, would that work?

**Comment by klimashkin** [comment]
From docs I thought that `defaultParams` is a global option, or it can be set for each route?
Let me try.

**Comment by troch** [comment]
It is both. Support for route level `defaultParams` has been added on the last minor version release.

**Comment by klimashkin** [comment]
Now I see, didn't notice that in changelog, thanks!
But seems it doesn't work in that case

I have
```javascript
{name: "app", path: "?:showVersion"},
{name: "app.ip", path: "/ip"},
{name: "app.ip.list", path: "/?:sort?:page"},
{name: "app.ip.item", path: "/:id", forwardTo: "app.ip.item.view"},
{name: "app.ip.item.edit", path: "/edit"},
{name: "app.ip.item.view", path: "/:version", defaultParams: {version: 'active'}},
```
And if I navigate to `/ip/5` I got `Uncaught Error: Cannot build path: '/:version' requires missing parameters { version } at Path.build$$1`

**Comment by troch** [comment]
Can you check the version you're on? After both testing it and reading the code, I can't see why `defaultParams` wouldn't work in that case.

**Comment by klimashkin** [comment]
Checked, 
router5 `5.8.1`
react-router5 `5.4.2`
redux-router5 `5.2.1`
router5-transition-path `5.1.1`

**Comment by klimashkin** [comment]
Tried to apply `encodeParams` and `decodeParams` to route like this
`{name: "app.ip.item.view", path: "/:version", encodeParams: (a, b) => {debugger;}, decodeParams: (a, b) => {debugger;}}`
And it never gets called also.

Maybe my options are wrong?
```
allowNotFound: false
autoCleanUp: true
defaultRoute: "app"
strictQueryParams: false
trailingSlash: true
useTrailingSlash: false
```

**Comment by troch** [comment]
I found the issue (#253) and will release a patch soon.

**Comment by jacobweber** [comment]
> Optional parameters are not supported in router5 (a design decision), and the way to achieve it is to define two routes (one with param, one without) with a parent forwarding to the non-param one by default (using forwardTo route option).

This confused me a little until I found this bug. You might want to clarify [this section](http://router5.github.io/docs/router-options.html) of the docs, which says:

> Query parameters are optional, meaning a route can still be matched if a query parameter defined in its path is not present.
