### ISSUE TITLE
Move to next child on partial matches

### ISSUE THREAD

**Issue by dgieselaar** [router5/router5#202]
Hi,

from what I can tell `route-node` currently does not attempt to find any more matching routes as soon as a partial match is found, even if that partial match in the end is not fully matched. Is this correct? Is there any reason for this behaviour, and would you be open to a PR that changes the lookup to move on the next child on a partial match?

**Comment by troch** [comment]
A partial match dictates the path followed in the routes tree. It is a design decision, for optimisation. Siblings are sorted in a specific order (sorting by length of path, number of segments, param / not param, etc...) so that it matches correctly.

Have you encountered a case where it doesn't match correctly?

**Comment by dgieselaar** [comment]
Yeah, we have a pretty complex routing structure due to legacy SEO reasons. I have the following paths:

- A: `:paramA/:paramB/:country/:region`
- B: `:paramA/:paramB/:country`

They are not necessarily parent/child, but more like siblings (it will result in the same view type, just with different data).

Because A has more parameters than B, it is ordered after B. Both partially match the following URL:
`/hotel/stedentrip/duitsland/beieren`, but because B is matched first, and will only match partially and not completely, `matchPath` will return null.

Any ideas? Maybe having the more complete/slower matching as optional will suffice?

**Comment by troch** [comment]
The behaviour you describe shouldn't really happen, I'm trying to remember what happens here: https://github.com/troch/route-node/blame/master/modules/RouteNode.js#L204

**Comment by dgieselaar** [comment]
I have really complex regexes, for instance: `:endecaA<hotels|stedentrip>/:endecaB<hotels|stedentrip>/:country<(?:(?!hotels|stedentrip)[^\/])*>/:area<(?:(?!hotels|stedentrip)[^\/])*>`. That might be the cause. In any case, I'm going to try to define my routes in a different way to see if I can work around it, will make sure I'll report back in this issue and do the investigation if necessary. Thanks for the responsiveness!

**Comment by dgieselaar** [comment]
Found the problem, opened a PR with a fix: https://github.com/troch/route-node/pull/14.

**Comment by troch** [comment]
Merged and released!
