### ISSUE TITLE
Modifying fromState in a plugin/middleware

### ISSUE THREAD

**Issue by simply-jos** [router5/router5#204]
I'm trying to add the ability to restore the old scroll position when the route changes, so this would be very useful. I'd store the scroll position in the previous state when the middleware's event handler fires, and restore it. However, it looks like fromState is immutable.

**Comment by troch** [comment]
You can call `done()` with a new state

**Comment by simply-jos** [comment]
That will modify toState, not fromState, though.

**Comment by troch** [comment]
Oh sorry I misread you. So you are expecting `fromState` to contain a scroll position value you have set before?

**Comment by simply-jos** [comment]
Yeah, exactly. I'd prefer to be able to do it in the router's navigation hooks so it cover's all cases-- such as when a user presses back or forward on the browser.

**Comment by troch** [comment]
Is the problem specifically with browsing using back / forward, or for any transition?

**Comment by simply-jos** [comment]
It should only restore the scrollbar position when you hit back or forward, yeah.

But I need to hook every navigation function so I can store the scrollbar position.

**Comment by troch** [comment]
Right, the issue is that the full state is not saved in history (because of possible non-serialisable values). It's best to save the scrolling position using your own container rather than using states: each state has an ID (in meta) that you can use for identifying them.

**Comment by simply-jos** [comment]
> each state has an ID (in meta) that you can use for identifying them.

That sounds perfect, thanks!

**Comment by simply-jos** [comment]
For anyone wondering, here's a really basic example:

```const scrollStateMap = {};
const element = document.getElementById('root');

const restoreScrollPlugin = (router) => {
  return {
    onTransitionStart: (toState, fromState) => {
      // Save the scroll state
      if (fromState && fromState.meta)
        scrollStateMap[fromState.meta.id] = element.scrollTop;
    },

    onTransitionSuccess: (toState, fromState, opts) => {
      // Restore the scroll state, or if we don't have a stored
      // scroll state, scroll to the top of the page
      if (toState && toState.meta && scrollStateMap[toState.meta.id])
        element.scrollTop = scrollStateMap[toState.meta.id];
      else
        element.scrollTop = 0;
    }
  };
};

export default restoreScrollPlugin;```
