### ISSUE TITLE
Provide TypeScript definitions for all packages

### ISSUE THREAD

**Issue by jkelin** [router5/router5#206]
`router5` package has `index.d.ts` TS definitions, however other packages (like `react-router5` and `redux-router5`) do not. It would be great if all packages had TS definitions.

https://github.com/router5/router5/pull/198 seems like a great example of what needs to be done.

I can work on this.

Package list:

- [ ] deku-router5
- [x] react-router5 (https://github.com/router5/router5/pull/209)
- [x] redux-router5 (https://github.com/router5/router5/pull/210)
- [x] router5-helpers
- [x] router5-transition-path
- [x] router5
- [x] rxjs-router5
- [ ] xstream-router5

**Comment by troch** [comment]
> I can work on this.

Yes please. I don't use TypeScript, and rely on others for creating and maintaining type definitions :)

**Comment by jkelin** [comment]
OK I have submitted PRs for react and redux (#209 and #210), which is what I need for my current project. It is unlikely that I will make typings for more packages, however I suggest keeping this issue open in case anyone else is looking for types.
