### ISSUE TITLE
Requiring from /modules instead of /dist for two dependencies

### ISSUE THREAD

**Issue by aksel** [router5/router5#216]
We use a Webpack DLL plugin to build dependencies. It fails in two places, because of the spread operator:

[route-node](https://github.com/troch/route-node/blob/master/modules/RouteNode.js#L158)

[path-parser](https://github.com/troch/path-parser/blob/master/modules/Path.js#L195)

It seems that, instead of being imported from /dist, RouteNode and Path are imported from /modules. I cannot seem to find where this happens.

Fixed it locally by including some babel-loader plugins for spread operators.

Ps. really digging route5 so far! Great work. react-router v4 is a mess, and v3 is misusing session storage to the point of exceptions. Very nice alternative so far 😄

**Comment by troch** [comment]
Hey @aksel, I think the issue has to do with `jsnext:main` pointing to the `modules` directory rather than a compiled version with ES2015 import and export statements. Will fix later today.

Thanks for your kind words 👍

**Comment by troch** [comment]
It has been fixed
