### ISSUE TITLE
Including additional data in navigate

### ISSUE THREAD

**Issue by aksel** [router5/router5#217]
I think this is partially related to #135 , but I'm not sure.

I would like to pass additional (serializable) data to the navigate function, but I don't want it to show up in the browser URL. Specifically, I want to pass data to the toState object.

As an example, [I have a route with async data, that is fetched via middleware](https://router5.github.io/docs/async-data.html). A component is rendered using this data. When I click on the component, I would like to navigate to a different route, that uses the same asynchronously fetched data as the previous route.

Instead of re-fetching the data, I would like to pass the already fetched data to the next route, via the toState object.

It seems to me, that I am currently only able to pass stuff to toState via the params object.

[react-router has this functionality, in the form of the location descriptor object and its state key.](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/location.md#location).

An example React component:
```
// react-router
<Link to={{ pathname: '/foo', state: { some: { thing: ['foo', 'bar', 'baz'] } } }} />
// accessible via this.props.location.state.some

// hypothetical react-router5 equivalent
<BaseLink routeName="foo" routeData={{ some: { thing: ['foo', 'bar', 'baz'] } }} />
// accessible via toState.data.some, or later route.data.some
```
Thoughts? Do you think this is way too much coupling between view and router?

**Comment by troch** [comment]
Hi @aksel. This is currently possible, but only if you are in strict query parameters mode (in non-strict mode, any additional parameter will be added to the query string).

I get the point of wanting to pass parameters which wouldn't appear in the URL. I'm not opposed to the idea if a good API can be proposed (which would work with strict and non-strict mode), but I can't think of a good one just now.

**Comment by aksel** [comment]
Thanks! Strict mode does indeed work.

I might make a pull request for an additional data parameter in the future, if time allows :)

**Comment by troch** [comment]
The down side of strict mode is that path with extra parameters won't match. I'm thinking of changing its behaviour to match when extra params but to strip unwanted parameters from the URL.

**Comment by ibc** [comment]
> only if you are in strict query parameters mode (in non-strict mode, any additional parameter will be added to the query string).

So, when the doc talks about "query parameters" it does not mean the **real** URL query parameters, but the custom like-query parameters managed by `router5` (in the browser plugin) after the URL fragment/hash component (`#`), right?

I think the documentation should clearly explain that.

**Comment by troch** [comment]
v6 has a new option for query parameters called `queryParamsMode` which replaces `strictQueryParams`. With its default value, extra query parameters are matched, but they don't appear in the URL when navigating (stripped when matching).
