### ISSUE TITLE
"Route not found" event

### ISSUE THREAD

**Issue by ivan-kleshnin** [router5/router5#22]
Suppose we're on the page `/about` which is not declared in the routes.
We want to display "page-not-found" widget (component) in this case.
We add listeners but router is silent if no routes matched. Why?

Shouldn't it raise an event with some special `toState` or `toState == undefined` right after `router.start()` to notify about this case? I was pretty sure **Not found** is the same valid and crucial information as **Found** to listen to. Did I miss something in the docs?

**Comment by ivan-kleshnin** [comment]
Oops, I see it's even stranger.

> Invoking the .start([startPathOrState ,] done) function will:
> Navigate to the default route if the current URL does not match an existing route

First. It's not documented how `startPathOrState` variable should affect.
Ok, let's skip this for a moment.

I have this code:
```js
import {Router5} from "router5";

let router = new Router5(undefined, {
  useHash: false,        // prepend hash to route paths
  defaultRoute: "ginger",  // default route
});

router
  .addNode("home"       , "/")
  .addNode("ginger"     , "/ginger");

router.addListener(handleAll);

function handleAll(toState, fromState) {
  console.log("handleAll()");
  console.log("toState:", toState);
  console.log("fromState:", fromState);
}
router.start();
```

And what this code does at access to "http://localhost:3000/sdfdsf"?
It redirects me to "http://localhost:3000/sdfdsf/ginger"???

Expected (at least to me) behavior would be to raise "Not found" event. 
But ok, even following docs, why not "http://localhost:3000/ginger"?

**Comment by troch** [comment]
For not found: http://router5.github.io/docs/transition.html

> Error: .onTransitionError(cb), .offTransitionError(cb)
Listeners are of the following form: function (toState, fromState) { }. Transition error listeners are called with an extra err argument.

**Comment by troch** [comment]
`http://localhost:3000/sdfdsf` => `http://localhost:3000/sdfdsf/ginger`

Well it is not really a bug, but it could definitely be improved. So far the router assumes that if you managed to load `http://localhost:3000/sdfdsf`, then `/sdfdsf` might be your base path.

**Comment by ivan-kleshnin** [comment]
@troch if we access "/sdfdsfsdf" onTransitionError is not invoked. I don't think it's right.

Next I try:

```js
function handleErrors(err) {
  console.log("error:", err);
}
router.onTransitionError(handleErrors);
router.navigate("dfdf");
```

`handleErrors` is still not called.

**Comment by troch** [comment]
`function handleErrors(toState, fromState, err) {
  console.log("error:", err);
}`

**Comment by troch** [comment]
I know why it is not called, needs to be fixed

**Comment by troch** [comment]
Thanks for raising those issues :+1: , a few points have been improved with 0.6.0 (just released).

**Comment by troch** [comment]
Oops didn't mean to reopen

**Comment by ivan-kleshnin** [comment]
@troch, thank you for this project! I really appreciate your work.

**Comment by troch** [comment]
Thanks for your kind words!
