### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by faergeek** [router5/router5#221]
I would like this project to have prettier setup, so everybody who contributes (including myself, of course) can think less about formatting as it will be an automatic process. Should I set it up?

It's really a thing without which I can't imaging my work anymore :-)

It can format at least JSON, JavaScript, TypeScript.

You can read more about it here https://prettier.io/

**Comment by troch** [comment]
It already has prettier 😄

**Comment by faergeek** [comment]
Oh, sorry, I didn't notice, I was looking for `.prettierrc` (yes, prettier now have config :-)). May be we can move configuration to file so tools like IDEs/editors integrate seamlessly?

**Comment by troch** [comment]
Yes 👍
