### ISSUE TITLE
Consider adding React topic (or mention React in description)

### ISSUE THREAD

**Issue by gazedash** [router5/router5#228]
I was searching for an alternative for react-router, and couldn’t find anything.
I found this router only by suggestion (it doesn’t appear in search for ‘React router’).
I like it and its api.
Until now it seemed to me that there is only one React router which api I do not like.
But it is not the case.
So I suggest you make this library more discoverable for React users by adding React topic for this repository and mention React in description.

**Comment by amok** [comment]
I would also suggest to add router5 to https://github.com/enaqx/awesome-react and https://redux.js.org/docs/advanced/

**Comment by wrightm** [comment]
Added issue to add to awesome list https://github.com/enaqx/awesome-react/issues/795

**Comment by ematipico** [comment]
Well this router it's not exactly **for** React... isn't it an agnostic router?

**Comment by troch** [comment]
It is view agnostic but is mainly used with React, and I agree it is worth letting know more React developers that there are alternatives to react-router.

**Comment by wrightm** [comment]
added PR https://github.com/enaqx/awesome-react/pull/798
