### ISSUE TITLE
Initial URL query params are later copied after /#NAME

### ISSUE THREAD

**Issue by ibc** [router5/router5#229]
I'm just starting with router5 so sorry for the lack of knowledge. However I realized of something a bit strange when testing my first app with router5 + react-router5 + redux-react:

My web app is opened with some query params, something like:

```
https://mydomain.org/?foo=FOO&bar=BAR
```

I've configured router5 with two routes ("access", the default one, and "room"). Once the site is loaded, the URL becomes:

```
https://mydomain.org/?foo=FOO&bar=BAR#/access
```

OK, it makes sense. In the `router` section in my redux `store` I see that `params` is an empty Object.

Later I rewrite the URL by replacing `#/access` with `/#room` and press `Enter`. The URL becomes:

```
https://mydomain.org/?foo=FOO&bar=BAR#/room?foo=FOO&bar=BAR
```

which looks ugly to me. Now `params` are `{ foo: "FOO", bar: "BAR" }`.

So, how does router5 (the browser plugin) handle query params present in the initial URL? When do those URL query params become "rare" params after the URL hash/fragment component (`#`)?

And how should I handle those initial query params? Should I read them and delete them (via `window.history.pushState()` before starting my `router`?

**Comment by troch** [comment]
Hi @ibc, I think it is an issue with the history plugin, query params should be removed and added after the hash initially.

**Comment by ibc** [comment]
Why should them be removed initially? I may need them in case I reload the page (my web server may need them). 

In the other side, why should the query params become "hash params"?

**Comment by troch** [comment]
If you are after that behaviour, then don't use the hash: using a hash is a work around when you don't have access to a server (or can't configure it).

However the current behaviour can be fixed.

**Comment by ibc** [comment]
Yes, I can live without relying on real URL query params (it was just a question).

So, which would be the expected behaviour when opening `http://foo.com/?foo=123/#/?bar=456`?
Should router5 rewrite it into `http://foo.com/#/?foo=123&bar=456` so both `foo` and `bar` become router5 state params?

**Comment by troch** [comment]
I think this was fixed (before v6)
