### ISSUE TITLE
Document `startPathOrState` variable

### ISSUE THREAD

**Issue by ivan-kleshnin** [router5/router5#23]
http://router5.github.io/docs/navigation.html

> Invoking the .start([startPathOrState ,] done) function will:
> Navigate to the default route if the current URL does not match an existing route, or if the matched route cannot be activated
> Start listening to popstate events (triggered by back and forward buttons, and a manual change in the URL bar)
> Enable navigation

What does `startPathOrState` change in this description?

**Comment by troch** [comment]
Raise [here](/router5/router5.github.io/issues)
