### ISSUE TITLE
When using 'forwardTo' in route it is not possible to pass params

### ISSUE THREAD

**Issue by thupi** [router5/router5#234]
When using forwardTo in route which as far as i know takes a route name i cant pass paramteres.

Is there any other more powerfull redirecting methods?

Maybe forwardTo  could take a function which passes all the required data in order to proberly handle a redirection with params :-)?

**Comment by aksel** [comment]
I'm not sure you can do forwardTo with route params, but I agree that a callback similar to canActivate would be a good idea.

Alternatively, you can use canActivate to redirect with params. Although the router will interpret this as a transition error, it does redirect with parameters.
```javascript
[
  {
    path: '/hello',
    name: 'redirect',
    canActivate: () => (toSate, fromState, done) => done({ redirect: { name: 'route', params: { hello: 'world' } } }),
  },
  {
    path: '/route?hello',
    name: 'route',
  }
]
```

**Comment by thupi** [comment]
@aksel Thanks for the tip :-) 

I that might be my workaround for now :-) !

**Comment by troch** [comment]
@thupi `.forwardTo()` is a configuration method. When you navigate to `A` and forward to `B`, any parameters passed to `A` are passed to `B`.

**Comment by thupi** [comment]
Sry fo the late response :-) It must have been lost in my inbox... :-) I will definitely give this a shot soon :-)

Thanks :-) ?
