### ISSUE TITLE
Data loading hooks outside of components

### ISSUE THREAD

**Issue by nareshbhatia** [router5/router5#235]
The React example shows loading of data in the component: https://github.com/router5/router5/blob/master/packages/examples/apps/react/components/Inbox.js#L12. I would like my components to not know about data fetching. Is there an example of this? Ideally the data should be loaded when the route changes and before the component is instantiated.

**Comment by aksel** [comment]
[Here's an example from the docs](https://router5.github.io/docs/async-data.html)

It shows how you can resolve promises when routes are activated, using middleware.

**Comment by nareshbhatia** [comment]
Thanks so much, @aksel. Quick followup question - in the docs primarily use `onActivate()` whereas your example uses `loadComponent()`. Just wanted to make sure I understand the difference. I assume `onActivate()` is more generic and can do anything on route changes, whereas `loadComponent()` is used specifically to dynamically load components on routes changes. Is this correct?

**Comment by nareshbhatia** [comment]
Closing this now. I was able to follow the documentation and understand how onActivate() works. Thanks again, @aksel.

**Comment by aksel** [comment]
In my example, the data loading function is called prefetch, not onActivate.
In my opinion, onActivate is too generic a name to use for async data loading. Though that might just be me, and maybe prefetch is not so good a name either! 😅 

Regarding loadComponent, you are correct, it dynamically loads components, for when they are needed.

Each function is called by its own middleware.
The naming of these functions is entirely up to you. You just have to make sure the middleware you write calls the functions

**Comment by nareshbhatia** [comment]
Aha, now it makes more sense :-). I would not have looked for that name! Thanks for the clarification.
