### ISSUE TITLE
route.params not changing after a successful transition

### ISSUE THREAD

**Issue by nareshbhatia** [router5/router5#236]
I am trying out my first app using router5. So far so good, I am able to get most of the stuff working, but stuck on one issue - I have a `BookPage` with two tabs - `summary` and `reviews`. The page is initialized with the summary tab. However, when I click on the reviews tab, `route.params.tab` still has the value `summary`. The transition has completed successfully as seen below. However `console.log()` from the BookPage still says `tab: summary`.

![image](https://user-images.githubusercontent.com/1220198/34075925-22880ac6-e2a4-11e7-814c-0f52665ee472.png)

Here's the code for my BookPage

```
import React from 'react';
import PropTypes from 'prop-types';
import { routeNode } from 'react-router5'

class BookPage extends React.Component {
    static contextTypes = {
        router: PropTypes.object.isRequired
    };

    constructor(props, context) {
        super(props, context);
        this.router = context.router;
    }

    render() {
        const { route } = this.props;
        const { tab } = route.params;
        console.log('tab:', tab);

        return (
            <div>
                <div>
                    <button onClick={this.handleTab1Click}>
                        Summary
                    </button>
                    <button onClick={this.handleTab2Click}>
                        Reviews
                    </button>
                </div>

                {tab === 'summary' && 'Summary'}
                {tab === 'reviews' && 'Reviews'}
            </div>
        );
    }

    handleTab1Click = () => {
        const { route } = this.props;
        const { bookId } = route.params;
        this.router.navigate('book', { bookId: bookId, tab: 'summary' })
    };

    handleTab2Click = () => {
        const { route } = this.props;
        const { bookId } = route.params;
        this.router.navigate('book', { bookId: bookId, tab: 'reviews' })
    };
}

export default routeNode('book')(BookPage)
```

What am I missing?

Thanks in advance.

**Comment by nareshbhatia** [comment]
Digging into this further, it appears that the `route` supplied by `routeNode()` is not the router's state. It is probably just the route from the routes tree. If I switch to using the router state as follows, I do get the right params:

    const routerState = this.router.getState();

Can someone please confirm if this is the right way to get the current params? If yes, what is the usefulness of the `routeNode` HOC?

**Comment by troch** [comment]
> Digging into this further, it appears that the route supplied by routeNode() is not the router's state

Exactly, `routeNode` is to link a route node to the router: in your case, the `book` route is rendered by its parent node (which in router5 is called the unnamed root node: `routeNode('')`).

For any route change you can use `withRoute`, `routeNode` is an optimized version which will only re-render if it is concerned by a route change. Read this for more in-depth explanations: http://router5.github.io/docs/understanding-router5.html

**Comment by nareshbhatia** [comment]
Thanks @troch. Much clearer now and I got it working with `withRoute`.
