### ISSUE TITLE
How to navigate to same route with different parameters? [Question]

### ISSUE THREAD

**Issue by todorpr** [router5/router5#239]
Sorry to ask here, but couldn't find a better place... I would like to navigate from url:
```
www.domain.com/some-path?pages=page1:23
```
to:
```
www.domain.com/some-path?pages=page1:24
```

How can I do this? With `router.navigate('name')` is possible to navigate to another route, but what is the best approach when just params are slightly different?

**Comment by aksel** [comment]
One way, is you can spread the current params, replacing the param you want to replace.

To navigate from ```www.example.org/route?foo=bar&hello=world``` to ```www.example.org/route?foo=bar&hello=different```

you can do: ```router.navigate(route.name, { ...route.params, hello: 'different' });```

**Comment by troch** [comment]
@todorpr: as @aksel mentioned, you need to explicitly pass all parameters.
