### ISSUE TITLE
Forward button broken again?

### ISSUE THREAD

**Issue by Gekkio** [router5/router5#24]
It looks like issue #11 is back (at least on Chrome 44 and Firefox 40). When pressing the back button, I can see the forward button change quickly from enabled to disabled, and in practice it is never usable.

Router5 0.4.3 seems to be fine, but the problem has reappeared in 0.5.0. Verified on "Router5 with React" example, so the problem seems to be in the library.

**Comment by vojtech-dobes** [comment]
Truly looks that way, I was preparing to report this as well.

**Comment by troch** [comment]
Committing a fix right now. Bad bug, I need to look at my linter options (should have been picked up)

**Comment by vojtech-dobes** [comment]
:+1:

**Comment by troch** [comment]
Fixed in 0.6.1

**Comment by Gekkio** [comment]
Thanks for the very quick response :)

**Comment by teohhanhui** [comment]
Having the same problem in 0.9.2

**Comment by troch** [comment]
Actually broken since 0.8.0, fixed again... :bug:
