### ISSUE TITLE
Adding data to state loses params

### ISSUE THREAD

**Issue by Lapixx** [router5/router5#242]
I'm trying to add additional data to my routerState, and according to [the example in the middleware docs](http://router5.github.io/docs/middleware.html#adding-data-to-state), the following should work:

```js
const attachDataMiddleware = router => (toState, fromState) => {
  return {
    ...toState,
    hello: 'World'
  }
}
```

However, when doing this, I'm getting an error on navigating: `Uncaught TypeError: Cannot read property 'params' of null`.

I noticed that mutating the `toState` object directly *does* work without issues:
```js
const attachDataMiddleware = router => (toState, fromState) => {
  toState.hello = 'World'
  return true
}
```

Which is an alright workaround for now but is not a really clean solution (especially when trying to merge the `toState` with another object).

**Comment by troch** [comment]
```js
const attachDataMiddleware = router => (toState, fromState) => {
  return {
    ...toState,
    hello: 'World'
  }
}
```

Should be

```js
const attachDataMiddleware = router => (toState, fromState, done) => {
  done({
    ...toState,
    hello: 'World'
  })
}
```

**Comment by Lapixx** [comment]
I guess I indeed wrongly assumed that the behaviour would be the same for synchronous middleware.

However, the change you suggested (using `done()`) does not result in the state being extended (although it doesn't result in an error either -- looks like it's just ignored).

I tried to do it like this (closer to the example), but that gives me the same problem as before (`params` missing from the state):

```js
const attachDataMiddleware = router => (toState, fromState) => {
  return Promise.resolve({
    ...toState,
    hello: 'World'
  })
}
```

**Comment by Lapixx** [comment]
That makes sense, indeed. Would you be open to support this for synchronous code as well? i.e returning the updated state or throwing and Error.

It feels a bit awkward to have to make the code asynchronous for these cases.

**Comment by Lapixx** [comment]
Then it’s good to note that the example from the docs is incorrect :)

As for my other question: would it be possible to support (or are you open to a PR to add this) this in a synchronous way, without using Promises or callbacks?

**Comment by troch** [comment]
In a synchronous way, I don't think it would be a breaking change, and I would be open to a PR.

**Comment by troch** [comment]
The promise way should work actually, I have checked. So the docs are correct.

The following should work:

```
const attachDataMiddleware = router => (toState, fromState) => {
  return Promise.resolve({
    ...toState,
    hello: 'World'
  })
}
```

Do you have other middleware functions registered which could have interfered?
