### ISSUE TITLE
How to use forwardTo with parameters?

### ISSUE THREAD

**Issue by ibc** [router5/router5#243]
Basically I want to automatically forward this route:

`/channel/:channel_id/`

to this one:

`/:client_id/channel/:channel_id/`

But, since the first route does not specify any `client_id`, I want to use a default value of "foo".

This is what I have but obviously does not work:

```js
const router = createRouter(
	// routes
	[
		{
			name : 'channel',
			path : '/:client_id/channel/:channel_id/'
		},
		{
			name      : 'channel_old_api',
			path      : '/channel/:channel_id/',
			forwardTo : 'channel'
		}
	],
	// options
	{
		defaultRoute  : 'channel',
		defaultParams :
		{
			client_id  : 'foo',
			channel_id : 'lalala'
		},
		trailingSlash     : true,
		strictQueryParams : false
	});
```

If I open the browser in `https://localhost/#/channel/alpha/` it fails with:

```
Uncaught Error: Cannot build path: '/:client_id/meet/:channel_id/' requires missing parameters { client_id }
```

Is there any way to use `forwardTo` with extra default parameters? Something like:

```js
{
	name          : 'channel_old_api',
	path          : '/channel/:channel_id/',
	forwardTo     : 'channel',
	forwardParams : { client_id: 'foo' }
}
```

Thanks a lot.

**Comment by troch** [comment]
`defaultParams` is not supported per route, but I'm in the middle of adding them

**Comment by ibc** [comment]
Good to know. Thanks.
May you close this issue once implemented?

**Comment by troch** [comment]
Will do! The PR is ready: #244, will probably release tomorrow or friday

**Comment by ibc** [comment]
Wow!

**Comment by LeonardoGentile** [comment]
Thanks @troch, any chance you could also update the docs about this? 👍

**Comment by troch** [comment]
Yeah sure, the docs will be updated before release

**Comment by troch** [comment]
Released

**Comment by ibc** [comment]
Great! Thanks
