### ISSUE TITLE
Go back/forward

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#246]
Hi, sorry if there is a doc for it, but I could not find a way to go back/forward in history using router5.
I don't wan't to use browser history api because going back that way can lead to transitioning away from current website. Would be great if router5 have feature to go back/forward if there is previous/future state.

**Comment by troch** [comment]
It would need to be implemented in the browser plugin. The difficulty is to keep a parallel version of the history, while not knowing if a user pressed the back or forward button on a `popstate` event and having little information about the browser history itself. That said, now that I have an unique ID per state, it could be guessed what triggered a `popstate`.

I've not attempted it, so not sure what caveats there are.
