### ISSUE TITLE
How to keep params when using actions.navigateTo(routeName)?

### ISSUE THREAD

**Issue by ibc** [router5/router5#247]
I use router5 with redux and the browser plugin. I want to use the `routeNodeSelector` feature (or maybe `actions.navigateTo()` directly). And I want to keep the original route query params when changing the route using that router5 API.

For example, my web app is opened with this URL:

`https://mydomain/#/foo/?port=1234?debug=true`

Then I want to use `navigateTo('bar') (or the same using `routeNodeSelector`) and get this URL:

`https://mydomain/#/bar/?port=1234?debug=true`

but it gives me this:

`https://mydomain/#/foo`

Yes, using `navigateTo` I can take the current route params and use them as follows:

```js
dispatch(actions.navigateTo('bar', route.params));
```

Is there any way to avoid such a hack and just keep the existing URL params?

**Comment by troch** [comment]
There is a plugin called `persistentParams`.
