### ISSUE TITLE
trailingSlash: true does not work if there are query params

### ISSUE THREAD

**Issue by ibc** [router5/router5#248]
I'm having many issues with router5 when I use URLs with "query" parameters (not real URL query params, but those params after "?" after the URL fragment "#").

My routes:

```js
{
  name : "foo",
  path  : "/:companyId"
}
```

Router options:

```js
{
  trailingSlash : true,
  strictQueryParams : false
}
```

Then let's open the web app directly with the following URLs:

#### `https://localhost/#/microsoft`

* It matches the `foo` route.

#### `https://localhost/#/microsoft/`

* It matches the `foo` route and rewrites the URL to `https://localhost/#/microsoft`.

#### `https://localhost/#/microsoft?qwe=123`

* It matches the `foo` route.

#### `https://localhost/#/microsoft/?qwe=123`

* It does **NOT** match the `foo` route.

I've also tried adding "/" to the `path` in the `foo` route and also `trailingSlash:false`. Nothing works.

Do I miss something? or is it just that router5 does not properly behave when there are "extra query params" in the initial URL?

**Comment by ibc** [comment]
Now the same with `useTrailingSlash: true`:

#### `https://localhost/#/microsoft`

* It matches the `foo` route and rewrites the URL to `https://localhost/#/microsoft/`.


#### `https://localhost/#/microsoft/`

* It matches the `foo` route.


#### `https://localhost/#/microsoft?qwe=123`

* It matches the `foo` route and rewrites the URL to `https://localhost/#/microsoft/?qwe=123`.

#### `https://localhost/#/microsoft/?qwe=123`

* It does **NOT** match the `foo` route. THIS IS NOT GOOD!!!

This is, how is it possible that it matches `https://localhost/#/microsoft?qwe=123` and rewrites it to `https://localhost/#/microsoft/?qwe=123`, but it does match ``https://localhost/#/microsoft/?qwe=123` if that is the original URL?

This must be a bug.

**Comment by ibc** [comment]
Things are even worse if `useHash: false` in the browser plugin. If the initial URL has real query params (`?foo=bar`) no route is matched at all, no matter which the value of `trailingSlash`, `useTrailingSlash` or `strictQueryParams` are.

May I know please whether this is supposed to work or not? I just wouldn't like to spend more time on this if this is not even supposed to work. Thanks.

**Comment by ibc** [comment]
OK, now I'm **pretty sure** that `strictQueryParams: true` is ignored for the original URL of the web page.

I've added some query params to the route (`path: '/:company?foo') and then opened the web with those exact query params. It matches the route. But if I add any extra query param (`/google?foo=bar&baz=123`) then the route **IS NOT** matched.

However, if later I run `router.matchPath('/google?foo=bar&baz=123')` then it matches the route.

**Comment by ibc** [comment]
@troch any comment, please?

**Comment by troch** [comment]
I'm going to have a look.

**Comment by ibc** [comment]
Humm, something may have changed. I'm trying adding the final slash to the routes' `path`:

routes:
```js
[
  {
    name     : 'join',
    path     : '/:organizationId/:roomId/' // NOTE the final "/"
  }
]
```

options:
```js
trailingSlash     : true,
useTrailingSlash  : true,
strictQueryParams : false

// in browserPlugin:
useHash : false
```

Then if I directly open these URLs this happens:

#### https://localhost/Microsoft/Test

* The "join" route is matched.
* Location is rewritten to `https://localhost/Microsoft/Test/`.
* OK

#### https://localhost/Microsoft/Test/

* The "join" route is matched.
* OK

#### https://localhost/Microsoft/Test?qwe=123

* The "join" route is matched.
* Location is rewritten to `https://localhost/Microsoft/Test/?qwe=123`.
* Route params include `qwe: 123`.
* OK

#### https://localhost/Microsoft/Test/?qwe=123

* The "join" route is matched.
* Route params include `qwe: 123`.
* OK


So it seems it works fine.

**HOWEVER:** If I remove the final slash from routes' `path` (and set `trailingSlash` and `useTrailingSlash` to false) the above URLs do NOT work. If the initial URL contains query params the "join" route is NOT matched.

**Comment by troch** [comment]
So I'm not sure what's wrong, but you should avoid adding adding a trailing slash to path definitions. If you want to enforce trailing slashes, you simply need to set `useTrailingSlash` to `true`. `trailingSlash` option is set to `true` as a result (and you shouldn't change it to `false`).

- Avoid defining paths

**Comment by ibc** [comment]
Hi, I do know that I shouldn't add slashes in the `path` and I know how `trailingSlash` and `useTrailingSlash` work. The problem (as explained above) is that router5 fails to process the initial URL of the web app. So my combination of `trailingSlash`, `path` with "/", etc is just an ugly workaround that I've found to make it work, just that.

In similar reported issues (such as #114) I see that you test the behavior via [router.matchPath()](https://github.com/router5/router5/issues/114#issuecomment-280921029) API, and it works that way. Yes, it works that way. Again, the problem is that router5 does not behave the same way when it comes to process the initial URL that started the web application.

I will try to provide a simple code snippet that reproduces the problem so you can see the problem.

**Comment by ibc** [comment]
I hope this clearly shows the problem:

https://github.com/ibc/router5-url-issue

**Comment by ibc** [comment]
Hi @troch, can you please confirm whether you will be able to check my demo project demonstrating the issue? I'm just living with many ugly hacks for now (such as adding or removing final slash before the query params in the original URL before starting `router5`) but I hope I'll no longer need them in the future.

**Comment by troch** [comment]
I've not had the time to have a look, but thank you for sending the link!

**Comment by ibc** [comment]
Just wondering if `router5` 5.8.3 or it's updated dependency `route-node` 5.0.3 is related to this issue :)

**Comment by ibc** [comment]
Thanks, do not worry and also enjoy your holiday ;)

**Comment by ibc** [comment]
Friendly ping :)

**Comment by troch** [comment]
@ibc I've been refactoring route-node, and didn't manage to reproduce with the refactor. I'm less than a week away from releasing v6 of router5, and hopefully those issues should go away.

**Comment by troch** [comment]
It changes the options API. It allows for a more intuitive and flexible configuration, including the serialisation and matching of query parameters. Serialising objects is not planned yet, but with the complete refactor of search-params, it could be added (although objects have a couple of edge cases)

**Comment by ibc** [comment]
Nice, thanks.

**Comment by ibc** [comment]
I'm trying to test router5 v6. However it's not being easy. I cannot just use a Git URL in `package.json` pointing to the "v6" branch because router5 does not have a `preinstall` script in its `package.json`, so the building stuff must be done separately.

Entering into `myapp/node_modules/router5` and running `npm install && npm run bootstrap` does work, but `npm run build` fails:

```
~/tmp/router5-url-issue/node_modules/router5 git:router5-v6▲ $ npm run build

> router5@ build /Users/ibc/tmp/router5-url-issue/node_modules/router5
> node scripts/build && npm run build:umd

Building router5
packages/router5/modules doesn't exist
child_process.js:644
    throw err;
    ^

Error: Command failed: babel packages/router5/modules --out-dir packages/router5/
packages/router5/modules doesn't exist

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at packages.forEach.pkg (/Users/ibc/tmp/router5-url-issue/node_modules/router5/scripts/build.js:23:5)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/ibc/tmp/router5-url-issue/node_modules/router5/scripts/build.js:16:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

This may be due to NPM placing and sharing dependencies on the parent `node_modules` folder and so on, so I did a fresh `git clone` of the v6 branch. Now `npm run build` (after previous npm commands) fails with:

```
> router5@ build:umd /Users/ibc/tmp/router5
> rollup -c rollup.config.js

🚨   Error: 'default' is not exported by packages/router5-transition-path/dist/es/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
packages/redux-router5/modules/lib/routeNodeSelector.js (1:7)
1: import transitionPath from 'router5-transition-path';
          ^
2:
3: function routeNodeSelector(routeNode) {

```

**Comment by troch** [comment]
v6 finally out, thanks for your patience

**Comment by ibc** [comment]
Hi, I've updated my *router5-url-issue* project with router5 6.0.0 and updated the route options to be:

```js
trailingSlashMode : 'default',
queryParamsMode   : 'loose'
```

I've also tried with other values for `trailingSlashMode`. The issue still exists. You can check it by cloning https://github.com/ibc/router5-url-issue and running `gulp live`.

**Comment by ibc** [comment]
Hi, the issue still exists in 6.1.3
