### ISSUE TITLE
Example in docs does not seem to work

### ISSUE THREAD

**Issue by rocketraman** [router5/router5#252]
Looking at this example: http://router5.github.io/docs/with-react.html#/inbox

When one starts to compose, but then clicks another link, one gets an error message as expected. However, if one clicks the back button, there is no error and the compose state is cleared. Based on the text, this seems like a bug?

**Comment by troch** [comment]
Hi @rocketraman, it is expected. The browser plugin has a `forceDeactivate` option. Basically back and forward actions are non cancellable, so the advice is not to try to fight them or your browser history will be messed up.
