### ISSUE TITLE
When a React RouteNode should re-render?

### ISSUE THREAD

**Issue by LeonardoGentile** [router5/router5#254]
Hello @troch!
I'm having a big doubt after a [bug](https://github.com/LeonardoGentile/react-mobx-router5/issues/6) emerged in my react-mobx plugin.

My version of `RouteNode` is based on yours [react-router5 version ](https://github.com/router5/router5/blob/master/packages/react-router5/modules/routeNode.js).

Now I've noticed that in your version whenever a route change happens **all** your RouteNodes will re-render. 
This usually works when your component structure resemble exactly a single tree and of course the visual changes will only happen in the children branches of the intersection RouteNode (because of the `switch` or any other means to select the sub-components).  
Nonetheless all RouteNodes are being re-rendered.

I think that this might be inefficient and I put in place a logic to re-render **only the intersection node**.  In this case when the component structure is a tree it works because all the subcomponent of the intersection are re-generated and so any RouteNode in this branch will be re-generated and will select the correct subcomponents even tough it's not the intersection (this is a render, **not** a re-render).

Now this logic turned to be buggy for some specific cases (example: `app.a({id:1}).b -> app.a({id:2}).c`) so I tough to add an extra condition:

Re-render a RouteNode only when:
 - it represents the intersection node
 - or the **segment** associated with RouteNode is one of the segments [toActivate](https://github.com/router5/router5/blob/master/packages/router5-transition-path/modules/index.js#L74)

I tough preventing re-rendering RouteNodes might be necessary when you have a lot of them and only few of them really need to. Or when your component structure is organized in multiple parallel trees for example.

What do you think?
But most important, am I overcomplicating this and I should just trust React and its internal algorithms?  😆

**Comment by LeonardoGentile** [comment]
Right, sorry I did not look into the listenersPlugin and I wrongly assumed that each route node was listening to just any route changes. 
I'm setting up an example with react-router5 to see if this also affect your package or not.

**Comment by LeonardoGentile** [comment]
@troch take a look here: https://react-x2uirc.stackblitz.io/
I've setup the same example using react-router5.
The routes config:
```
export default [
  {
    name: 'app',
    path: '/',
    children: [
      {
        name: 'page',
        path: 'page/:id',
        children: [
          {
            name: 'article',
            path: '/article'
          },
          {
            name: 'info',
            path: '/info'
          }
        ]
      }
    ]
  }
];
```
If you try to navigate for example from `app.page({id:1}).article` to `app.page({id:1}).info` it works (I'm putting routesParams in parens for explanation only).
  
If you navigate from `app.page({id:1}).article` to `app.page({id:2}).info` it doesn't works.
By passing `{reload:true}` in route options seems to make things worse.

Now, I'm not sure if this is a misconfiguration, a limitation or a bug.

**Comment by troch** [comment]
Can you share the code of your example?

**Comment by LeonardoGentile** [comment]
Oops, I've shared only the view link, here's the edit version: https://stackblitz.com/edit/react-x2uirc/

**Comment by LeonardoGentile** [comment]
Hello @troch have you had by chance the time to look into this ?

**Comment by LeonardoGentile** [comment]
Any update on this @troch? 
What can I do to help you on this? Was my example setup enough to let you understand the problem?

**Comment by troch** [comment]
I guess that makes sense since when nesting `routeNode` HoCs, children route nodes of an updating route node don't get local state updates. I think I need to introduce a key in `routeNode` or other fix.

**Comment by LeonardoGentile** [comment]
@troch I've found a possible fix for my plugin but I'm not sure if it break the original routeNode  responsibility. 

Right now a routeNode should update when this condition is met (pseudo-code taken from mobx-plugin):

```
this.routerStore.intersectionNode === this.nodeName;
```

You do the same using your listener plugin.

A possible fix would be:

```
const isIntersection = this.routerStore.intersectionNode === this.nodeName;
const nodeToActivate = this.routerStore.toActivate.find((item, index, array) => {
  return item === this.nodeName
});
return isIntersection || nodeToActivate
```

That is a routeNode should update **either** when it is the intersection node **or** it is one of the node to activate.

What do you think?

If the logic is correct you could be apply it also on your side

**Comment by troch** [comment]
> That is a routeNode should update either when it is the intersection node or it is one of the node to activate.

I think I can refine it. It will reload if:
- If it is the intersection node
- Going from the intersection node to leaves, any activated node which has a matching deactivated node, until not (it makes sense in my head anyway).

**Comment by troch** [comment]
OK, change is live:
- react-router5@6.0.0
- router5@6.1.0

Note that there is a breaking change in react-router5: listeners plugin is no longer needed, and that means upgrading to router5@6.1.0 to use it

**Comment by LeonardoGentile** [comment]
thanks @troch 👍 
Apart from the `shouldUpdateNode` function that's gonna be very useful I've seen you now you use an `observerPlugin` instead of the listenerPlugin, any words on this, either here or in the docs somewhere?

**Comment by troch** [comment]
The router has now a `subscribe` function, and is marked as an observable so it can be consumed easily in stream libraries (http://router5.github.io/docs/observability.html).

I've just released a patch to fix a couple of issues.
