### ISSUE TITLE
Firefox: router can't identify route if it contains | (pipe) char

### ISSUE THREAD

**Issue by todorpr** [router5/router5#262]
Basically Firefox doesn't encode | (pipe) char, actually even if it is already encoded to %7c it decodes it - this way router can't identify the route.

Actually this issue is related to `route-node` [https://github.com/troch/route-node/issues/19](https://github.com/troch/route-node/issues/19) but wanted to point it out here, as it bugs `router5` in some way.

**Comment by troch** [comment]
Fixed in route-node v3.0.3
