### ISSUE TITLE
Previus node using redux

### ISSUE THREAD

**Issue by karimone** [router5/router5#263]
I'm trying to use router5, but I found very hard understand the documentation maybe because there is no reference at all but just a demo.

So I discovered the actions.navigateTo here: https://github.com/router5/router5/blob/master/packages/examples/apps/react-redux/components/Nav.js

Is there any way to get an action or maybe through the router to have a goToPreviousNode using redux?

**Comment by troch** [comment]
For redux-router5, documentation is visible here:
https://github.com/router5/router5/tree/master/packages/redux-router5 or https://www.npmjs.com/package/redux-router5

There is no redux action to go back to the previous route, or no router method to call. It depends what you mean by going "back": window.history.back() or navigating to a new route which is the previous route.
