### ISSUE TITLE
Question: isActive but ignore params

### ISSUE THREAD

**Issue by jacobweber** [router5/router5#266]
To use `isActive`, I have to specify values for path parameters, or it will return false. But what if I want to find out whether a route is active regardless of the params? Is that possible?

For example, if I have a route `{name: 'userDetail', path: '/user/:id'}`, then `isActive('userDetail')` returns false when I'm on the URL `/user/123`.

(Apologies if this isn't the right place to ask questions.)

**Comment by troch** [comment]
In that case you might not need `isActive` and instead do `router.getState().name === 'userDetail'`?

**Comment by jacobweber** [comment]
That'll work -- thanks for the quick reply!
