### ISSUE TITLE
Query string is being stripped since router5@6.1.2

### ISSUE THREAD

**Issue by todorpr** [router5/router5#276]
Just updated to the latest `router5@6.1.2` and realized that the query string is being stripped.

For example if path is `/one-two?start=22` it becomes just `/one-two`

Demo url: https://nr0742q7v4.codesandbox.io/one-two?start=22

The issue doesn't exist with `router5@5.8.3`

**Comment by troch** [comment]
Hey @todorpr, read breaking changes https://github.com/router5/router5/blob/master/CHANGELOG.md#breaking-changes-1, especially the new option called `queryParamsMode`.

**Comment by todorpr** [comment]
Ah, I see. Sorry for bothering you, @troch!
