### ISSUE TITLE
Take the Router Challenge

### ISSUE THREAD

**Issue by grahammendick** [router5/router5#278]
[The Router Challenge](https://github.com/grahammendick/router-challenge) aims to be to Routers what TodoMVC is to MV* frameworks. It offers the same Music Catalog application built in React using different Routers. For it to be successful I need the help of Router writers like you. Will you [take the Router Challenge](https://github.com/grahammendick/router-challenge/blob/master/CONTRIBUTING.md) and implement the Music Catalog application using router5, please?

**Comment by troch** [comment]
I don't have the time right now. I am working on a new package that I am going to publish soon, in combination with any router would make that challenge a walk in the park. Maybe then 😄

**Comment by troch** [comment]
Nope, it's not, I just don't have a few hours to dedicate to it.
