### ISSUE TITLE
[redux-router5] Consider renaming routeNodeSelector to createRouteNodeSelector

### ISSUE THREAD

**Issue by amok** [router5/router5#287]
Because it's what it (func) does :)

Of course it's just a matter of taste. But it brings a bit more clarity (f.i in react: `componentDidMount` and not just a `didMount` or something)

And again, just for an example, how do I usually use it

```
import { routeNodeSelector as createRouteNodeSelector } from 'redux-router5'

const routeNodeSelector = createRouteNodeSelector('')
const route = routeNodeSelector(state)
...
```

Or it could be named routeNodeSelectorCreator (see https://github.com/reduxjs/reselect#createselectorcreatormemoize-memoizeoptions )

**Comment by troch** [comment]
Yes, I'm going to make that change and push a breaking change

**Comment by amok** [comment]
awesome!  thanks (#292)

**Comment by troch** [comment]
No problem. Version 6.0.0 has been published but I've noticed it hasn't well propagated. Npm seems to have issues.
