### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by jonaskello** [router5/router5#288]
In new versions of router5 we can [subscribe to changes](http://router5.github.io/docs/observability.html). However there seems to be no way to unsubscribe, or at least it is not documented. Perhaps the subscribe() function can return a function that is called to unsubscribe?

**Comment by troch** [comment]
The subscribe function returns an unsubscribe one.

**Comment by jonaskello** [comment]
Aha, good! I'm using typescript and it seems the [typings](https://github.com/router5/router5/blob/master/packages/router5/index.d.ts#L263) does not reflect this:

```ts
 subscribe(cb: SubscribeFn): void
```

 Also I could not find anything about it in the docs.

So maybe this issue could be to update the typescript typings and the docs?

**Comment by jonaskello** [comment]
On a related note, using a plugin to subscribe to changes seem to give you more granular events (started, error etc.). Is there some way to un-use a plugin? I'm looking for the inversion of `router.usePlugin()`, something like `router.removePlugin()`.

**Comment by troch** [comment]
Ah yeah, good catch I will update them. There isn't a way to remove plugins.

**Comment by troch** [comment]
Fixed in 6.2.1
