### ISSUE TITLE
queryParams issues

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#290]
Hi, on the latest router 6.2.1 I found next issues:

1. With this config
```javascript
  queryParams: {
    nullFormat: 'default',
    arrayFormat: 'brackets',
    booleanFormat: 'none',
  },
```
navigating to `true` boolean parameter makes it appear in redux store as boolean `true`, but if reload browser page with the same url, parameter becomes string `'true'`. That breaks check in some my components.

2. With this config
```javascript
    queryParams: {
      nullFormat: 'string',
      arrayFormat: 'brackets',
      booleanFormat: 'empty-true',
    },
```
navigating to `true` boolean parameter makes it appear in redux store as boolean `true`, but if reload browser page parameter is transformed to null, for instance, `?boolparam` is transformed to `?boolparam=null`.
If I set config to hidden null
```javascript
    queryParams: {
      nullFormat: 'hidden',
      arrayFormat: 'brackets',
      booleanFormat: 'empty-true',
    },
```
then after reload, `true` boolean parameter just disappears from url.

Seems like nullFormat check goes first somewhere in router5 code, but probably booleanFormat should go first

**Comment by klimashkin** [comment]
3. With this config
```javascript
  queryParams: {
    nullFormat: 'default',
    arrayFormat: 'brackets',
    booleanFormat: 'unicode',
  },
```
navigating to `true` boolean parameter makes it appear in redux store as boolean `true`, but if reload browser page with the same url, parameter becomes string `'✓'`

**Comment by klimashkin** [comment]
Everything latest
```
"react-router5": "6.0.1",
"redux-router5": "5.5.0",
"router5": "6.2.1",
"router5-transition-path": "5.3.0",
```

**Comment by klimashkin** [comment]
Rest of router config:
```javascript
    autoCleanUp: true,
    allowNotFound: false,
    caseSensitive: false,
    trailingSlashMode: 'never',
    strictTrailingSlash: false,
    queryParamsMode: 'default',
```

And browser plugin config:
```javascript
  router.usePlugin(browserPlugin({
    forceDeactivate: true,
    useHash: true,
    hashPrefix: '',
    base: '',
    mergeState: false,
    preserveHash: false,
  }));
```

**Comment by troch** [comment]
Can you double check the version in `node_modules`? There was a fix in version 6.1.3, and it sounds a bit like what was fixed. If you are on the latest, can you try to reproduce? (there is a stackblitz with redux and react here: https://stackblitz.com/edit/react-redux-router5)

**Comment by klimashkin** [comment]
I created simple example:
https://stackblitz.com/edit/react-redux-router5-sfrf65
If you click on 'Show version info' link, `?showVersion` param is added to the url and everything is fine. But if you reload the page with that url, then it is transformed to `?showVersion=null` and version info can't be shown anymore.

And I checked node_modules, everything is latest:
```
> npm ls router5
└── router5@6.2.2
> npm ls react-router5
└── react-router5@6.0.1
> npm ls redux-router5
└── redux-router5@6.0.0
> npm ls router5-transition-path
├─┬ react-router5@6.0.1
│ └── router5-transition-path@5.3.0  deduped
├─┬ redux-router5@6.0.0
│ └── router5-transition-path@5.3.0  deduped
├─┬ router5@6.2.2
│ └── router5-transition-path@5.3.0  deduped
└── router5-transition-path@5.3.0
```

**Comment by troch** [comment]
I've found the issues and will be updating packages soon.

**Comment by klimashkin** [comment]
Thanks, that works now!
