### ISSUE TITLE
Middleware return type

### ISSUE THREAD

**Issue by dangmai** [router5/router5#298]
Hi, it looks like the return type of Middleware is missing the fact that we can return anything in order to mutate the route state, as seen here: https://github.com/router5/router5/blob/c1c8d93a663f4b1fac8e5d9a39a3d000d03cf221/packages/router5/index.d.ts#L205

I think `boolean | Promise<any> | void` or something more generic would be better, but I don't know enough about the internal of router5 to make a PR for that.

**Comment by troch** [comment]
I've made that change
