### ISSUE TITLE
[typings] shouldn't be logger instead of loggers?

### ISSUE THREAD

**Issue by vaurelios** [router5/router5#299]
Is it a typo [here](https://github.com/router5/router5/blob/c1c8d93a663f4b1fac8e5d9a39a3d000d03cf221/packages/router5/index.d.ts#L416)?
```typescript
declare module 'router5/plugins/loggers' {
```
maybe should be:
```typescript
declare module 'router5/plugins/logger' {
```

typescript compiler complains:
```text
Module not found: Can't resolve 'router5/plugins/loggers' in '...'
```

Changing the [L416](https://github.com/router5/router5/blob/c1c8d93a663f4b1fac8e5d9a39a3d000d03cf221/packages/router5/index.d.ts#L416) and [L31](https://github.com/router5/router5/blob/c1c8d93a663f4b1fac8e5d9a39a3d000d03cf221/packages/router5/index.d.ts#L31) it builds normal.

**Comment by troch** [comment]
Yes it should. Do you mind creating a PR for it?
