### ISSUE TITLE
Meaning of nullFormat: 'hidden'

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#307]
Hi @troch!

I was thinking about `nullFormat: 'hidden'` option and could not come up with real use case.
The main reason of having some state values reflected in url (instead of storing them somewhere in javascript) is to make them restorable between page reloads (and also ability to save url in favorites and to share them with other people), and route library is responsible for managing such state variables.

Option `nullFormat: 'hidden'` violate this basic principle, because `null` as a parameter value can't be restored on page reload. So if I navigate to path with `null` parameter and expect this parameter to be exactly `null` somewhere on the page, it will produce different behavior on spa navigation and on classic navigation/reload.

**Comment by troch** [comment]
`nullFormat` to `'hidden'` is when you want to treat `null` like `undefined`: don't display them. It's there to be used, if someone is after that use case.

> value can't be restored on page reload

If you set `queryParamsMode` to `'default'`, you'll hit scenarios where not all state values are in the URL
