### ISSUE TITLE
Callbacks should reference traversed state

### ISSUE THREAD

**Issue by Kukkimonsuta** [router5/router5#31]
Either as `this` or as an additional parameter (personally I'd prefer additional parameter).

Bonus points for supporting something like `router.addCanActivateListener(canActivate);`

http://jsbin.com/damapi/14/edit?js,console

**Comment by troch** [comment]
Hi @Kukkimonsuta. Thank you for raising an issue. I don't feel this is necessary and this is why: `canActivate` functions are by definition tied to specific route / segments so I wouldn't encourage the use of a generic function. Those functions would be more things like `isLoggedIn`, `isAdmin`, `hasRole(role)`, etc... You ("the developer") tells the router what `canActivate` function is tied to which route, so you don't need the router to tell you what route it is using a `canActivate` function against. If you use the same canActivate function across multiple routes and still need to make decisions base on the traversed route, I would encourage you to use closures.

Your modified jsbin: http://jsbin.com/gijehu/edit?js,console

Can you elaborate more about `router.addCanActivateListener(canActivate);`, I am not sure to understand?

**Comment by Kukkimonsuta** [comment]
Thank you for the swift reply :+1: I understand how this is intended to be used, however my use case isn't that simple - but thinking about it, I'm going at it wrong..

Lets take the example from docs:
![example](http://router5.github.io/img/deactivation-activation-path.png)

The user is on `users.view` and is navigating to `orders.completed`. Now in my case every state has its own view that remains visible until user navigates somewhere else on the same level (for instance `users` is visible on both `users.view` and `users.list`). To achieve such behavior I need an entry point that describes me the whole path when transitioning, so I can adjust views accordingly. The ideal pipeline would be:

1) check whether transition can be made

 - `canDeactivate users.view`
 - `canDeactivate users`
 - `canActivate orders`
 - `canActivate orders.completed`

2) resolve dependencies for new states

- async load data for `order`
- async load data for `order.completed`

3) deactivate / activate states

- hide view `users.view`
- hide view `users`
- display `orders`
- display `orders.completed`

However such pipeline is probably too complex for this router library. Thinking about it what I actually need is just to get list of states being deactivated or activated in the `onTransition` event - is there a built in way to get such information? Would it be possible to expose it to the `onTransition` event so it doesn't have to be recomputed (since at this point the router must already know what states are being activated or deactivated)?



`router.addCanActivateListener(canActivate);` would be just global variation to adding `canActivate` to each route, but without referencing traversed route it doesn't really make sense.. or probably doesn't make sense at all now.

**Comment by troch** [comment]
You perfectly understand the transition phase. This routing library can handle complex asynchronous pipelines without problems.

1) Currently supported

2) As you mentioned it, use of _middleware_ with `onTransition` is how you can handle asynchronous operations and still have control over transition success / failure. Initially I thought about supporting onActivate and onDeactive functions in the transition pipeline, however it would only support data loading in series whereas it is what I criticise other routers for: imposing a control flow on data loading. A middleware gives you a blank slate where you can load data in parallel, in series, the way you want and just callback / return a promise where you are done. If you use promises, you can chain, use Promise.all or mix the two if you implement a data dependency graph (like async.js `.auto()`).

There is an undocumented feature of router5 which is an internal helper exposed as a static method. It is called `transitionPath` and you can use it as follow:

```javascript
const { intersection, toActivate, toDeactivate } = Router5.transitionPath(fromState, toState);
```

Going from `users.view` to `users.list` would output the following:

```javascript
{
    intersection: ''users'
    toActivate: ['users.list'],
    toDeactivate: ['users.view'']
}
```

3) With a component tree this is a problem you don't have. You simply need to target the `intersection` node and re-render from there: the old branch with components to deactivate will be pruned, new components will be added. If you don't have a component tree (which is unlikely as the DOM is a tree), 
then you can use global listeners (`.addListener()`) to manage custom logic, still using `.transitionPath`.

I am currently developing 1.0.0 (development is 95% completed, now refactoring docs and cleaning up): it introduces so called "plugins" which allow you to plug custom logic at the back of the router, that might help.

**Comment by Kukkimonsuta** [comment]
Sounds good, thanks for your help :+1:
