### ISSUE TITLE
"toState is null" with routeNode

### ISSUE THREAD

**Issue by robotvert** [router5/router5#311]
Hi,

So I've been trying to get react-router5 to work using the new React context API by reading the docs and the provided sample app on stackblitz.
So far no luck...

First of all, maybe I've been looking in the wrong place but I didn't find a good explanation about the difference between RouteNode and Route. The doc says they both pass the route, previousRoute and router down to the consumer, cool, but when to use one VS the other?

Then onto the real issue, I simply can't get the simpliest thing to work when using routeNode:

```
The above error occurred in one of your React components:
    in RouteNode
    in RouteProvider
TypeError: toState is null
```
stemming, it seems, from `transitionPath.js:28`

The code I have is simply this:

```
import React from "react";
import ReactDOM from "react-dom";
import createRouter from "router5";
import loggerPlugin from "router5/plugins/logger";
import browserPlugin from "router5/plugins/browser";
import { RouteProvider, RouteNode } from "react-router5";

const routes = [
  { name: "search",  path: "/" },
  { name: "contacts",  path: "/contacts" }
];

const router = createRouter(
    routes, { defaultRoute: "search" }
  )
  .usePlugin(loggerPlugin)
  .usePlugin(browserPlugin());

ReactDOM.render((
  <RouteProvider router={ router }>
    <RouteNode nodeName="">
        {({ route, previousRoute, router }) => <div>Route</div>}
    </RouteNode>
  </RouteProvider>
), document.getElementById("spa"));
```

What am I doing wrong here?

**Comment by troch** [comment]
Hey @robotvert, I believe you have not started your router (`router.start()`). But I can improve the experience here, and it shouldn't error for `null` values.

For route node explanation: https://router5.js.org/introduction/core-concepts

**Comment by robotvert** [comment]
Ah, right, thanks for the swift reply and pointing out the obvious mistake. 
I'm not sure how I overlooked this one... 😅 
I guess throwing an error is alright, if it's indeed a mistake to use a router that's not been started, how about having the error message provide a hint, something like "no router state, have you started the router using start() ?"

As for the route node explanation, I've read the docs a few times and while the concept slowly sinks in, what I find confusing is which component _from react-router5_ to use.
What is the rule of thumb for using `Route` or `RouteNode` or no wrapper at all? The [sample app](https://stackblitz.com/edit/react-router5-new-context-api) is a mix of everything, which is good for demonstration purposes, but it makes n00bs like me more confused without specific documentation and/or accompanying code comments.

Thanks a bunch!

**Comment by troch** [comment]
When in doubt and for most use cases, simple route binding (`Route` or `withRoute`) is perfectly fine.

`RouteNode` (or `routeNode`) is an optimisation to avoid re-rendering everything when the route changes. It is only useful if you have nested routes. It's easy to swap `Route` with `RouteNode` or `withRoute` with `routeNode` once you are more comfortable with your understanding of it.

**Comment by robotvert** [comment]
Starts to make sense, thanks a lot!

Closing this non issue then.
