### ISSUE TITLE
Persistent params survive browser history navigation

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#312]
Hi!

If I specify one persistent parameter like `router.usePlugin(persistentParamsPlugin(['a']));`, it will not be reflected in the url on initial load (`/#/`), which is right.
Then if there is a link that navigates to that param when we click on it, url changes to, say, `/#/?a=1`.
Then if we press browser back button we go back in history, but url doesn't change and parameter stays in state.

I'm wondering if it is expected behavior or a bug?

**Comment by troch** [comment]
I'd say it is expected behaviour.

**Comment by klimashkin** [comment]
But it's like that only if you go back. If you remove persistent parameter (by navigating to `{a: undefined}`) then go back and then forward, parameter acts like normal parameter - it's removed on forward.

What the reason behind keeping persistent parameter while going back? It becomes altered history, rather then accurate.

**Comment by troch** [comment]
Ha, I misread your initial comment and thought it was happening the other way round. Yeah I agree going back should restore the state as it was.

**Comment by troch** [comment]
The approach from the persistent params plugin needs to be changed. Currently it cannot handle that case.
