### ISSUE TITLE
Question: Not understanding allowNotFound and defaultRoute

### ISSUE THREAD

**Issue by thezimmee** [router5/router5#313]
Hello, great library, thank you for your work!

I need some clarity on how the `allowNotFound` and `defaultRoute` options work, and the documentation, for me, is difficult to understand. Nor could I find answers searching through the repo/issues.

Here's what I am trying to do:

1. Redirect to home route (`/home`) when user arrives at root path (`/`).
2. Use `404` page as default route when no path is found.

I ended up using `404` as the `defaultRoute`, and disabling `allowNotFound`; then setting up both `root` (`/`) and `home` (`/home`) routes and using `router.forward` to forward `/` to `/home`.

Is this the correct way to accomplish the above? As a sidenote, what is the `*splat` feature I found referenced by another user? Does that act as some sort of catch all route?

Regarding `defaultRoute`, the docs say:

> When your router instance starts, it will navigate to a default route if such route is defined and if it cannot match the URL against a known route...

I think it's the "when your router instance starts..." part that confuses me... it seems the `defaultRoute` is triggered not only when the router instance starts, but any time a route is not found; in which case, it redirects to the `defaultRoute`. Am I understanding that correctly?

Regarding `allowNotFound`, from the docs:

> There are two ways to deal with not found routes: the first one is to configure a defaultRoute (and defaultParams), the second one is to allow those not found routes to create a new routing state. Set allowNotFound to true and the router will emit a state value for unmatched paths.

With `allowNotFound` set to true I can't figure out how to tie in to the event that an unmatched path is found and a new state is created. How do I tie in to the not found event/state? When would `allowNotFound` be used instead of `defaultRoute`?

Thank you for your work and your help!

**Comment by troch** [comment]
> Redirect to home route (/home) when user arrives at root path (/)

Create a route with path `'/'` and use the `forwardTo` option to redirect to home

> Use 404 page as default route when no path is found.

Use `allowNotFound`.

With `allowNotFound` a special state is created. Its name is a constant that can be imported:

```js
import { constants } from 'router5'

constants.UNKNOWN_ROUTE
```

**Comment by thezimmee** [comment]
My apologies, I completely missed the `forwardTo` option in the docs.

As for the `constants.UNKNOWN_ROUTE`, I understand I can get the not found path with that constant; I guess my question is what event can I tie into when a path is not found? I am using the listeners plugin to add listeners to my routes, which obviously doesn't create a listener on a not found route. How can I know when a route is not found?

**Comment by troch** [comment]
Not sure I understand. With `allowNotFound` a state is created. From the router perspective, it is not really different than any other state. So any listener you use, you can use for not found states.

**Comment by thezimmee** [comment]
With `allowNotFound: true`, I have this:

```js
router.add({ name: routerConstants.UNKNOWN_ROUTE, path: '/error' });
router.addRouteListener(routerConstants.UNKNOWN_ROUTE, (toState, fromState) => {
	console.log('NOT FOUND:', toState, fromState);
});
```

However, the listener does not get triggered when a path is not found. What am I missing?

**Comment by troch** [comment]
Why do you call `.add`?

**Comment by thezimmee** [comment]
I have tried creating the not found route with both `.add()` and `.createRouter()`, the above snippet was easier to share. Both ways have resulted, for me, in the not found listener not being triggered. I assume I must manually create the not found route, yes? If I don't create it I get a warning that the listener for the not found route won't be called because the route doesn't exist:

![image](https://user-images.githubusercontent.com/976368/41370303-8053394a-6f04-11e8-8640-6a78fde15f21.png)

**Comment by micros123** [comment]
Sound like I'm struggling with the same issue. I'm trying to catch any non-existing route (in case a user types an invalid path for example) and redirect them to a valid route.
I would expect this to rewrite the URL in that case too.
Tried pretty much every combination of defaultState, allowNotFound, forwardTo, etc. But nothing really changes the State.

**Comment by brett-nuske-alliancesoftware** [comment]
Not sure if this is the correct way to do it but the following was working for us...

```
function myErrorPlugin(router, dependencies) {
     return {
         onTransitionSuccess: (toState, fromState) => {
             if (toState.name == constants.UNKNOWN_ROUTE) {
                 console.log('requested page not found!');
                 router.navigate('home.view');
             }
         }
     };
}
myErrorPlugin.pluginName = 'MY_ERROR_PLUGIN';

const routes = [
     { name: 'home', path: '/dashboard', children: [
         { name: 'view', path: '/view'},
     ]},
     { name: 'notfound', path: '/notfound' }, 
];

const router = createRouter(routes, {
     allowNotFound: true,
     trailingSlashMode: 'always',
})
.usePlugin(loggerPlugin)
.usePlugin(
     browserPlugin()
)
.usePlugin(myErrorPlugin)
```

**Comment by troch** [comment]
@thezimmee picking this issue back up:
- You don't need to create a not found route
- The warn on listeners plugin is not an issue, it warns you it might never be called just because it ignores it is a possible state name=. But it should get called when emitted, I have verified it with a test (#330)
