### ISSUE TITLE
Can't navigate back to parent route from child

### ISSUE THREAD

**Issue by soumyart** [router5/router5#315]
Once navigate to a child route, it is not coming back to parent after clicking the Link tag. I have created a [stackblitz sample](https://stackblitz.com/edit/react-router5-new-context-api-w1iz9p) by extending the router5 new context api project.

Steps to follow:
1. Go to Inbox
2. Click on message
3. Again click on Inbox

Expected Behavior:
After following step 3 current route should be inbox and message content shouldn't be displayed.

Link to sample project: https://stackblitz.com/edit/react-router5-new-context-api-w1iz9p

**Comment by troch** [comment]
The route changes but the last message content is still displayed. Will have a look.
