### ISSUE TITLE
router.subscribe not documented

### ISSUE THREAD

**Issue by jacobweber** [router5/router5#316]
The documentation says that the [listeners plugin](https://router5.js.org/advanced/listeners-plugin) is deprecated in favor of router.subscribe. But the signature for this method isn't documented in [API Reference](https://router5.js.org/api-reference); it's only mentioned in [Observing State](https://router5.js.org/guides/observing-state#subscribing-to-state-changes).

Assuming it doesn't take any arguments, is there no longer a way to listen for when specific routes/nodes are activated?

**Comment by troch** [comment]
Hi @jacobweber, it is documented under observing state, as you noted. Listeners plugin is not deprecated yet, it might be in the future as its functionality overlaps with the `subscribe` method.

**Comment by jacobweber** [comment]
That page doesn’t describe how to call it though (e.g. what arguments to pass), like the API reference page would.
