### ISSUE TITLE
child route names not documented

### ISSUE THREAD

**Issue by jacobweber** [router5/router5#317]
If I define routes with children, it seems that I can't call router.navigate and pass it the child route's name. Instead I found by experimentation that I need to pass [parent-name].[child-name]. But I don't see this documented anywhere.

**Comment by troch** [comment]
Navigation to routes which are relative to the current route is not a feature, so it's not documented since it's not a feature.

**Comment by jacobweber** [comment]
Maybe I phrased this wrong. I’m just talking about navigating to a child route in any manner, regardless of the current route. It doesn’t look like the parent.child syntax is documented.
