### ISSUE TITLE
Client-side navigation on GitBooks docs site is not working

### ISSUE THREAD

**Issue by azangru** [router5/router5#318]
This may be a well-known issue, or perhaps a very region-specific problem (and therefore maybe not an issue at all for most visitors), but whenever I try to read router5 docs on the GitBook-powered site (https://router5.js.org), I can not navigate around it at all — clicking on any link in the table of contents causes this to happen:

![image](https://user-images.githubusercontent.com/6834224/42129338-de2abca4-7cca-11e8-8838-6a08c4e6a249.png)

![image](https://user-images.githubusercontent.com/6834224/42129374-b971b4e8-7ccb-11e8-9c8b-639a29649d46.png)

Server-side routing works fine; but with the client-side routing broken like this the site is almost unusable.

**Comment by troch** [comment]
Must have been a glitch on their side

**Comment by azangru** [comment]
@troch If this is a glitch, it's a very persistent one — I am seeing it on two different machines, from two different internet providers; and I've been seeing it for at least a couple of months.

I have also checked the docs site from a virtual machine using Browserstack, and everything works fine there. So it's probably some region-specific problem. I am located in Russia, and our internet regulators have broken quite a large portion of the internet for us while trying to block Telegram, so this might be related. Or it might be not.

Just wanted to let you know that the docs site is likely broken for some countries.

**Comment by troch** [comment]
I don't have any control on the doc site (provided by GitBooks). What do you refer to when you say "I have also checked the docs site from a virtual machine using Browserstack"?

**Comment by azangru** [comment]
I looked at another site whose docs are using GitBook (redux.js.org) — and yeah, navigation is broken there as well. So it's almost certain that our internet regulators, in their infinite wisdom, broke something on which GitBook is relying for navigation.

Sorry for the unrelated issue.

**Comment by troch** [comment]
@azangru do you have any other screenshot / console log on what breaks? Intercomm is a chat platform, and with my ad blocker on, I also get a 403 on their ping request: that doesn't prevent me from seeing the docs content. Also, if you have an add blocker on, have you tried without?

**Comment by azangru** [comment]
Sure. My initial blaming of the ping request was incorrect, sorry for that. That's because the real culprit shows up a little bit later in the network panel. Here is a more detailed and corrected description:

1) Clicking on the top-level nav items in the sidebar works:

![image](https://user-images.githubusercontent.com/6834224/42702511-6c0c9b58-86d2-11e8-9fcb-71d2e9bc485b.png)

2) Clicking on the second-level nav items in the sidebar doesn't:

![image](https://user-images.githubusercontent.com/6834224/42702550-8bcd8434-86d2-11e8-8362-e7954abdd320.png)

3) Here's what I see in the network panel:

![image](https://user-images.githubusercontent.com/6834224/42702627-baf0ce42-86d2-11e8-970c-c48da0d78e82.png)

As you can see, the request to https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/documents timed out after about a minute and a half:

![image](https://user-images.githubusercontent.com/6834224/42702667-d9ef35ae-86d2-11e8-9662-fa65d07f2b96.png)

I am not using any ad blockers.
