### ISSUE TITLE
No way to selectively apply the active class to react-router5's Link depending on query parameters

### ISSUE THREAD

**Issue by azangru** [router5/router5#322]
react-router5's `BaseLink` component attempts to determine whether its route is currently active:

```
    isActive() {
        return this.router.isActive(
            this.props.routeName,
            this.props.routeParams,
            this.props.activeStrict
        )
    }
```
(https://github.com/router5/router5/blob/master/packages/react-router5/modules/BaseLink.js#L31-L37)

router5's `isActive` method accepts an argument (`ignoreQueryParams`) telling it whether to include query parameters in route matching:

https://github.com/router5/router5/blob/master/packages/router5/modules/core/utils.js#L20-L39

There doesn't seem, however, to be a way to use the `ignoreQueryParams` option from the `BaseLink` component. So, unless I am missing something, it's currently impossible to selectively apply the active class to the Link depending on the route's query parameters.

**Comment by azangru** [comment]
> That said, BasLink can be modified to accept a prop telling it to ignore query params.

Which prop is that? I looked through the list [here](https://github.com/router5/router5/blob/master/packages/react-router5/modules/BaseLink.js#L115-L125), but couldn't find the correct one.

**Comment by troch** [comment]
" BasLink can be modified to accept" means that it can change, not that it exists.

**Comment by azangru** [comment]
> " BasLink can be modified to accept" means that it can change, not that it exists.

Yep, sorry, I misread that. Would you like a PR?

**Comment by troch** [comment]
Yes please :)

**Comment by azangru** [comment]
@troch done: https://github.com/router5/router5/pull/323
