### ISSUE TITLE
Param matchers greedy match defined routes

### ISSUE THREAD

**Issue by cayuu** [router5/router5#325]
```javascript
const routes = [
  { name: 'home', path: '/' },
  { name: 'home.moo', path: 'moo' },

  { name: 'eviltroll', path: '/:catch' } 
]

// Expect to match "home.moo"
router.matchPath('/moo')
// -> { name: 'eviltroll', params: { catch: 'moo' } ...
```

:(

I'm probably doing something wrong here, because this seems like quite an obvious use-case, defining one set of handlers for matching routes, and letting mis-hits continue through to the rest of the defined routes. What I didn't expect was for the 'param' operator (`eviltroll`) to be greedy and match the route defined by the "home.moo" handler. 

Is this expected behaviour? And if so, can the intended match above be reached some other way?

Thanks!

**Comment by troch** [comment]
`{ name: 'home.moo', path: 'moo' }` -> `/moo` instead?

**Comment by cayuu** [comment]
I gave that a shot as part of testing, and it doesn't match at all - ie. even if you remove the 'eviltroll' path and just leave the two 'home' paths `router.match('/moo')` returns `@@router5/UNKNOWN_ROUTE`. This is where I suspect I might have something wrong?

**Comment by troch** [comment]
Didn't realise `/moo` was nested. So the behaviour you see is expected: the path matcher goes through top node and follow down match partially match the given path. But in your case `/moo` is first matched by `/:catch`.

**Comment by cayuu** [comment]
Thanks Thomas, understood. Will design for this consideration. #closing

**Comment by troch** [comment]
To clarify: when two path definitions like `/moo` and `/:param` are siblings (they are children of the same parent node), `/moo` is tried before `/:param`.

The reason for not returning all matches and then picking the "best" one (i.e. the most specific one - with less params) is a design decision for increased performance and scalability: especially in the scenario of server-side rendering. That kind of match strategy is common server-side: the first match is the match.
