### ISSUE TITLE
Performance issue adding lots of routes

### ISSUE THREAD

**Issue by vincentjames501** [router5/router5#328]
There is a pretty serious performance issue if your application has a lot of routes. In our case, we have over 500 and on my decently fast machine it can take over 4 seconds to add them all! This is obviously an unacceptable amount of time if you want fast web app start up times. I've submitted a PR here to hopefully address the issue: https://github.com/troch/route-node/pull/22 . Let me know if there is anything else I can do to help.

**Comment by troch** [comment]
@vincentjames501 updated, v6.4.0 should have a much faster startup time for your use case!

**Comment by vincentjames501** [comment]
Thanks so much @troch ! Looks like the TS definition will need to be updated as well. Would you like for me to do that or would you?

**Comment by vincentjames501** [comment]
Looks like the interface for `add` didn't change: https://github.com/router5/router5/blob/bedd4e9a3760ffc262f52b356a212366aca7c537/dist/router5.js#L2369

Is there a different method you were thinking for supplying the `sort` param?
