### ISSUE TITLE
Feature request: abstract states

### ISSUE THREAD

**Issue by Kukkimonsuta** [router5/router5#33]
While trying to build a custom framework around router5, heavily utilizing the implementation of nested states, I've found myself in need of abstract states - state that has optional path and can't be navigated to, but trigger relevant events and can be used in custom pipeline.

For instance - I've got two layout pages `public` and `private`. These would both trigger their events when transitioning from one child state to another (or just be used in custom pipeline), but there would be no way to navigate to them directly.

```javascript
.addAbstractNode('public')						// abstract state without url
.addAbstractNode('public.account', '/account')	// abstract state with url (for inheritance to child states)
.addNode('public.account.signIn', '/sign-in')	// normal state

.addAbstractNode('private') 					// abstract state without url
.addNode('private.home', '/') 					// normal state
```

Such instance would only allow going to `/` and `/account/sign-in`.

**Comment by troch** [comment]
It is something I thought about recently. I think it is feasible to support but requires quite a bit of work on route-node library. Mostly because of the matching process which consumes matched nodes. With abstract nodes, it will need to explore children and then move on to the next sibling if no match is found.

There is also a different meaning of 'abstract' which can be found in ui-router for example, which is a route which cannot be directly activated.

May I ask what sort of framework you are building? I am quite interested in how people use router5.

**Comment by Kukkimonsuta** [comment]
I think `router-ui`s abstract state is pretty much the same as what I'm after. From their definition:

> An abstract state can have child states but cannot get activated itself. An 'abstract' state is simply a state that can't be transitioned to. It is activated implicitly when one of its descendants are activated.



Sure: I'm building something I like to call 'hybrid single page application framework'. It's basically step between common server side web application and single page application. The routing logic and view composition is taken care of in the browser, but views are being rendered on the server. This allows me to write applications with SPA-like feel, but keep my sanity while developing and more importantly maintaining such application. I understand that this might sound crazy to some people, but I've already tried to go full angular and the only thing I've found is that there is too much overhead to write such app properly and that it has crazy low maintainability index (at least when combined with asp.net).

**Comment by troch** [comment]
I think what I will split it into two features:
- abstract states (states which cannot be activated, but children can)
- path-less states (states without a defined path)

an abstract state can be path-less or not.
A path-less state can be abstract or not.

**Comment by Kukkimonsuta** [comment]
Sounds great :+1:

**Comment by troch** [comment]
I'm closing this for now, I'm not near being able to implement such things for now.

**Comment by LeonardoGentile** [comment]
@troch so this feature was canceled?

**Comment by troch** [comment]
@LeonardoGentile I've hadn't have the time to look at it. So not cancelled, but not a priority.

**Comment by LeonardoGentile** [comment]
@troch just for curiosity, is this feature planned or included for version 5?

**Comment by troch** [comment]
@LeonardoGentile I have _route forwarding_ awaiting to be released and it will provide something similar but more general purpose. See PR #154, it will also useful for multiple paths pointing to the same route (#90)

**Comment by LeonardoGentile** [comment]
Great 👍 
I will wait for the release to test how I could you use that PR to have the abstract states behavior. 

Btw I guess that for having such similarity with abstract routes then before forwarding a route to another all the middleware and lifecycle functions will still be called for the original route, isn't it?

**Comment by troch** [comment]
Just released (5.1.0)

> the middleware and lifecycle functions will still be called for the original route, isn't it?

Nope, it won't. If you transition from `A` to `B`, with `B` forwarding to `C`, it is equivalent to a `A` to `C` transition (like `B` didn't exist).

**Comment by LeonardoGentile** [comment]
hmm ok, then I'm not sure route forwarding is similar to abstract routes 🤔 
I'll have to play a little with it then

**Comment by troch** [comment]
Following ui-router definition, it can be if you forward a parent to one of its child.

> An abstract state can have child states but cannot get activated itself. An 'abstract' state is simply a state that can't be transitioned to. It is activated implicitly when one of its descendants are activated.

What you seem to think about is some sort of "portal" routes.

**Comment by LeonardoGentile** [comment]
Coming from ui-router myself (it's been a while) I used the abstract routes as the last sentence defines: "It is activated implicitly when one of its descendants are activated."

This is helpful to apply some auth logic/data injection to a group of subroutes.

Using the route forwarding from a parent to a child (to obtain a similar result) might work for a single child. When we have multiple children how do we forward from parent to a specific child? 

```
A/
  B/
  C/
  D/
```
Let's say we declare that when we navigate to `A` then forward to `B`.   
How do we say the same for `C` and `D`?  The router only knows that when we hit A -> go to B.

**Comment by troch** [comment]
>>> Let's say we declare that when we navigate to A then forward to B.
How do we say the same for C and D? The router only knows that when we hit A -> go to B.

Not sure I understand. But forwarding only happens if you navigate to A. Navigating directly to B, C or D does nothing special.

**Comment by LeonardoGentile** [comment]
>Not sure I understand. But forwarding only happens if you navigate to A. Navigating directly to B, C or D does nothing special.

Exactly :) That was the concept of an abstract route in ui-router. Anyway let me experiment with forwarding and I'll get back to you

**Comment by troch** [comment]
@LeonardoGentile worked as expected for you?
