### ISSUE TITLE
Route5 for MarkoJS

### ISSUE THREAD

**Issue by jesse1983** [router5/router5#332]
Hi guys.

Recently I created a package for [MarkoJS](https://markojs.com/) (similar React / Vue) using Router5:

https://jesse1983.github.io/marko-router5

It's a new package, then it has few downloads and stars.

If there is interest, you can add it on Examples ok?

Tks!

Jesse Pinheiro.

**Comment by troch** [comment]
Hey @jesse1983, nice work on this 👍. I'm going to add a link to it.
