### ISSUE TITLE
Seeking advice

### ISSUE THREAD

**Issue by ematipico** [router5/router5#337]
Hi, I have the following questions/doubts and I am seeking advice:

1. `canActivate` => why there isn't a function called `clearCanActivate`? I noticed that for the counter part, there is a `clear` function 
2. Is it possible to remove routes? If so, how? I didn't find anything on the documentation
3. In an attempt to create a breadcrumbs component, what's the best approach with `router5`? I was looking at the APIs but for now I didn't have any lightbulb. My idea of breadcrumbs was the most diffused `home -> section -> detail -> further detail`

**Comment by troch** [comment]
Hi @ematipico 

- Pretty much all the time, the use case for `canActivate` is to check global state, while the use case for `canDeactivate` is to check local state. `canActivate` tends to belong to the application (is user admin, is user logged in, etc...), `canDeactivate` tends to belong to views / components (is form incomplete, has user taken required steps, etc...)
- Not possible to remove routes at the moment
- For breadcrumbs, you can simply have a component connected to the route state (`withRoute`) and then conditionally render the various elements
