### ISSUE TITLE
Multiple/nested routers possible?

### ISSUE THREAD

**Issue by milesj** [router5/router5#339]
Sorry if this is the wrong place. I looked through the docs and codebase but couldn't find much.

We have a React application that will have a top-level router that modifies the URL. This router will mainly be used to jump around root landing pages. Within each of these landing pages, we need a nested router that doesn't modify the URL (can't deep link for security reasons). Throwing this logic into component state/context would be annoying, so hoping to lean on a routing layer that supports it.

**Comment by troch** [comment]
Hi @milesj, nested routers is not officially supported, I can think of two issues which might not be issues in your case:
- If multiple routers listen to popstate events and accessing the URL: in your case, your nested router doesn't need to read / write the URL (it doesn't need the browser plugin).
- With React, it uses context (old one) to store the router, so nesting providers would mean you can't access both at the same time
