### ISSUE TITLE
Add ability to set arrays in query parameters with square brackets

### ISSUE THREAD

**Issue by Ashot-KR** [router5/router5#36]
`arr=1&arr=2` this scheme has several problems:
1. If only one parameter passed(`arr=1`), it parsed as a `string`. `arr[]=1` allow to parse it as array with single element. In my case i had to manually convert single value to array.
2. If application prerenders page on server with PHP, it won't parse `arr=1&arr=2` as an array, it gets only last value (http://stackoverflow.com/a/9547490)

**Comment by troch** [comment]
Thanks for your feedback. I will add it to [route-node](https://github.com/troch/route-node) and [path-parser](https://github.com/troch/path-parser).

**Comment by troch** [comment]
Supported in 2.0.0
