### ISSUE TITLE
[ts] RouteNode is missing in typings

### ISSUE THREAD

**Issue by vire** [router5/router5#366]
```
  "name": "react-router5",
  "version": "6.5.0",
  "typescript": "3.1.1"
```
error thrown by tsc:

```
Module ''react-router5'' has no exported member 'RouteNode'. Did you mean 'routeNode'?
```

**Comment by troch** [comment]
I've commented on your PR

**Comment by vire** [comment]
@troch I've stumbled upon the bug mentioned in #372, sorry for missing the generic param `T`, I wasn't using `Route` at all till now... 

It's a question for you to consider adding some typescript tests to have `typings` integrity...
