### ISSUE TITLE
canDeactivate not working properly

### ISSUE THREAD

**Issue by dubiousdavid** [router5/router5#368]
Here's a simple example, using react-router5 stackblitz. The `compose` route should be prevented from deactivating, but it isn't.

https://stackblitz.com/edit/react-router5-hqt5jr?file=index.js

Also, are you suppose to be able to set `canDeactivate` on your initial array of routes alongside `name`, `path`, etc.?

**Comment by troch** [comment]
No idea why the example is broken, but I'm lacking time to be able to look at it. So PR welcome.

> Also, are you suppose to be able to set canDeactivate on your initial array of routes alongside name, path, etc.?

No, it's not supported.

**Comment by sloosch** [comment]
Had the same problem:
You need to set "forceDeactivate: false" in the browserPlugin and "autoCleanUp: false" in the router config.

The doc says something like "not recommended to set forceDeactivate to false" but does not state why. And it is not clear to me what benefit it has to clear "canDeactivate" functions after each transition by default (autoCleanUp: true).

**Comment by troch** [comment]
`canDeactivate` is not a great idea, because of how browser history works. The documentation and the feature are not very clear, and things like `autoCleanUp` are very early choices of this project. I'll see what can be done for the next batch of breaking changes (v7).

**Comment by troch** [comment]
(Closing for now).
