### ISSUE TITLE
Memory leak with cloning the router and usage of usePlugin

### ISSUE THREAD

**Issue by davidecantoni** [router5/router5#369]
For performance reasons we are cloning the routerInstance each time:

```javascript
const routerInstance = createRouter(routes, {
    trailingSlash: true,
  })
  .usePlugin(
    browserPlugin({
      useHash: false,
      base: 'http://...',
    })
  )
  .usePlugin(listenersPlugin())
```

.... other file
```javascript
routerInstance.clone()
```

Unfortunately if we stress test the application (few 1000 r/m) the cpu and memory looks as follow:

![screen shot 2018-10-04 at 13 00 25](https://user-images.githubusercontent.com/1339576/46470092-be54f380-c7d5-11e8-8b8a-3f94423a2f4d.png)

If we comment out the two `usePlugin` the cpu memory goes back to normal:

![screen shot 2018-10-04 at 13 00 25 2](https://user-images.githubusercontent.com/1339576/46470093-be54f380-c7d5-11e8-9a96-d1527ad8e85e.png)

Versions in use:
- react: "^16.5.0"
- react-router5: "^6.1.0"
- redux-router5: "^6.0.2"
- router5: "^6.3.0"

on Nodejs 10.6.0

Any idea what could be the reason for those memory leaks?

Thanks a lot!

**Comment by troch** [comment]
Thanks for reporting, I'm not sure what would cause it but will run through the cloning logic. You only use the two plugin listed, but no middleware?

**Comment by troch** [comment]
OK, I'm going to have to set tests for it as I don't see where could be the problem on the cloning itself. In the meantime, what you can do is to add plugins after cloning rather than before.

**Comment by davidecantoni** [comment]
Thanks @troch for your investigation. 
Unfortunately i need more time to investigate if the router is the problem or something else. 
If you wish we can close the ticket and once i went over it i can give you a feedback?

**Comment by troch** [comment]
Thanks for replying. Yes sure, let's do that. I'll close the issue just now, but will still receive any notification and we can re-open it later.
