### ISSUE TITLE
Link component doesn't respect route's defaultParams

### ISSUE THREAD

**Issue by kierson** [router5/router5#377]
Hi!

It seems that is is not possible to use `<Link />` component like this:

```js
// route
{
  name: 'some-route',
  path: '/some-path/:id',
  defaultParams: { id: '1' },
}

// link usage
<Link routeName="some-route">Some Link</Link>
```

This ends up with an exception:
```Error: Cannot build path: '/some-route/:id' requires missing parameters { id }```

However when using `router.navigate('some-route')` everything works fine. `navigate` method of router instance understands `defaultParams`.

Would it be possible to have such behavior in `<Link />` komponent as well?

**Comment by troch** [comment]
Hi, looking into it.

**Comment by troch** [comment]
I've publish a new patch (router5@6.6.2)
