### ISSUE TITLE
Error if callback "done" is missing for router5.start()

### ISSUE THREAD

**Issue by sukazavr** [router5/router5#38]
Hello! I noticed something.

If option "useHash" is set to "true" and the callback "done" is missing for router5.start(), then i get the error "Uncaught TypeError: done is not a function".

Router5 version is 1.2.1.

![image](https://cloud.githubusercontent.com/assets/2406951/11917154/549664de-a70c-11e5-9b93-1aa7dfde65e8.png)

**Comment by troch** [comment]
Thank you for raising this. It has been fixed with 1.2.2.
