### ISSUE TITLE
slow transition from page with large number of <Link /> elements

### ISSUE THREAD

**Issue by ajeffrey** [router5/router5#382]
Hi,

I have a page with a large number of Link elements (around 6000, it's a large table). When I navigate away from this page by clicking one of the links, react-router5 directly results in a 6 minute delay in rendering. Is there a way to work around or otherwise disable this behaviour? 

Thanks

[edit]

I initially thought this was caused by the unsubscribe functionality, but that's not quite right. For additional information, the delay seems to be caused by the logic in withRoute.js:
```
                    this.routeState = {
                        route,
                        previousRoute
                    }
                    if (this.mounted) {
                        this.forceUpdate()
                    }
```

It appears that on TRANSITION_SUCCESS, this function is called for every Link, forcing an update (and thus, presumably, a re-render). I'm not very familiar with the internals of router5 but this seems to be the source of the slowdown.

As an experiment I commented out `this.mounted = true` in `componentDidMount` and the navigation time went from 6 minutes to about a second.

**Comment by troch** [comment]
You can use `BaseLink` instead, which isn't connected to route changes, or implement your own custom link component.

**Comment by ajeffrey** [comment]
that's worked, thank you!
