### ISSUE TITLE
Router creation fails when using `Redux-Router5` if no dependencies are provided

### ISSUE THREAD

**Issue by NoiSek** [router5/router5#388]
When used with `redux-router5` and it's `router5Middleware`, router5 will throw the following:

```
index.es.js?c208:168 Uncaught TypeError: Cannot set property 'store' of undefined
    at Object.router.setDependency (index.es.js?c208:168)
    at eval (index.es.js?2236:118)
    at eval (redux.js?00d8:615)
    at Array.map (<anonymous>)
    at eval (redux.js?00d8:614)
    at createStore (redux.js?00d8:79)
[... truncated ...]
```

This is due to redux-router5 attempting to set `routerDependencies['store'] = <reduxStore>` where `routerDependencies` is `undefined`. 

The temporary fix for this is to use an empty array when initializing the router i.e. `createRouter(someRoutes, { 'defaultRoute': 'home' }, []);`

As a suggestion, router5 should be checking whether or not the value is undefined, and then provide an empty array as appropriate [here](https://github.com/router5/router5/blob/03a96c62412b558531f0435dd5ab0e47e2ea56cf/packages/router5/modules/core/dependencies.ts#L5).

**Comment by troch** [comment]
Fixed and released, thanks for reporting
