### ISSUE TITLE
Make path-parser replaceable with other library

### ISSUE THREAD

**Issue by aleksandrlat** [router5/router5#394]
Hi @troch 
`path-parser` has very limited functionality. 
It would be nice to make it replaceable using some config option.

Also it is not possible to define routes with multiple varying query params.

**Comment by troch** [comment]
Hi @aleksandrlat, it would concern `route-node` package rather than `router5`. What is limiting you with `path-parser`?

**Comment by aleksandrlat** [comment]
We need optional params.

**Comment by aleksandrlat** [comment]
Is it possible to redirect from hash routes like `/#part1/part2` to `/part1/part2` with router5?
We are adding router5 and we are changing hash urls to regular. And we want to redirect from old urls to new.

**Comment by troch** [comment]
Optional parameters are achievable with `forwardTo`. It's a little verbose, but I'm open on potential abstractions at the router level (i.e. generating the example below). For using a different parser, I'm unsure about the outcome (whether it's something which is feasible or not), and I'm not willing to try myself.

```js
{
    name: 'parentRoute',
    path: '/route',
    forwardTo: 'parentRoute.default',
    children: [
        {
            name: 'default',
            path: '/'
        },
        {
            name: 'withId',
            path: '/:id'
        }
    ]
}
```

> Is it possible to redirect from hash routes like `/#part1/part2` to `/part1/part2` with router5?

No, but it's straight forward enough to do it before you call `router.start()` (detecting `#` and removing it if match). Or you can add a plugin which wraps the `start` function and applies that logic (see browser plugin for inspiration).

**Comment by aleksandrlat** [comment]
Thank you @troch!
Also for url like this `http://localhost:3000/user/settings?integrationstab=true&no-rsc-connect`
`no-rsc-connect` does not appear in params of route. I use `queryParamsMode` = `loose`

> For using a different parser, I'm unsure about the outcome (whether it's something which is feasible or not), and I'm not willing to try myself.

Will you accept PR if I implement it?

**Comment by mikkelwf** [comment]
@troch It would be nice to have options URL params.
Especially for routes displaying default / unfiltered content (content without the URL param).
Right now the route needs to be registered two times, and the `forwardTo` does not really change this, since the example with two child routes now totals 3 unique routes.
