### ISSUE TITLE
[react-router-5] useRouteNode hook is broken

### ISSUE THREAD

**Issue by titouancreach** [router5/router5#395]
Hello,

Please refer to this [codesandbox](https://codesandbox.io/s/w7y6okrz1w)
I've created two components, one is `ContentWithHocs` and the other is `ContentWithHooks`

From the App component, I call either `ContentWithHocs` or `ContentWithHooks`. It appears that in some case (maybe the first time, before the hook subscribe), the current route returned by `useRouteNode` is null whereas this doesn't show up with the HOC version. 

Maybe the first `useState` should be retrieved from context instead of null ?  

Thanks

**Comment by titouancreach** [comment]
Also, maybe [here](https://github.com/router5/router5/blob/master/packages/react-router5/modules/hooks/useRouteNode.ts#L30), `useEffect` should depends of `router`. In that way, if router change (it shouldn't but this is cleaner), we unsubscribe to the old router and subscribe to the new one.

**Comment by troch** [comment]
Is it broken on 16.8.0 only or it was broken before?

**Comment by titouancreach** [comment]
Hooks wasn't released before 16.8.0, so it was not really usable

**Comment by troch** [comment]
Well of course I meant alpha releases, this was developed against the alpha release :)

**Comment by titouancreach** [comment]
I didn't try, but I think so. It looks it is a bug from the code and not from the hooks itself.

- The first time, state is null (before the component did mount, the effect is not triggered) https://github.com/router5/router5/blob/master/packages/react-router5/modules/hooks/useRouteNode.ts#L10

Maybe the solution is not to initialize the state to null but, initialize it with the current route (same way as: https://github.com/router5/router5/blob/master/packages/react-router5/modules/hooks/useRoute.ts)
