### ISSUE TITLE
Remove tsconfig from npm package

### ISSUE THREAD

**Issue by titouancreach** [router5/router5#397]
Maybe we can remove `tsconfig.*.json` from npm because Vscode (maybe other code editor) complains.
They complain about the `../../tsconfig.base.json` that doesn't exist.
Maybe I can fix my VSCode configuration to ignore that file, but I think it's a good thing to not reference a file that doesn't exist.
![screenshot](https://user-images.githubusercontent.com/3995719/52489120-b6f98880-2bc1-11e9-8a11-27e9e8242680.png)

That's not a big deal, but I feel frustrated to alway have: "1 problem" in the "PROBLEMS" section :)

**Comment by troch** [comment]
Fixed with latest release
