### ISSUE TITLE
Component not re-render after navigate

### ISSUE THREAD

**Issue by khotey** [router5/router5#403]
I have routes
```ts
const routes: Route[] = [
  {
    name: "home",
    path: "/"
  },
  {
    name: "signIn",
    path: "/sign-in"
  }
];
```

And root component, in app component I check if user authenticated and if is it not call `router.navigate("signIn")`, but after first render app it not re-render after location change.

```tsx
const enhance = compose(
  routeNode(""),
  withAuthUser
);

const App = ({ route, router, authUser }: Props) => {
  const topRouteName = route.name.split(".")[0];

  if (topRouteName === "home") {
    if (!authUser) {
      // change location but App not re-render to return SignIn
      // and show Home component on sign-in location
      router.navigate("signIn");
    }

    return <Home />;
  }

  if (topRouteName === "signIn") {
    return <SignIn />;
  }

  return <h2>400: Not Found</h2>;
};

export default enhance(App as any);
```

**Comment by troch** [comment]
Calling navigate in a render is not advisable. Instead, look at handling this side-effect in a different way. router5 allows you to use `canActivate` on a route node, and to redirect to another route. Alternatively you can use the `useEffect` hook, or `componentDidUpdate` in a class.
