### ISSUE TITLE
Allow reload of a page

### ISSUE THREAD

**Issue by Christian24** [router5/router5#408]
Hi,

it would be cool to have the option that when navigating to a page, a full reload would happen.
Something like location.reload with https://developer.mozilla.org/en-US/docs/Web/API/Location/reload 

I have the requirement to reload the login page to gain a xsrf token when navigating to the login page. 

Is this a feature for on the roadmap? Or can I do this with callbacks?

**Comment by titouancreach** [comment]
Why not use `window.location.href` directly ?

**Comment by troch** [comment]
Hi @Christian24, you could implement a custom middleware or plugin which would reload the page. Another option is to "decorate" the `navigate` function (you can look at the browser plugin for inspiration on how the start function is decorated)

**Comment by Christian24** [comment]
Thanks for the input, I will see what I can do.
