### ISSUE TITLE
Exceptions are swallowed

### ISSUE THREAD

**Issue by Nickman87** [router5/router5#42]
Hi,

I've been having a hard time tracking exceptions in my application and have just discovered the reason: When working with promises in a transition middleware, exceptions get swallowed when they occure while resolving the promise.

By adding a `catch` that rethrows the error to the async handler here:
https://github.com/router5/router5/blob/master/modules/async.js#L21
My exceptions are correctly displayed in the console.

I'm not sure if this is the best way to handle this issue, but it would be nice to be able to get these errors out of the router.

**Comment by troch** [comment]
Are you talking about JS errors caught with a `try { } catch { }`, or rejected promises with a `.catch`?

**Comment by Nickman87** [comment]
I'm talking about JS errors that could be caught with `try {} catch {}` that are thrown in the 'done' handles of an accepted (or rejected) promise.

**Comment by troch** [comment]
I'll improve that with version 2.0.0

**Comment by Nickman87** [comment]
Awesome!

**Comment by troch** [comment]
Improved with 2.0.0
