### ISSUE TITLE
Consider putting on CDNs

### ISSUE THREAD

**Issue by JonathanWolfe** [router5/router5#43]
It'd be helpful for testing, examples, and sites that don't need a build step to be able to use Router5 from a CDN like [cdnjs.com](https://cdnjs.com) and [jsdelivr.com](https://jsdelivr.com).

This would also let us put running examples in the docs using [jsbin](https://jsbin.com) and such.

**Comment by troch** [comment]
Good idea. I have to look into it and create PRs for it.

**Comment by troch** [comment]
Didn't get round doing it on cdnjs or jsdelivr yet, but npmcdn and rawgit are two CDNs working just now:

- https://npmcdn.com/router5@3.0.3/dist/browser/router5.min.js
- https://cdn.rawgit.com/router5/router5/v3.0.3/dist/browser/router5.min.js
