### ISSUE TITLE
Are these packages abandoned?

### ISSUE THREAD

**Issue by mahnunchik** [router5/router5#448]
* Last update on 13 Mar 2019
* Outdated documentation and examples

Are these packages abandoned?

**Comment by troch** [comment]
Hello, no it's not but I've had limited time to maintain it. I'm in the process of pushing a general update to fix some bugs and resolve type issues (see #446). ETA is within 2 weeks now.

**Comment by mahnunchik** [comment]
Thank you for the clarification.
