### ISSUE TITLE
onTransitionSuccess not passing the final state piped from middlewares

### ISSUE THREAD

**Issue by gera2ld** [router5/router5#45]
`onTransitionSuccess` does not pass the final state piped from middleware, `$$success` is invoked with the old `toState` instead of the final `state` passed by `_transition`, I think that does not make sense. Besides, `router5.start` works properly with the middleware.

Code ref: https://github.com/router5/router5/blob/89227b49586bf382f49daa4a080c2377ac080739/modules/router5.js#L502

**Comment by troch** [comment]
You are right, `state` should be passed to success callbacks. Committing a fix...

**Comment by troch** [comment]
2.0.4 released, fixing that issue. Thanks for raising!
