### ISSUE TITLE
Universal reload

### ISSUE THREAD

**Issue by lagden** [router5/router5#46]
Hi,

I created a test based in your example: http://router5.github.io/docs/universal-applications.html
But the router5 is not working, it's causing **reload in page**!!

Am I doing something wrong?
https://github.com/lagden/router5-playground

In my test, I created `workaround.js`
https://github.com/lagden/router5-playground/blob/master/public/workaround.js#L6-L16

I put `event.preventDefault()` for all `<a>` and call `router.navigate`. In this way the `router5` behaves as it should, but I believe the `router5-history` should make this work.

**Comment by troch** [comment]
I got confused by the title of the issue.

The behaviour you describe is completely normal, and it is not router5-history role to intercept links and transform clicks into routing instructions. What you describe is not a workadound and when creating links in your app, you have two choices:
- You can use components creating links with click handlers. preventing default and calling `router.navigate`
- You can use event delegation to perform link clicks interception. There is a package available here: https://github.com/jas-chen/router5-link-interceptor

**Comment by lagden** [comment]
Sorry!! The subject was really weird!! :sweat_smile:

Okay, now I understand how the router5 works!
I took  a look at code of `router5-link-interceptor` and it was inspired on `visionmedia/page.js`!
I thought this behaviour was already embedded on the library.

My [playground](https://github.com/lagden/router5-playground) was updated and works as it should.

Thanks for the clarification.

**Comment by troch** [comment]
No problem. There is also something to clarify with universal applications: you are following the example (I need to update it) which uses the same router instance and start / stop on each request. This is OK as long as your start transitions are synchronous. If it becomes asynchronous (because of canActivate or a middleware function), you need to create a new router instance each time (it is OK to do that).

**Comment by lagden** [comment]
is missing an `vanillajs` example!
Would be great if we had one! :+1:
