### ISSUE TITLE
Redirect route in `canActivate`.

### ISSUE THREAD

**Issue by nicholaswyoung** [router5/router5#48]
Is there a way to, if `canActivate` fails, redirect to another route?

**Comment by nicholaswyoung** [comment]
If `canActivate` return a rejected `Promise`, I want to redirect to another route.

**Comment by troch** [comment]
The way I do it with redux is by adding a middleware: if action is `TRANSITION_ERROR` and the error code is `CANNOT_ACTIVATE`, I navigate to another route (ex: sign in page).

I am currently thinking about different solutions to redirection, mainly to make it server friendly (i.e. working with `start`)

**Comment by nicholaswyoung** [comment]
@troch How do you navigate from inside the redux middleware? I don't believe that I've seen that API yet.

**Comment by troch** [comment]
You can use dispatch:

```js
import { actionTypes, actions } from 'redux-router5';
import { errCodes } from 'router5';

export const authRedirectMiddleware = ({ dispatch }) => next => action => {
    next(action);

    if (action.type === actionTypes.TRANSITION_ERROR && action.payload.transitionError.code === errCodes.CANNOT_ACTIVATE) {
        dispatch(actions.navigateTo('login');
    }
}
```

**Comment by kyungmi** [comment]
@troch I cannot naigate to the page that I wanted with the middleware as you wrote because of the action of the router5-history plugin. This history plugin force itself to navigate to the default route before the middleware catch TRANSITION_ERROR action. (https://github.com/router5/router5-history/blob/master/modules/index.js#L46)

**Comment by troch** [comment]
Yes I am aware of that, it does so because it doesn't know where to go otherwise. I guess I have to implement a way to tell the router where you want to go next in case of an error, i.e. with a custom error object containing a `redirect` key.

It would look like this:

```js
const = authCheckCanActivate = () => 
    api.authCheck().catch(() => ({ redirect: { name: 'sign-in' } });
```

**Comment by kyungmi** [comment]
@troch That's good. Do you have a plan to do that?

**Comment by troch** [comment]
Yes, I'll start working on it over the week end. I have the need myself for it on what I currently work on.

**Comment by troch** [comment]
I implemented it, I will run more tests and then release it.

**Comment by troch** [comment]
This was released on Sunday. Just to clarify, with promises you need to reject it:
```js
const = authCheckCanActivate = () => 
    api.authCheck().catch(() => Promise.reject({ redirect: { name: 'sign-in' } });
```
