### ISSUE TITLE
How I can parse path with many different optional parameters

### ISSUE THREAD

**Issue by max-mykhailenko** [router5/router5#50]
I have a simple path like `page/action/#a=1&b=2&c=3 ...` and I really don't know all parameters names. How I can receive them in object?

```javascript
{
  a: 1,
  b: 2,
  c: 3,
  //...many other parameters
}
```

**Comment by troch** [comment]
Are you asking for hash parameters? Linked to #51?

**Comment by max-mykhailenko** [comment]
Nope, I have a troubles when I initialize `Router`
```
const router = new Router5(
  [
    {
      name: 'report',
      path: 'report/?a&b&c&d&e', // and I don't know all params, how I can get all what url has
    },
  ],
  {
    defaultRoute: 'report',
  }
);
```

**Comment by troch** [comment]
I am not sure there is a way. There is a router option `strictQueryParams` which is `true` by default, turning it to `false` will match a route with non listed query params, but I don't think it parses them and add them to state.

**Comment by troch** [comment]
Matching them and adding them to the state is relatively easy to do, but what about building? If you navigate to a route (name and params), do you expect non-listed params to be added to the path as query params?

**Comment by max-mykhailenko** [comment]
Hm, yep, I expect to see all params in url. I think I should not to use router5 in this case. Possible I will write a custom router5Middleware (I use router5 with redux) without using `router.navigate` inside. Maybe you can give me some advice with this non-standard case.

**Comment by troch** [comment]
It's actually not that difficult to do, I have matching working. Building is a little more challenging because from a set of parameters with their value, I cannot tell how to serialize a list of values (using `[]` or not).

Another way to abstract away those extra parameters by serializing them in one query param, using JSON or something else:
`?a=1&b=2&params=7B%22c%22:3,%22d%22:4,%22e%22:5%7D` is
```js
{
    a: 1,
    b: 2,
    params: {
        c: 3,
        d: 4,
        e: 5
    }
}
```

**Comment by max-mykhailenko** [comment]
**About this issue:**
Thanks for your advice. I rewrite my module without and now it doesn't has router5 in dependencies.
This issue can be closed. It's not a problem of router5.
```javascript
function objectToUrl(params) {
  const urlParamsString = Object.keys(params).map(k => {
    if (Array.isArray(params[k])) {
      return params[k]
      .map(v => `${ encodeURIComponent(k) }[]=${ encodeURIComponent(v) }`)
      .join('&');
    }
    return `${ encodeURIComponent(k) }=${ encodeURIComponent(params[k]) }`;
  });
  return `?${ urlParamsString.join('&') }`;
}

const induceMiddleware = () => next => action => {
  if (action.type === actionTypes.NAVIGATE_TO) {
    window.history.replaceState(
      action.payload.params,
      '',
      objectToUrl(action.payload.params)
    );
  }
  return next(action);
};
```

**About another problem with dynamic unknown url params (not names at this time, but values)**
In my last projects I solve url problems using my own middleware, which only translates changes to url, but don't send data to store. I read url and parse it only on app init. It give me ability to solve problems like this:
- navigateTo url
- get ajax request which clarify url parameters
- navigateTo clarified url

If I do this using router5 I will get several store updates and first of them without required params which I will have only on the next step.

I will be very happy if you have thoughts how I can clarify url params without unnecessary store update at first step.

**Comment by troch** [comment]
Thanks for your feedback. I need to better handle unknown query params with router5. I currently don't have a lot of time but started some changes about a month ago: serialising extra parameters in URL and parse them too (I have parsing working).
