### ISSUE TITLE
QUESTION: Can I use the browser plugin but have each route specify when to use pushState vs replaceState?

### ISSUE THREAD

**Issue by tybenz** [router5/router5#506]
I'm looking for a router that will let me deep-link everything, but not necessarily use pushState for every granular route. I'd rather use replaceState for granular routes, and only use pushState for top-level route changes. Is this possible in the current version of router5?

**Comment by faergeek** [comment]
You can use [Middleware](https://router5.js.org/advanced/middleware) or [Lifecycle functions](https://router5.js.org/advanced/preventing-navigation) for that.

**Comment by tybenz** [comment]
Thank you!
