### ISSUE TITLE
Uncaught TypeError: this.buildPath is not a function

### ISSUE THREAD

**Issue by tnwt7** [router5/router5#54]
I have installed router5 via npm and got version 3.0.0
I used it with React using react-router5. When render my component which contains `BaseLink` this error: `Uncaught TypeError: this.buildPath is not a function` was thrown inside `function navigate(name)` at the line: `toState.path = this.buildPath(name, params);`

I also examine the source code and it looks like class `Router5` doesn't contain `buildPath` function.

**Comment by troch** [comment]
Odd. I'm using 3.0.0 and BaseLink and don't have an issue. `buildPath` is definitely a method on the router instance, what plugins are you using?

**Comment by tnwt7** [comment]
I am using `listeners` and `history`

**Comment by troch** [comment]
I have checked, none of them try to modify `buildPath`. I don't see what could cause an issue, it is a rather strange one. If you use `BaseLink`, actually `buildPath()` would be called through `buildUrl()` to generate the link href, before it would be invoked by `navigate()`.

Is the href of your link looking OK?

**Comment by tnwt7** [comment]
I remove all node modules and re-install again. It works fine now and cannot reproduce this issue. Thank you very much for your support, @troch
