### ISSUE TITLE
Router5 does not throw ROUTE_NOT_FOUND on initial render with no matching route.

### ISSUE THREAD

**Issue by tokenvolt** [router5/router5#55]
Let me explain what I mean.
For example, we have a non-matching route `http://localhost:8080/#/non-existent`. If I copy-paste it inside a browser address bar or try to change it from existing route in address bar, then the page is navigated to the defaultRoute, but I don't see transition error  ROUTE_NOT_FOUND being thrown.

If I make defaultRoute undefined, then I can see ROUTE_NOT_FOUND error. Is that intentional?

**Comment by troch** [comment]
Yes this is intentional. On start, if there is a default route, it will redirect to that default route if it cannot match the current URL with a route. Otherwise it will emit a `ROUTE_NOT_FOUND` error.

**Comment by tokenvolt** [comment]
My use case includes "go to `http://localhost:8080/#/non-existent` and show 404 page", but I still want users to be able to go to `http://localhost:8080` and show some default route. Do you have any advice how to achieve this?

**Comment by troch** [comment]
If you want full control over a 404 page, then don't define a default route. One trick is for your 404 page to be the default route..

**Comment by tokenvolt** [comment]
Yes I know, but the problem is that `http://localhost:8080` is considered a not found route in case of undefined default route, whereas `http://localhost:8080/#/` is ok.

**Comment by troch** [comment]
Are you using router-history? I think it is something I can fix there so `http://localhost:8080` is seen as `http://localhost:8080/#/`

**Comment by tokenvolt** [comment]
Yes, I'm using it.

**Comment by troch** [comment]
I've released router5@3.0.1 and router5-history@3.0.2. `http://localhost:8080` should match `/`,  whether you use hash or not.

**Comment by tokenvolt** [comment]
@troch Thank you very much! It's working =)

**Comment by troch** [comment]
You're welcome, closing this!
