### ISSUE TITLE
GET parameter not push to history

### ISSUE THREAD

**Issue by isergey** [router5/router5#56]
Hello!
I have next router:
```
const routes = [
    { name: 'search',      path: '/search?:query'},
    { name: 'detail', path: '/detail/:id'},
];

const router = new Router5(routes, {
	useHash: true,
	defaultRoute: 'search',
})
.usePlugin(historyPlugin())
.usePlugin(listenersPlugin())
.start();
```
When I make navigation like this:
```
router.navigate('detail', {id: id++});
```
I can back to previous id. But when I make navigation like this:
```
router.navigate('search', {query: query++});
```
I can't back to previouse query value. Why?

**Comment by troch** [comment]
A change of state will cause a new history entry to be added, whether it is caused by a URL or query parameter..

**Comment by vojtech-dobes** [comment]
Hi, I've just updated to newest version and it looks like bug - `navigate` to route that differs only in query parameter seems to do `replaceState` even though I pass `replace: false` specifically.

**Comment by troch** [comment]
I've made a change recently to router5-history around the use of `reload`, it has caused it.

router5-history 3.0.3 fixes it. Let me know if it doesn't.

**Comment by vojtech-dobes** [comment]
Great, fixed :).
