### ISSUE TITLE
Why are URLs concatenated?

### ISSUE THREAD

**Issue by fairbairn** [router5/router5#57]
Given the sample code below...

~~~
import Router5, {loggerPlugin} from 'router5';
import historyPlugin from 'router5-history';
import listenersPlugin from 'router5-listeners';

const routes = [
    { name: 'loan',                         path: '/loan/:id/detail'},
    { name: 'loan.pricing',                 path: '/loan/:id/pricing'}
];

const options = {
    useHash: true,
    defaultRoute : 'dash',
    base: '/static/'
};

function createRouter() {
    let router = new Router5(routes, options);
    router.usePlugin(listenersPlugin());
    router.usePlugin(historyPlugin());
    return router;
}


let router = createRouter(routes, options);

console.log(router.buildUrl('loan', {id:1}));
console.log(router.buildUrl('loan.pricing', {id:1}));
~~~

The output is:

~~~
$ babel-node test_url.js 
/static/#/loan/1/detail
/static/#/loan/1/detail/loan/1/pricing
~~~

Why is the second url generated concatenated?

We want the 'loan' route at the node level so we can do this...

export default connect(routeNodeSelector('loan'))(OurComponent);

but it incorrectly generates the links, manually, and using BaseLink, for the secondaries.

We need the URLs to be...
~~~
/static/#/loan/1/detail
/static/#/loan/1/pricing
~~~

**Comment by fairbairn** [comment]
Apparently the segments are actual route segments, so you can't define the path explicitly, you need to define the path per segment understanding they will concatenate.

Not sure we originally gleaned that from the docs, but we went back and changed all our paths to be partials and we can get around our mis-assumptions.

Would be kind of nice to not have to think in terms of nesting, but I guess the engine works that way.  Reality is we may want to organize routes with certain parent nodes but we want the actual routes to be unrelated.

I don't see a way to do that.

Could we ever do the following?

home   /home
home.dash /dash
home.profile /profile
?

Seems we'd have to give up some of the reselect efficiencies if we wanted custom paths.

Maybe there could be an override condition to the route definition so we could define it as explicit from root (/) rather than segmenting?

I just like the idea of separating concerns between the benefits of the "name" property (and how they might render under react) and the actual route displayed to the user within the browser.

**Comment by troch** [comment]
If you use `.` in a route name, then it extends the path of its parent. It's just a habit to get. The reasons for nesting are:

- More efficient matching by traversing a tree
- Representing with names the hierarchy of your UI

> Could we ever do the following?
Seems we'd have to give up some of the reselect efficiencies if we wanted custom paths.

Having the router targeting the node to update is nice and efficient, but not doing it is not that bad. With your home / dash / profile example, if you want independent URLs then you'll need to not nest them.

> Maybe there could be an override condition to the route definition so we could define it as explicit from root (/) rather than segmenting?

I completely understand your idea of wanting to decouple URLs structure from route / UI structure. The buiding path part would be achievable, but with the way route matching is architected, it would add complexity and edge cases. I'll give it more thoughts.

**Comment by fairbairn** [comment]
So I have a question about the utility of routeNodeSelector.  We can't really seem to find a use-case in our scenario, and questioning what value it has when we're at root ('').

Say we have the following top level routes from root..

A
B
C

It's not uncommon that we'll have sub-pages under these routes, with the "landing page" reacting to the primary route name (for example A).

So let's say our UX has tabs across the top that match up to our routes - A, B, and C, and there are 5 sub-navs that will appear when you click on A...

A
A.two
A.three
A.four
A.five

and this is the rub, when someone goes into route A, we want it to immediately show our first sub-nav option, with others available via links.  That way, the routes make sense, otherwise we'd have to have an A.one and A would fire NotFound.  The urls would "jump" from root to A.one (/A/one) rather than typing /A and it goes to essentially what we would show for A.one.

But if we have A, as well as A.sub in our node rendering logic, then if we use routeNodeSelector to get some performance benefits, we can't get it right because if we set it to 'A', then it won't repaint properly.  If we set it to root (''), what's the point?

We have this across our application, and so we can't seem to benefit from routeNodeSelector triggering only the necessary route node to repaint.

Are we missing something in our architecture?
Are our routes just not conducive to using routeNodeSelector?
Is there really an impact if we don't?
Finally, what is the purpose of routeNodeSelector('').  Our primary default node has logic to draw different components depending on the route (say R1, R2, R3, which stem from root).  It's the top node always and hence the transition node so it seems at the '' route it will always trigger a repaint through the selector.  Is that not correct?

**Comment by troch** [comment]
It has a utility when you have nested components as a result of nested routes. The '' won't always trigger a repaint, it all depends on the transition path. If you go from A to B, or A.two to B, it will repaint. But if you go from A.two from A.three, 'A' will trigger.

A good overview on how it works: http://router5.github.io/docs/understanding-router5.html

The efficiency of using it really depends on how many components you avoid to re-render unnecessarily on a route change.
