### ISSUE TITLE
Router Question/Problem

### ISSUE THREAD

**Issue by DavidStrada** [router5/router5#59]
Hi!,

I'm testing your router5 package and ran into a problem where when i git back/forth on the browser it doesn't load the templates from "pushState", I'm using 2 of your plugins `'router5-history';` and `'router5-listeners';`

I've prepared some sample code to illustrate my app.

 [main File](https://github.com/DavidStrada/route5-example/blob/master/src/app.js)

[Repo](https://github.com/DavidStrada/route5-example.git)

Thanks

**Comment by troch** [comment]
The `start` callback is only called on start, it is not a callback invoked on every route change.

```js
router.addListener((toState, fromState) => { /*... */ });
```

There are different types of listeners you can register: http://router5.github.io/docs/listeners.html

**Comment by DavidStrada** [comment]
Hey, 

Thanks for writing back, somehow i missed that one, I uploaded the solution onto an example repo, perhabs you would like to include it onto your examples ? --> [Repo](https://github.com/DavidStrada/route5-example.git)

Thanks!

**Comment by troch** [comment]
I'll add a link, can you change the name of your repo to `router5-example`? Thanks.

**Comment by DavidStrada** [comment]
Sure :) there you go —> https://github.com/DavidStrada/router5-example

**Comment by DavidStrada** [comment]
yay!, I’ll add a more detail Readme later today.
