### ISSUE TITLE
UMD wrapper for dist/browser/router5.js

### ISSUE THREAD

**Issue by fabien** [router5/router5#6]
Usually you'd want the final `dist` file to be a single bundled umd-style file.

**Comment by fabien** [comment]
On a related note, I see that this `if/else` syntax works, even when transpiled to plain JS:

https://github.com/router5/router5/blob/master/modules/transition.js#L29

Is this 100% safe in all browsers/js environments? It looks a bit strange at first, but apparently it's OK.

**Comment by troch** [comment]
- UMD wrapper: not sure how to do this, will need to explorer tooling for bundling an UMD module. Do you use UMD?
- if/else: I actually don't like the way it is transpiled from ES6 to ES5. I'll add a code linter and code style checker.

**Comment by fabien** [comment]
Hi @troch I do use UMD (or more specifically RequireJS with AMD). It shouldn't be difficult to add this - probably just some wrapper code around your current browser/router.js file.
