### ISSUE TITLE
Adding meta data to routes

### ISSUE THREAD

**Issue by hellosmithy** [router5/router5#60]
Is there a way to add meta data to route definitions? e.g. specify a route `component` property that the view could then use, or is this considered an anti-pattern?

I see there is a `_meta` property used internally. However this seems to be stripped and recreated in the `route-node` package.

**Comment by troch** [comment]
> Is there a way to add meta data to route definitions?

Are you talking about state objects or the way you configure routes?

**Comment by hellosmithy** [comment]
@troch the way routes are configured - I'd like to add some extra data to the route definitions. It's not a big deal as there are other ways to do it. I just wondered if there was any existing mechanism for this.

**Comment by troch** [comment]
So you can have a route configuration array / object, and you can add any information you wish to add to it. It will simply be ignored by the router (it is only interested in route names, path and children if using an object).

On a route change, you then grab your route registry and find the component to render. You could also use a middleware to attach the component to render on the state object (see http://router5.github.io/docs/middleware.html#adding-data-to-state).

Direct coupling between router and view is an anti-pattern in my opinion, that's why the router shouldn't be aware of your components.

**Comment by hellosmithy** [comment]
@troch I agree the route itself should not be coupled to the view, but I'm happy to couple my route definition to a particular component as I usually end up making that mapping somewhere anyway.

Thanks for your help.

**Comment by troch** [comment]
> I'm happy to couple my route definition to a particular component as I usually end up making that mapping somewhere anyway.

That is perfectly possible. You own your routes definition: the router is only interested in parts of it, but is not the only entity consuming it. Middlewares are a good way to consume other parts: I for example do it with `onActivate` hooks (data loading functions) and page titles.

**Comment by iotch** [comment]
> You could also use a middleware to attach the component to render on the state object (see http://router5.github.io/docs/middleware.html#adding-data-to-state).

AFAIK, it's impossible to add any non-serializable value when using history plugin. For example, browser throws error when trying to pass React components with the state:
`DOMException: Failed to execute 'replaceState' on 'History': An object could not be cloned.`

**Comment by troch** [comment]
Hi @SmirnovW, custom data passed to the router will be ignored. Looking at the historic of this conversation, I'm not sure what I was talking about 😕. But you can inject data to the route state in middleware.

**Comment by SmirnovW** [comment]
@troch 
I've seen your comment:

> So you can have a route configuration array / object, and you can add any information you wish to add to it. It will simply be ignored by the router (it is only interested in route names, path and children if using an object).

As I understood, it's gonna be ignored, but not removed from a route. Currently, it's removing from the route object. Am I right?

The middleware's not an option, I'd like to define a "meta" data directly in a route object. And I think it's a pretty popular case.

**Comment by jamalsoueidan** [comment]
The easiest way is to go through routes and get the data yourself.

```javascript
routes.find(r => r.name === route.name)
```

Something like this, for nested you have to split the string and try to find the children down the path.

It would have been nice to have this helper inside router5-helper package.
