### ISSUE TITLE
Nested routes throws error.

### ISSUE THREAD

**Issue by durgesh-priyaranjan** [router5/router5#61]
I am using hash routing. And my route map is:

```
[{
	name: 'layout',
	path: '/layout',
	module: {
		"moduleName": "layout",
		"instanceConfig": {
			"container": "#app-container",
			"placeholders": {
				"header": "Router",
				"aboutUs": "About Us",
				"aboutUsURL": "#/layout/about",
				"contactUs": "Contact Us",
				"contactUsURL": "#/layout/contact",
				"career": "Career",
				"careerURL": "#/layout/career"
			}
		},
		"module": RootModule
	}
},{
	name: 'layout.about',
	path: '/about',
	module: {
		"moduleName": "about",
		"instanceConfig": {
			"container": "#page-container",
			"placeholders": {}
		},
		"module": RootModule
	}
},{
	name: 'layout.contact',
	path: '/contact',
	module: {
		"moduleName": "contact",
		"instanceConfig": {
			"container": "#page-container",
			"placeholders": {}
		},
		"module": RootModule
	}
},{
	name: 'layout.career',
	path: '/career',
	module: {
		"moduleName": "career",
		"instanceConfig": {
			"container": "#page-container",
			"placeholders": {}
		},
		"module": RootModule
	}
}]
```

Now, when I try to hit "http://localhost:****/#/layout/about", error is thrown as 
`
index.js:11 Uncaught TypeError: Cannot read property 'split' of undefinednameToIDs @ index.js:11transitionPath @ index.js:26transition @ transition.js:51_transition @ router5.js:575onPopState @ index.js:67
`
Its not getting fromState.

My router config is:

```
{
	useHash: true,
	hashPrefix: '',
	trailingSlash: true,
	logger: true,
	history: true,
	defaultRoute: 'layout'
}
```

Is there any issue in my configuration?

**Comment by troch** [comment]
I can't see an obvious issue with your routes configuration (history is not a valid option, but that's harmless to pass it to the router).

`transitionPath` is a function from `router5.transition-path` package: https://github.com/router5/transition-path/blob/master/modules/index.js, and `nameToIDs` gets called in there. The `transitionPath` called is triggered by the `router5-history` plugin through a call to `router5._transition()`.

The stack trace is slightly odd. Are you mutating your route names? What seems to happen is the state object it tries to split the name from has a name property which is not a string.

**Comment by durgesh-priyaranjan** [comment]
Thanks @troch for very prompt response. Found issue, I was attaching canActivate for every route and it wasn't returning promise.

Closing the issue.

**Comment by troch** [comment]
You don't need to return a promise. You can return true / false, a promise or call a done callback. I should try to throw meaningful errors / warnings
