### ISSUE TITLE
Unable to pass parameter with braces

### ISSUE THREAD

**Issue by fairbairn** [router5/router5#63]
Looking for a way to leverage Link / BaseLink in order to pass an :id parameter as a string-formatted GUID / UUID which has curly braces.

With a route of..

name = record
path = /record/:id

if I attempt to pass the routeParams of { id : "{any kind of guid value}"} the underlying path-parser fails with  "Some parameters are of invalid format".

Even if I encodeURIComponent the guid, it still fails.

Looking at path-parser, which router5 is based on (correct?), this is the code..

```
if (!opts.ignoreConstraints) {
            let constraintsPassed = this.tokens
                .filter(t => /^url-parameter/.test(t.type) && !/-splat$/.test(t.type))
                .every(t => new RegExp('^' + defaultOrConstrained(t.otherVal[0]) + '$').test(params[t.val]));

            if (!constraintsPassed) throw new Error('Some parameters are of invalid format');
        }
```

I would think we should be able to pass any kind of string into routeParams and it would perform the encoding properly.  The value itself has nothing to do with the pattern for building the path, so I'm unclear why it's failing.

Is there a way to have Router5 and path-parser accept a key/value pair for route params where the value contains braces?

Do we need to pass in ignoreContraints to path-parser, and if so, what do we pass into Link or BaseLink in order to achieve this bypass?

**Comment by troch** [comment]
http://tools.ietf.org/html/rfc1738#page-3 states `{` and `}` are unsafe characters in URLs, they need to be encoded. That said, it doesn't work when encoded, I need to check why.

**Comment by fairbairn** [comment]
That's great.

So since this affects two projects, how should we reference router5 and path-parser in our package.json to get both the fix from path-parser (because we use it separately) and router5 with the updated internal dependency?

**Comment by troch** [comment]
`npm update` should update it for you since it is a patch, or removing manually router5 directory in node_modules (or path-parser if you have npm3+) and `npm install`.

**Comment by fairbairn** [comment]
Even though route-node specifically references 1.0.2?

Will give it a shot though.

**Comment by fairbairn** [comment]
Still have an issue, now that I get around Link failing by passing { id: encodeURIComponent('{myguidstring}')}, then issue is when the url is encoded, the route.params key/value result has it encoded instead of decoded.  It should return as '{myguidstring}' but it comes back encoded which puts everything out of whack.

Personally, I think it should be transparent.  We should be able to pass in the key/value params for the route without regard to URI encoding, and it should decode it when parsing the route returning us back the native value.

Right now it's mismatched.

**Comment by troch** [comment]
That was an oversight, `1.0.4` has been released with encoding of parameters

**Comment by fairbairn** [comment]
Thanks.  It broke me though, apparently path-parser will URI encode what 
is already URI encoded, I had URI encoded my braces and it was working 
before, then upgraded, and when I pass my params down into path-parser 
it re-escaped my % chars from the prior encoding, which of course messed 
up my url.

Now I'm a bit in a mix, so have to refactor.  For clarity, when using 
Link within router5, do I need to pre- encodeURIComponent my {guid} 
strings, or will it do that internally now?  When I pass params into 
path-parser (because we use it to generate API routes), should it now 
NOT be pre encoded in order to keep the URL correct?

Not entirely sure when we need to do it (or not) since the update.

Thanks!

**Comment by troch** [comment]
Don't encode anything since it will be encoded by path-parser.

**Comment by fairbairn** [comment]
Got it.  Thanks.

You dream it.  We build it!

Breakthrough Technologies
breakthrough-tech.com
