### ISSUE TITLE
Async loading routes

### ISSUE THREAD

**Issue by iotch** [router5/router5#64]
Hello.
What's the best way to load a part of the routes definition on demand? 
For example, if app is big and code needs to be split - what's the approach to load child routes and associated code on transition to that route, and after the route loaded wait for all children's `onActivate` to resolve? 
Thanks!

**Comment by troch** [comment]
There are two ways to do it:
- You can either use a middleware which will delay the transition to make sure components you need for your route are available
- Or you can do it at the component level with the use of containers

You mention `onActivate`: data and components are two different things from the point of view of your application, and it is up to you how you organise your control flow. It is your view which matters and the one which has to wait for both data and components (not your router :))

**Comment by iotch** [comment]
Thank you for the quick reply, Thomas. 
Ideally I want my components were not aware of router and routes at all. I'd like to configure the routing outside of React hierarchy and tell React to render already nested components, not to decide what child the component should render. In this case I need a sindle HOC Router component which will make all the work of linking routes definition to the React components hierarchy. Example result:
```jsx
<RouterHOC>
    <Shop><Category><Shoes /></Category></Shop>
</RouterHOC>
````

My thoughts were the following:
1. There is a routes array, where `children` of some route objects are promises, that resolves to an array of child route objects. This is useful, to have the whole bundle configured separately - when another team is working on a site section, for example, `/shop` section, and the child routes of `shop` section are set and configured (including data loading with `onActivate`) within it's own bundle.
2. Middleware 1 on navigation to '/shop/category/shoes' detects the promise and waits for it. Promise resolves to:
```js
[
  {
    name: 'category',
    path:'/category'
  },

  {
    name: 'category.shoes',
    path:'/category/shoes'
  }
]
```
3. Middleware 2 waits for middleware 1 to resolve and after that it is aware of all the '/shop' children resolved. Then it maps `shop.category.shoes` to `<Shop><Category><Shoes /></Category></Shop>` and when the React component tree ready, resolves the own returned promise.
4. On successful transition RouterHOC renders the resulting component tree as it's children.

But such middleware chaining is not possible at the moment, so I'm not sure how to achieve both code splitting and data preloading with middleware. What am I missing? 
Thanks!

**Comment by iotch** [comment]
Oh, I'm sorry, was using same logic to add middlewares as adding plugins - with a new function call for each middleware. With the proper `useMiddleware()` syntax promises works as expected.

**Comment by troch** [comment]
Cool, is that your issue solved then?

**Comment by iotch** [comment]
Unfortunately not. It seems that I can't go that path because router needs to be aware of all the children routes before start matching, so I can't have unresolved children of '/shop' when navigating to '/shop/category/shoes' and expect that `/shop` will be matched anyway - I'm getting ROUTE_NOT_FOUND error before any middleware or plugin gets called.
I came to Router5 with the react-router background, so maybe I need to rethink the way a router should work... The really great feature of react-router is the ability to match partial routes and hold the transition and make a decision what and do next on each route nesting level from within `getChildRoutes()`.

**Comment by troch** [comment]
Ah OK I see. router5 doesn't offer that kind of route matching (load and pray), it doesn't need to. I believe react-router came to that solution because they needed to support code splitting, and they could only achieve it that way since with `<Route />` you do two thinks: you register a route, and you map that route to a component. With router5, route registration is not tied to component mapping, so you can define all your possible URLs up-front and then let your view react to route changes.

I conceptually treat code-splitting the same way I treat data loading: I trigger component loading if needs be on a route change with a container component displaying a loading feedback during the time the required component is not available. Once it is available, it renders it.

**Comment by iotch** [comment]
thanks!
