### ISSUE TITLE
Update history state on error

### ISSUE THREAD

**Issue by iotch** [router5/router5#65]
Hello.
Is it possible to update the URL in the browser's address bar after error occurred? For example, to tell the user at which URL error has happened and display an error page with the proper address, not the previous one. There is a `replaceHistoryState()` method, but it replaces, obviously.
thanks.

**Comment by troch** [comment]
Do you mean navigating away from your application?

**Comment by iotch** [comment]
I'm sorry, English is not my native language so seems my explanations are not clear...
Example: user is on page at /a navigates to /b. If transition was successful - browser url updates to /b. If not - it stays at /a. How to update to /b after error?

**Comment by troch** [comment]
If the transition is not successful:
- Route was not found and in that case you can use your default route as a fallback route
- Because it failed in `canActivate`, `canDeactivate` or in one of your custom middleware. You can add a `redirect` field to your errors: http://router5.github.io/docs/custom-errors.html.

**Comment by iotch** [comment]
OK, another example:
User browses a list of items at `/items`, and clicks at `/items/12345`. Data for the item `12345` is fetched by `canActivate()` (or by middleware) and for some reason fetch failed. I'd like to display an error message and have the url `/items/12345` so, for example, user can copy the url and tell the support team that  `/items/12345` is failing. If I'll use redirect - user will see irrelevant page address (like /error). 
So will be great to have `updateHistoryState()` provided by the history plugin, not only the `replaceHistoryState()` public method.

**Comment by troch** [comment]
In that case don't use `canActivate`. `canActivate` is designed if you absolutely don't want your User to access a route (and therefore don't have the URL added to their history). Having something like `updateHistoryState` would defeat the purpose. `replaceHistoryState` is a cheat designed to be used in very specific cases.

In your case I would do the error handling within your view rather than the router.

**Comment by iotch** [comment]
Handle error within the view is what I'm trying to achieve, actually. The goal is to handle all errors in one place, not let the each component (React in particular) to decide what error page to display - it's against DRY principle. Rather I'd like to subscribe the app to error event and display an error page component that aware of error code and displays different messages for example 'page not found' for the ROUTE_NOT_FOUND or a custom message for the custom error code returned by middleware. 

IMO it's a useful feature to make the developer decide whether to update history to next state after error has occurred or not, depending on use case. If you have one cheat, why not to have two? Or have the history plugin option that enables state update for the specific cases too?

**Comment by troch** [comment]
>  not let the each component (React in particular) to decide what error page to display - it's against DRY principle

I never suggested you repeat yourself. I'm suggesting you don't block a transition and then ask for the history to update anyway. This is simply not possible, and really not recommended. State updates are not  error updates. If you want your state to contain error info, then set up a route you redirect to on error, serialising the error as a query param.

**Comment by iotch** [comment]
> set up a route you redirect to on error

It's a bad practice to redirect on errors - if the user navigates to the page '/a/b/c' and this page (or route, in this case) is not found - an error component/message should be displayed for the given url _in place_, not after redirect to a dummy `/404` page. This is the expected behaviour for any error pages. Like: https://www.google.com/not-existent-page
Please, consider implementing such behaviour. I'm not sure about the right way to do it, I'm not good at Router5 internals for now, but something like:

````js
/* somewhere in a plugin */
onTransitionError: function(toState, fromState, error) {
    if(error.code === errCodes.ROUTE_NOT_FOUND) {
        this.router.updateHistoryState(toState.name, toState.params);
    }
}
````

**Comment by troch** [comment]
I'll look at another option (a wild card route). What you propose, I don't really like and don't think it can work (not the update history part, but the update the view part and back and forward buttons).

**Comment by iotch** [comment]
Thanks! The code above is a simplified part of my React plugin that builds a tree of view components based on route-to-component mappings and updates the RouterHOC state to re-render next screen. So on error instead of components tree, HOC is rendering the error page component with the error prop containing the info about the error. So it works, but replaces history instead of updating for now.

**Comment by troch** [comment]
An update: with `router5@4.0.0`, a new option `allowNotFound` will be available. If set to `true` and not default route is defined, then the router will generate a state like this (if you navigate to `/not-found`):

```js
{
    name: '@@router5/UNKNOWN_ROUTE',
    params: { path: '/not-found' },
    path: '/not-found'
}

**Comment by troch** [comment]
v4.0.0 has been released: http://router5.github.io/docs/migration-4.html.

See http://router5.github.io/docs/migration-4.html#unknown-routes-not-found-supported: with the option `allowNotFound` and without a set default route, the router will output a state for not found routes.
