### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by iotch** [router5/router5#66]
Hello. 
Getting this error when using history plugin and navigating with browser history buttons with the following routes config:
````js
const routes = [
    {
        name:'a',
        path: '/a',
    },
    {
        name:'b',
        path: '/b',
        canActivate: function(toRoute, fromRoute, done) {
            setTimeout(done, 5000);
        },
    }
];
````

Steps to reproduce:
1. navigate programmatically between routes to build a browser history
2. navigate back/forward while route 'b' is not yet resolved
This error happens right after the TRANSITION_CANCELLED event at: https://github.com/troch/route-node/blob/master/modules/RouteNode.js#L112

thanks!

**Comment by iotch** [comment]
This happens when no 'defaultRoute' option specified, history plugin tries to navigate to `undefined` here:
https://github.com/router5/router5-history/blob/master/modules/index.js#L55

**Comment by durgesh-priyaranjan** [comment]
I guess this fix is yet to be published on npm.
