### ISSUE TITLE
multiple useMiddleware()

### ISSUE THREAD

**Issue by iotch** [router5/router5#69]
Hello.
What is the reason of:
> Calling useMiddleware again will cause previously registered middleware functions to be deregistered.

thanks!

**Comment by troch** [comment]
As opposed to plugins (which are for side-effects: history, analytics, page title, etc...), order of middlewares matter. For that reason, I've added this constraint so one explicitly states the order of middlewares.

**Comment by iotch** [comment]
What do you think about pushing into middewares array instead of replacing? The order will remain the same - from first added to last, but will allow to add data-fetching middlewares from within different parts of config - for example, if the app is big and some of it's parts loaded on demand as modules. In this case each module will able to add own data-fetching (or any other required) middleware.

**Comment by troch** [comment]
The idea is a bit more like a redux store: you create your store with middlewares upfront. I could eventually add an `addMiddleware` function, but then why not have a `removeMiddleware`, etc...

If you have a data fetching middleware, it's perhaps best to have one middleware but then add data loading functions rather than individual middlewares.

**Comment by iotch** [comment]
Why not to give the route5 user some freedom in his app architecture? :) You have a great 'low-level' routing solution for those who feel that, for example, react-router isn't flexible enough. Router5 API is great and allows to solve 90% of issues related to routing in a specific use-cases because of it's flexibility and extendability.  Will be great to have those 10% as well :)

**Comment by troch** [comment]
I guess you are right. I'll add an `addMiddleware` method.

**Comment by iotch** [comment]
thank you, Thomas!

**Comment by troch** [comment]
With version 4, you can use `useMiddleware` multiple times, with one or multiple arguments, without overwriting already registered middlewares.
