### ISSUE TITLE
Uncaught TypeError: t is not a function

### ISSUE THREAD

**Issue by Crazy-Ivan** [router5/router5#7]
Hey, i think in the new version there is a bug. 
I found that even your examples stop working. Check this out in free time. 
http://router5.github.io/docs/with-react.html#/inbox. 

I don't know if this is a bug, however in my case router doesn't react on first page load. I think this something what each router should do. Should be able to recognize initial state. I will try to prepare some examples later in jsfiddle. I really like idea behind your router (if i understand it correctly), however it doesn't seems to work as it is described at the page. Maybe those information are not up to date ?

**Comment by troch** [comment]
It seems I didn't build properly last night. I will fix it in the next hour.

Thanks

**Comment by troch** [comment]
Hi @Crazy-Ivan, it was a bug. Fixed with v0.2.2, very sorry about that.

I will take time today to add a new documentation page describing in details the initialisation phase and transition phase. If you can tell me what is unlear to you, it would help.

**Comment by troch** [comment]
3ecc838bbe44f11c38e814242176d94a911e48f9

**Comment by Crazy-Ivan** [comment]
Thanks a lot, now it works much better :). However :),  in the new version 0.2.4 there is an issue with the path to the dist file. I use jspm to install your lib.
```
jspm install npm:router5 
```
In new version is something wrong with the file path.

When i try to include the lib.
```
include router5 from 'router5';
```

I get error from system.js
http://example.com/lib/npm/router5@0.2.4/dist/commonjs/Router5.js (404) not found
there is no such a file like Router5.js, there is router5.js

**Comment by troch** [comment]
Oops, it should be fixed with 0.2.5

**Comment by Crazy-Ivan** [comment]
Awesome :+1:
