### ISSUE TITLE
Not listed query parameters disappear 

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#70]
Hi, maybe it's related to #50 
Handling query parameters is not quite clear.
I want to read several query parameters, names of which I don't really know beforehand, for instance `utm_*` values. And this params should not affect route matching, they can appear on any page.

Now even if I specify `strictQueryParams: false`, I can't get them from `params` object, and moreover - they disappear from url after middleware processing finished.

**Comment by troch** [comment]
Two things from this issue: query parameters not listed not appearing in state (they should). The root route is an empty path `''`: one trick you can use (I'll see how to support it with the router API) is to have your root route path something like `'?utm_'`. Look here: https://github.com/router5/router5-persistent-params/blob/master/modules/index.js#L18

**Comment by klimashkin** [comment]
Do you mean something like this?
```
[{
  name: '', path: '?utm_', children: [
    ...
  ]
}]
```
But in this case i have an error
`Uncaught Error: RouteNode.add() expects routes to have a name and a path defined.`

**Comment by troch** [comment]
` router.rootNode.setPath('?utm_')`

I don't have yet an API to configure the root node.

**Comment by troch** [comment]
Not listed query parameters are now serialised in state params (when `strictQueryParams` is set to false). A patch was just released on `route-node@1.4.5`, just re-install router5 to get it.

**Comment by klimashkin** [comment]
Strange, but i don't  see not listed query parameters in `toState.params` in my middleware.
Moreover, if I write query parameter in url that is not listed in routes,  `toState.params`  is always empty, even if url contains also listed parameters

**Comment by dmitriid** [comment]
`"router5": "4.3.0"`

I still have this issue: `strictQueryParams: false` is set, but the params are cleared:

```typescript
const routes = [
  {
    name:     'events',
    path:     '/events',
    children: [
      {
        name:     'id',
        path:     '/:id',
        children: [
          {
            name: 'misc',
            path: '/:city-name/:venue-name/:event-name'
          }
        ]
      }
    ]
  }
]

const router = new Router5(routes, {
  // defaultRoute:      'events',
  strictQueryParams: false,
  autoCleanUp:       false
})

const broswerPlugin = browserPluginFactory({
  useHash: false
})


router.usePlugin(broswerPlugin)

router.start(...)

```

- without `strictQueryParams: false` the router would redirect to the defaultRoute
- with `strictQueryParams: false` clears out any params in the query string (i.e. `/a/b/c/d/?x=1` becomes just `/a/b/c/d/`)

We solved it by listing all the `utm_*` params, but this is a bit confusing :)

**Comment by troch** [comment]
Thanks for your detailed report, will look at it.

**Comment by troch** [comment]
@dmitriid I think this is solved by latest version (4.4.0)

**Comment by dmitriid** [comment]
Awesome! Thanks, I'll try to try it early next week!

**Comment by dmitriid** [comment]
@troch Just to confirm. It works! Thank you!
