### ISSUE TITLE
Documentation lacks a good overview.

### ISSUE THREAD

**Issue by mik01aj** [router5/router5#71]
I'm reading the documentation and it's hard for me to understand where would router5 go in my app. In the simplest form, I understand the router as something that maps urls to states. But the introduction doesn't talk about this. Let me quote the very first sentence:

> The main idea behind router5 is to treat routes like any other application data / state. 

Okay, cool, I expect a nice pure functional router. But then in another place I read that calling `.start()` will bind the router to the browser state. In my understanding, this contradicts the "main idea"!

Then I see:

> With router5 it is reversed: rather than the router updating the view, it is up to the view to listen / bind / subscribe to route changes in order to update itself.

So I suppose that the router has some internal state, and I can push URLs and listen to state changes. Right?

I try to be constructive, and not just complain about the docs I didn't write. But the introduction would really, really benefit from a "big picture" overview. This can be one paragraph, or an example with 10 lines of code, that would explain the Router5's place within an app. (e.g. should my UI create a router, or will the router create my UI?)

Maybe I'll even prepare one when I understand it better. ;)

**Comment by mik01aj** [comment]
And a consistency question:

```
let r1 = new Router5([{name: 'view', path: '/view'}]);
let r2 = new Router5(route); r2.add({name: 'view', path: '/view'});
let r3 = new Router5(route); r3.add([{name: 'view', path: '/view'}]);
let r4 = new Router5(route); r4.add(new RouteNode('home', '/home'));  // why Node and not Route?
let r5 = new Router5(route); r5.addNode('view', '/view'); // shorthand? why?
```
All these are equivalent, right? Then it would be also good to explain this in docs.

**Comment by troch** [comment]
Yes, unfortunately the documentation doesn't receive as much care as I'd like to give it.

`.start()` doesn't bind the router to the browser state. Plugins handle side-effects like `router5-history` (update URL and listen to popstate events). The start method is there to start the router after it has been configured, it allows you to start it with a given URL (server-side node for example), with a given state (client-side hydration for example). Not providing any start information will fallback to `getLocation()` method which returns nothing by default, but is decorated by router5-history plugin.

> So I suppose that the router has some internal state, and I can push URLs and listen to state changes. Right?

Yes, the router has some internal state: its current state. The current state is needed to compute a transition path for nested routes.

> Maybe I'll even prepare one when I understand it better. ;)

I'm in the middle of writing version 4.0.0. It snowballed a bit, but I'll dedicate some time to upgrading the docs for and after that release. And for sure, I would immensely appreciate any help.

**Comment by dogoku** [comment]
On the topic of docs, I'd like to add that the `strictQueryParams` option is not listed in the API reference for the Router5 constructor or the `setOptions` method. In fact, `setOptions` has no documented options whatsoever

**Comment by troch** [comment]
Options are documented here: http://router5.github.io/docs/router-options.html

**Comment by troch** [comment]
I'll focus on improving the docs in the coming months, making it less scattered and more approachable (going from very basic to more complex examples).

Any advice is welcome :smile:

**Comment by troch** [comment]
Didn't mean to close.

**Comment by jwoudenberg** [comment]
On this subject: I'm not sure if it's removal was intentional, but I'm personally really missing the API page at the moment. I guess it's not the most useful landing page for people new to router5. Once you pass the examples phase though, it works great as a reference page.

I was using it a lot for quick reference lookups, like "what was the method called again?" or "what arguments does that take?".

**Comment by troch** [comment]
I'm going to bring it back, I've ran out of time and went for releasing 4.0.0 anyway (and not delay it any further).

**Comment by troch** [comment]
@jwoudenberg API reference is available again

**Comment by steve-craft** [comment]
Hi, 
I'm implementing your idea about using middleware exposed in https://router5.github.io/docs/async-data.html 
There something I didn't catch on the version without redux : running the onActivate and passing params. Is there a magic I don't know about ?
I solved it by just adding call to the onActivate methods explicitely (between onActivateHandlers selection and the Promise.all): 
	const lastHandler = onActivateHandlers.pop();
	const activaters = onActivateHandlers.map((oa) => oa(null));
	if (lastHandler !== undefined) 
    		activaters.push(lastHandler(toState.params));	
and I pass activaters to the Promisse.all rather than onActivateHandlers.   		
It solved my simple case where params is passed only in the last segment, but it doesn't cover more complex cases. A word about it in doc would be appreciate. :-) 

Long live router5.

**Comment by troch** [comment]
Looking through it, seems there are a few things not making sense. Will update. Thanks!

**Comment by steve-craft** [comment]
Hi, another remark about the middleware page (https://router5.github.io/docs/async-data.html ) but on the redux example : a 
done()
shouldn't be added at the end of the onRouteActivateMiddleware method ? Because one could use the Promise.all as above, but this is then blocking.

**Comment by troch** [comment]
Closing for now, I try to keep documentation up to date, and fix errors when they are mentioned to me.
