### ISSUE TITLE
Prevent navigation in middleware

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#72]
Hi!
If I return promise from middleware and want to prevent navigation, what data should be in thrown error?
code: TRANSITION_CANCELLED or TRANSITION_ERR?

**Comment by troch** [comment]
`TRANSITION_ERR`. `TRANSITION_CANCELLED` will be triggered if:
- You cancel a route transition yourself
- You navigate to a new route while the router is transitioning

**Comment by klimashkin** [comment]
- "You cancel a route transition yourself"
You mean `router.cancel()`?
I saw that it's private method https://github.com/router5/router5/blob/master/modules/router5.js#L497

But if redux-router5 uses it, seems like  it safe, thanks!

**Comment by troch** [comment]
I had not documented it, and at the time the `@private` meta key was only for it to not appear in the docs. I had forgotten about it.

**Comment by troch** [comment]
> But if redux-router5 uses it, seems like it safe, thanks!

Safe and tested.

**Comment by klimashkin** [comment]
By the way, is there a way to catch transition cancel or some hook?

**Comment by klimashkin** [comment]
Got it, plugin with 'onTransitionCancel' handler
