### ISSUE TITLE
Make middleware depends on context

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#73]
Hi!
I have middleware that prefetch async data for further react rendering and it's rely on some flags.
So that flags can be uniq for each request on server side, what means that I need something like context in middleware for each `router.start(url)`. Or put middleware function on each router.start instead of applying it once on router creation.

**Comment by troch** [comment]
In version `4.0.0`, you'll be able to use closures in `(router) => (toState, fromState, done)`. Execution will happen on start.

**Comment by klimashkin** [comment]
Great! Is there any shipping plan for 4.0.0?

**Comment by troch** [comment]
End of the month is what I'm aiming for. I have two weeks holiday starting tomorrow, and during the 2nd week I'll be able to focus on it a lot more.

**Comment by troch** [comment]
Middleware functions are thunks executed when registered. The returned function will be executed on each transition, and context is preserved with closures.

```js
function(router, dependencies) {
    return function(toState, fromState, done) {
    };
}
```

**Comment by klimashkin** [comment]
Now i'm a little bit confused. Do we really need it If we `createRouter` on each http request on server side? Anyway it's necessary to run `useMiddleware` on each route creation

**Comment by troch** [comment]
> Do we really need it If we createRouter on each http request on server side

It is preferable. Since it's not stateless, you can't allow a single instance to be accessed by multiple requests.
