### ISSUE TITLE
Transitions are not cancelled properly if cancel several consecutively

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#74]
Lets assume I have 3 links on page and middleware that delays `done` by 5 seconds
If I'm clicking fast on each of link from 1 to 3 in series, eventually only number 3 leads to route change. That's correct.

But if I listen `onTransitionCancel` and wind up some async action that middleware calls on transition cancellation, it terminates middleware immediately. And in the same case while I clicking from 1 to 3:
On clicking on 1 middleware starts async action for it;
On clicking on 2 transition to 1 is canceled in correct way and middleware starts async action for 2;
On clicking on 3 transition to 2 is not canceled but fulfilled immediately with its middleware termination! What means that url is being changed to 2. And middleware starts async action for 3, which will be fulfilled when async action returns ok what will change url to router 3.

I found workaround. If on `onTransitionCancel` I throw error from middleware instead of just returning, it prevents url changing to 2.
But it's seems like hack, and in console I see `Transition cancelled` for 1 when click on 2, and then `Transition error with code TRANSITION_ERR` for 2 when click on 3. Therefore, for instance, if I have 10 links and click on each of them fast in sequence, first will be canceled, and 8 next will have transition error.

**Comment by troch** [comment]
Looking into it

**Comment by troch** [comment]
Cannot replicate using some tests (not in the browser). Do you have code for this exact scenario? I am making some changes to have cancellations executing done callbacks immediately rather than waiting for the end of a middleware function before replying. I'll keep an eye on the issue.

**Comment by troch** [comment]
I believe v4 should fix this issue, but I couldn't replicate it so I'm unsure about my claim.
