### ISSUE TITLE
Replace on redirect

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#75]
Seems like it's not possible to pass `replace` option on redirect error from middleware.

But it's really needed - it's strange to give user ability to navigate back to broken page, in this case by pressing back button user comes again on redirected page. So maybe `replace` option should be by default on error redirect

**Comment by troch** [comment]
`redirect` is used for errors, and therefore the errored transition doesn't add a new history entry. Pressing the back button would normally redirect to the last known and successful state

**Comment by troch** [comment]
Currently here is what happens:
- If coming from a popstate event, it replaces: the router cannot transition to the current history state and replaces it
- On start it always replaces, whether it is a redirect or not
- If coming from an in-application call of `router.navigate`, it doesn't replace. But I wonder if I should respect the options initially passed, or enable the use of a `replace` flag as you proposed

**Comment by klimashkin** [comment]
For instance if user opens blank page and goes to root route, and I throw redirect error from my middleware function to navigate to nested route like this
`throw {redirect: {name: 'app.nested'}}`
it ends up at this line 
https://github.com/router5/router5/blob/master/modules/router5.js#L547

In this case `window.history.length === 3`, and on `history.back()` user goes to root route, that redirect it back to nested again, so user can't get back easy.
But should be `window.history.length === 2` and on `history.back()` should navigate to blank page

**Comment by klimashkin** [comment]
To be clear: On our project we have root route `'/'`, but only for fetching something from backend in middleware and redirect to one of the nested routes, depending on data that was returned from backend.
Therefore user should not see root route. If he comes from external website, by pressing back button he should return on referral website instead of root node

**Comment by troch** [comment]
On a blank page / page load, `start` is invoked, not `navigate`. The line you are pointing at should not be invoked, instead redirection on start is handled by this one: https://github.com/router5/router5/blob/master/modules/router5.js#L238. It is always a replace on start. I do similar stuff (redirect from log in to the main page if you already signed in) and I've not noticed issues with the history length. I'll change the line you mentioned to inherit navigate options, and look more in depth to what could cause what you experience.

**Comment by troch** [comment]
Closing this. In version 4, redirect inherits options from navigation. It only replaces if the intention was to replace for the transition which failed. Please re-open if you are experiencing issues.
