### ISSUE TITLE
How to add Query String parameters

### ISSUE THREAD

**Issue by yofret** [router5/router5#76]
Hi First of all, sorry for posting this in issues, I just wasn't sure where to ask this, since I can't find in the docs, basically what I want to do is, add query string parameters with any given names

for instance

/path?foo=2
/path?var=1

I only have 1 route node, I tried adding `/path?param` but it only match when param is present, the idea here is that the queryParam could have any given name

Thanks

**Comment by troch** [comment]
Setting `strictQueryParams` should work for you: http://router5.github.io/docs/router-options.html#strict-query-parameters

**Comment by yofret** [comment]
Cool, that worked, but I want to capture parameters on router change

/path
to
/path?foo=2

this doesn't trigger a route change, and it make sense, since the route is the same, the question is where can I capture these parameters

**Comment by troch** [comment]
This should trigger a route change. Can you give me more details about how you are using router5?
