### ISSUE TITLE
Initial canActivate leading to "redirect" renders getState() unusable

### ISSUE THREAD

**Issue by vojtech-dobes** [router5/router5#79]
We have following `canActivate` call:

```
router.canActivate('r1_foo', (router) => (toState, fromState, done) => {
	return Promise.reject({
		redirect: {
			name: toState.name.replace('r1_', ''),
			params: toState.params,
		},
	});
});
```

This gets correctly executed and browser address bar gets updated. But when we call `router.getState()` afterwards, it returns `null`.

**Comment by troch** [comment]
I have a test case with that scenario (`canActivate` returning a rejected promise containing a redirect directive), and it works fine. I also have that configuration in production and it also works fine.

Is it something which was working before 4.0.0 release? Could you try to change it to the following, to check if the promise is not swallowing an error:

```js
router.canActivate('r1_foo', (router) => (toState, fromState, done) => {
    done({
        redirect: {
            name: toState.name.replace('r1_', ''),
            params: toState.params,
        },
    });
});
```

**Comment by vojtech-dobes** [comment]
> Is it something which was working before 4.0.0 release?

Nope, we've added this code only after upgrading to 4.0.0.

> Could you try to change it to the following, to check if the promise is not swallowing an error:

Works like a charm :). Thank you very much.

**Comment by troch** [comment]
> Works like a charm :). Thank you very much.

So what was the issue? Just switching from promise to done callback fixed it?

**Comment by vojtech-dobes** [comment]
> Just switching from promise to done callback fixed it?

That's right.

**Comment by troch** [comment]
That's weird :confused:!
