### ISSUE TITLE
Using defaultRoute path as /

### ISSUE THREAD

**Issue by ismail-codar** [router5/router5#8]
I am setting up my router like [{name: "index", path: "/"}, {name: "test", path: "/test"}.....], defaultRoute = 'index' and it not working right. If directly entering www.sitename.com/test router redirects www.sitename.com 

{name: "index", path: "/index"} is working good. But this time default page url displays form of www.sitename.com/index . 

Because partialMatch function matches on path: "/" settings. https://github.com/router5/router5/blob/master/dist/browser/router5.js#L208 So..

```javascript 
_urlMatch("/test", new RegExp('^' + "\/")) returns {}
_urlMatch("/test", new RegExp('^' + "\/index")) returns null

**Comment by troch** [comment]
Thanks for reporting this.
It looks like I have to do more sorting here (possibly using path length as a sorting criteria): https://github.com/troch/route-node/blob/master/modules/RouteNode.js#L44

**Comment by ismail-codar** [comment]
I've tested. Thank's you for your work.

**Comment by troch** [comment]
:+1:
