### ISSUE TITLE
Consider locking dependencies if router5 wants to be stable.

### ISSUE THREAD

**Issue by kierson** [router5/router5#82]
I had a situation where on my build with the same version of router5 (3.0.3) my application worked properly, but on my co-workers (also router5@3.0.3) didn't (of course we had the same source code of the app).
The reason was that router5 has dependency on route-node, which some time ago (from version 1.4.3) changed the way of handling route parameters object that contains null or undefined values.
We use such values when we extend current route parameters for adding new parameters and removing one like this

const routerState = Object.assign({}, route.params, {
      param1: 'someVal',
      param2: 'someVal2,
      paramWhichIKnowWeHaveToRemove: undefined
});

this.context.router.navigate('myRoute', routerState);

In version of node-route <= 1.4.2 this will just remove param "paramWhichIKnowWeHaveToRemove" from URL. From version 1.4.3 it will add paramWhichIKnowWeHaveToRemove=undefined to the URL.

It is just example, I can handle it my own way, but it was quite hard to debug what was the reason of changing this behavior.

**Comment by troch** [comment]
It seems a bug was introduced when patching `route-node`, which was not intentional and I apologise for the inconvenience. A new patch will be deployed before the end of the week.

**Comment by klimashkin** [comment]
Wow, I do it manually everywhere, didn't know it was possible by transferring `null` directly to route-node.
You should definitely mention it in docs, it's very widespread case!

**Comment by troch** [comment]
router5@4.0.5 contains the latest patch from route-node (@1.4.7). It should fix the handling of undefined and null values in query parameters.

**Comment by kierson** [comment]
Thanks for very quick response and fix!
