### ISSUE TITLE
Nullifying route param should remove it from params object

### ISSUE THREAD

**Issue by klimashkin** [router5/router5#83]
Thanks for fixing https://github.com/router5/router5/issues/82#issuecomment-246206744

Now if specify `{myparam: null}` it will remove `myparam` from url, but it is still remains in params object as `{myparam: null}`. If param has been removed from url, it should be removed from parameters object as well, otherwise it confuses.

**Comment by troch** [comment]
Note sure if I agree or not. The URL is only a representation of the state object, not the other way round. Param are not removed from URL, they are just not serialised into it.

Currently you can add any param to `navigate`, even params which are not in your route definition. I use this for example for specifying where to redirect after the login screen. Something like this could break existing implementations.

**Comment by klimashkin** [comment]
> Param are not removed from URL, they are just not serialised into it.
But it's the same in the end - url doesn't contain the parameter :)

**Comment by troch** [comment]
It could be a breaking change. I'm not against doing it, but it will have to wait for the next major release. What about you decorate (monkey patch) `router.makeState`? https://github.com/router5/router5/blob/master/modules/create-router.js#L75-L89

Something like that:

```
const originalMakeState = router.makeState;

router.makeState = (name, params, ...args) => {
    const cleanParams = cleanParamsObject(params);

   return originalMakeState(name, cleanParams, ...args);
};
```
