### ISSUE TITLE
# hash based routing

### ISSUE THREAD

**Issue by emildimitrov** [router5/router5#84]
Hi guys, 

I'm evaluating router5, but couldn't find info regarding hash based routing instead of history based.
Can some one provide info regarding this topic? I just wan't to know is hash based routing supported and does it play well with redux.. 

Thanks a lot in advance,
Emil Dimitrov

**Comment by troch** [comment]
Hi Emil,

The router is a state machine, outputting state updates to whoever want to listen to them: it plays very well with redux. See https://github.com/router5/redux-router5 for more details, example here https://github.com/router5/examples/tree/master/apps/react-redux.

There is hash based routing available but it uses HTML5 history (i.e. it uses the history API and popstate events, not hashchange events, so you need history support). For syncing router state with your history, you need to use the `browserPlugin`. I've just updated the docs: http://router5.github.io/docs/history.html

**Comment by emildimitrov** [comment]
Well then, sorry for my misunderstanding.. my brain is just really used to the default hashChange & history driven routes.. 
So instead of choosing between #user/details & /user/details we can just stop worrying about whats going out in the url bar... and even not use it for transition between our screens ( in SPA )..

**Comment by troch** [comment]
The decision to use `#` or not is more a backend-driven decision (i.e. can you serve an index.html on any route or just on your domain root). I don't support `hashchange` since I don't need it myself and it has not been requested / implemented by users until now. That said, it's wouldn't be that difficult to implement a plugin. It would basically consist of:
- On transition success, update the hash URL
- On hash change event, ask the router to navigate to the new path

**Comment by emildimitrov** [comment]
My concern was the browser support.. some support hash change some history api.. sad story. With state machine driven approach this doesn't look like issue, but and ux decision. After thinking about this approach i found it flawless ( in the context of client side SPA ), because by nature the url bar is meant for get requests to server and the # is meant for navigation to id.. not for client side routing..  in general i really feel natural a state machine for content transition & similar interactions. 
Really appreciate your work! This is future.
