### ISSUE TITLE
Support for routing in modal windows ( sticky state )

### ISSUE THREAD

**Issue by emildimitrov** [router5/router5#86]
Hello guys,

I'm trying to figure out how to implement routing in modal window.. without loosing the current route (fragment). The real world scenario is lets say you are in /main/something and you are about to click a button to redirect to /main/deposit, but deposit requires user to be logged in so it triggers displaying of modal window in which you can go to /auth/login, /auth/register etc etc and after that proceed with /main/deposit.

I'v seen examples with ui-router http://christopherthielen.github.io/ui-router-extras/example/stickymodal/index.html#/people/managers . I still can't figure our how to implement this approach with  router5.. if i transition to new tree the current tree will just unmount, but i want to keep it alive in some kind of inactive, but not unmounted state.

Thanks in advice,
Emil Dimitrov

**Comment by troch** [comment]
Hi Emil,

Keep in mind router5 just gives you state and does not render any components for you. In your app, if you have modals, you probably open them as a result of a state change. Well for routing, nothing changes, open and close modals as a result of a app state change, including routing state.

**Comment by emildimitrov** [comment]
Yeah i know, but with modal & current route we have two independent active states lets say /main/something and from main/something we invoke auth/login with myRouter.navigate('login', {modal: true}, but we want main/something to stay active while auth/login to be also active.. 

Like in the example:

router.canActivate('profile', (router) => (toState, fromState, done) => {
    return isUserLoggedIn()
        .catch(() => Promise.reject({ redirect: { name: 'login' }}));
});

router.navigate('profile', (err, state) => {
    // err is null
    state.name === 'login';
});

bout without deactivating the current active route

**Comment by troch** [comment]
I know ui-router-extras and the concept of "sticky state". I've used Angular and ui-router for a while and at the time I never really understood why you would want to persist a controller, when you could just offload its data in a factory (when the scope is destroyed) and grab that data from the same factory when a new instance of a controller is produced. To me, that is a failure to distinguish between data and presentation layer.

The same applies for router5. It will give you a tiny part of your app state, the other part being everything else like current user, data from an API, etc... You can't have "two active states" but your app state should help you determine if you need to bring a modal or not, display a component, etc... Remember that with router5 you have access to the previous route.

I don't have a recipe to give you, it really depends on your view layer, how you manage modal dialogs, etc... But I would encourage you to not think like ui-router-extras, think in terms of view / state separation: state can persist longer than views.

**Comment by emildimitrov** [comment]
Showing single modal with actions is not a problem at all.
The general problem is that routing (state changes) needs to be done in these modals with all the state trees etc etc.. while current state is preserved in the background. At the moment the only solution i can think of is having two router5 instances one for general app tree and one for modal tree. And the workflow will be something like 
- from **router1** state 'main.list try to change state to 'main.deposit'
- 'main.deposit' could not be activated because user is not logged
- because of that from 'main.list' we fire state change in **router2** (which operates like separate app but in modal) 'auth.login' and from there 
user can change states to 'auth.register' 'auth.recover' etc in the modal while preserving in background the state of the main app **router1**
- when user logs we discard router2 (modal app) and go back to navigating to 'main.deposit' from router1.

Looks little overhead, but since we can have more than one active state per router instance this seems valid. What do you think?

**Comment by troch** [comment]
Two routers wouldn't work, or to be more precise the problem would be with using more than one browser plugin.

A view is not forced to update on a router state change, you could do different stuff depending on the previous route or other app state (like logged in status).

**Comment by troch** [comment]
Closing for now.
