### ISSUE TITLE
Allow duplicated path

### ISSUE THREAD

**Issue by veraee** [router5/router5#87]
I would like to have duplicated path in my routes definitons.
The Use case: I need to navigate from state A to state B while on the page, but for the state B I do not have an URL which works on the server, hence state B cannot be reached via typing an URL into the browser, but that's ok, state B should not be reachable by URL - it is a kind of "intermediate" state.

Do you think it is a feasible idea?
My patch would: via an option: on route definition: allow duplicate path, do not change browser URL, if it keeps the same, use the one _not_ marked via option as target state when reaching the page via typing in the URL.
Maybe: use some (generated) hash value as browser URL for the intermediate state, so my server does not bother on page realod.

**Comment by veraee** [comment]
...and as this is my first post here: thank you for router5 - it's great!

**Comment by troch** [comment]
What you are proposing is path-less routes. I don't how feasible it is, I've not thought about ways to implement it yet.

**Comment by troch** [comment]
The "longest" one will match first. "longest" means number of params / segments / characters.

**Comment by troch** [comment]
I won't support this: I'm trying to limit the amount of configuration and option to get set-up with router5. a `forwardTo` option was added recently (see #154), which prevents some states to be reached (and instead they are "forwarded" to another route): it might work for your case.
