### ISSUE TITLE
Have an option for _not_ concatenating path values

### ISSUE THREAD

**Issue by veraee** [router5/router5#88]
As far as I see the paths gieven in the router definiton are concatenated for child nodes.
So with state names and path
```
a        /A
a.b      /B
a.b.c    /C
```
the real path for node c will be "/A/B/C"

In my case, the URLs do not have the same hierarchy structure as the node hierarchy.
My URL for a.b is "/A/B", but for a.b.c it is "/somethingCompletyDifferent"

Is it possible have the option _not_ to concat the paths from root node to the target root?

Thanks in advance

**Comment by troch** [comment]
I can look into that. Doesn't seem not feasible.

**Comment by troch** [comment]
OK, that's not difficult to implement. However, there are restrictions: you can't have a nested route with an absolute path if a parent has parameters.

**Comment by troch** [comment]
I've added support for absolute paths `~/path`. For now it's disabled for children which parents have parameters.
