### ISSUE TITLE
Documentation out of date / confusing

### ISSUE THREAD

**Issue by dmitriid** [router5/router5#89]
Going through docs, I ran into the following:

- http://router5.github.io/docs/configuring-routes.html  
  "Adding routes to your router" uses `createRouter` as example. I guess it should be `new Router5(...)`?  
  Or should specifically say  
  ```
import createRouter from 'router5'; 

const myRouter = createRouter(...)
```

- http://router5.github.io/docs/plugins.html  
   All plugin examples links except `Logger` lead to 404s

Will add more if/when I find more gotchas

**Comment by troch** [comment]
This part has missed an update. Thanks for bringing my attention to it, it has been updated (`new Router5()` is the router5@<4 syntax)

**Comment by dmitriid** [comment]
wooho!
