### ISSUE TITLE
Map multiple paths to same Route

### ISSUE THREAD

**Issue by dogoku** [router5/router5#90]
Hi again! Thanks for all your efforts and releasing 4.x.

After updating (which was a breeze btw), I was eager to use the new `allowNotFound` option to show errors without changing the url. However this is not possible as long as I have a `defaultRoute`.

The only reason I have a `defaultRoute` configured is for people navigating to `/` to be redirected to `/home`.  I know this can be handled inside a middleware, but wouldn't it be better if we could declare this during config?

E.g:

``` javascript
const routes = [
    { name: 'home', path: '/'},
    { name: 'home', path: '/home'},
    ...
];
```

or 

``` javascript
const routes = [
    { name: 'home', path: ['/', '/home'] }
    ...
];
```

I have a feeling that there's some deep reason why this can't happen, but here's to hoping :)

**Comment by troch** [comment]
v5.1.0 has a new feature called "route forwarding" which can be used for aliasing. See #154
