### ISSUE TITLE
Newbie question: npm test: mocha: quotes on file pattern (a windows problem?) 

### ISSUE THREAD

**Issue by veraee** [router5/router5#91]
I tried to run
  npm test

it stops with 
`Error: cannot resolve path (or pattern) ''tests/**/*.js''`

the single quotes seem to be used literally,

when I change the line in package.json from
    `"test": "mocha --compilers js:babel-core/register --recursive --require ./tests/_helpers.js 'tests/**/*.js'",`
to (removing the single quotes around `tests/**/*.js`)
    `"test": "mocha --compilers js:babel-core/register --recursive --require ./tests/_helpers.js tests/**/*.js",`
it works, all test pass.

Is this expected behavior?
Thanks in advance,

**Comment by troch** [comment]
Probably a windows issue, I removed them since they are apparently not needed.
