### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by iotch** [router5/router5#92]
Hello, Thomas!
Have you considered to provide and maintain definition file for typescript?
Thanks.

**Comment by troch** [comment]
Yes, it is something I'm aware would be nice to provide. I don't use TypeScript, and would be happy to help any effort.

**Comment by slively** [comment]
These are working pretty well for me, I ended out having to write my own for rxjs-router5 though: https://www.npmjs.com/package/@types/router5

**Comment by troch** [comment]
@slively I think those definitions are from v3 (v4 was an internal refactor).

**Comment by Keats** [comment]
I made https://gist.github.com/Keats/1b8833b581d01e751048e1f51041817f

It's not complete though

**Comment by troch** [comment]
@Keats that's really helpful. Would you mind starting a PR?

**Comment by Keats** [comment]
Yep will do so in a bit

**Comment by Keats** [comment]
Anyone good at writing definition files or has an example of definition that works for something like https://gist.github.com/Keats/1b8833b581d01e751048e1f51041817f#file-router5-d-ts-L132 ?

I'm pretty sure the `declare module` should not be there.

**Comment by troch** [comment]
Added to v4.6.0
