### ISSUE TITLE
Unknown Route

### ISSUE THREAD

**Issue by jamalsoueidan** [router5/router5#93]
I have configure Router with

 `{ allowNotFound = true}`

but I'm not getting any new routing state in my application_layout.

```
const ApplicationLayout = ({route}) => (<div>{route.name}/div>)
export default connect((state) => routeNodeSelector(''))(ApplicationLayout);
```

Because im getting this error:

> Transition error with code ROUTE_NOT_FOUND

I'm trying to catch any unknown urls, and render specific component!

**Comment by troch** [comment]
Did you solve your issue?

**Comment by jamalsoueidan** [comment]
Yes :)
