### ISSUE TITLE
How can I navigate to previous page?

### ISSUE THREAD

**Issue by wenpengfei** [router5/router5#95]
Hi, 

I have a react web application use router5...

How can I navigate to previous page ?  just use history.back() ?

**Comment by troch** [comment]
Yes you can use `history.back()`, it will trigger a popstate event which will be caught by the browser plugin. Alternatively, you can use `router.navigate(name, params)` if you know your previous route and if you want to create a new history entry.

**Comment by wenpengfei** [comment]
@troch thaks!
