### ISSUE TITLE
Router params update

### ISSUE THREAD

**Issue by jamalsoueidan** [router5/router5#99]
Hello,

I'm trying to save actions to url, so visitors can undo actions by going backward and forward in the browser.

My setup is as follows *USE ONLY*

```
state {
  history: ...
}
```

...if you wish to save the old state. Then I created redux middleware to save *state.history*, I generate a new ID, and want to bring it up to URL, but can't figure it out?

I tried with

`router.navigate(router.getState().name, {history: lastGeneratedId})`

This doesn't work, i hope you can help me with this one :)

Here is my snippet code: [https://gist.github.com/jamalsoueidan/d87f61c733e2a6c64c48bf81fc0c3d7a](https://gist.github.com/jamalsoueidan/d87f61c733e2a6c64c48bf81fc0c3d7a)

**Comment by troch** [comment]
I'm not sure I follow all the details. Is it simply a case that you want to synchronise the URL following user actions, rather than navigate to a new state?

**Comment by jamalsoueidan** [comment]
I would like to have different components on the same page to sort the list or other things, and I would like to visitor to undo this by clicking go back on the browser.

So I have a middleware in redux that look at the state.history and compare old history with the new one, if anything changed I would like to generate a new params in the url, so when the user go back, the old state.history is pushed in redux and the old state is set.

:)

**Comment by troch** [comment]
In the browser, you can rely on the browser history for going back and forward. You cannot amend the router state but you can replace it using `.navigate` with option `replace: true`. That's how you would "would like to generate a new params in the url". The best way is to compute those params before navigation in the first place.
